### PR TITLE
More Global Defaults

### PR DESCRIPTION
**Pull request by Soare-Robert-Daniel**
Implemented:

- Icon List
- Tabs
- Accordion
- Progress Bar
- Review
  - [x] CSS
  - [x] Products Features
  - [x] Update to fix the focus bug
- Circle Counter
- Slider
- Leaflet
- Google Map
- Lottie
- Popup

### CODE REVIEW

**Comment by HardeepAsrani** [comment]
@Soare-Robert-Daniel We only need features as if people just check same type of product, they might be using the same features to compare between, while Pros/Cons will always be different.

**Comment by HardeepAsrani** [comment]
- Section & Column's default tag
- Accordion's Gap thing doesn't look right, the padding/margin issue. Same with a few other fields.
- Review one looks weird, you should put the currency in its own tab and close the color ones.
- You can remove Progress Bar, Circle Counter, Tabs, Icon Block, Slider, Maps, Google Maps, Lottie, Popup, Icon List
- With the left, you can put them in alphabetical order.

We need these for blocks that people like to keep unified, like Buttons, Sections, and such, not for Maps and stuff. And we also don't want to overwhelm them with defaults.

**Review by HardeepAsrani — CHANGES_REQUESTED** [review]
- Section & Column's default tag
- Accordion's Gap thing doesn't look right, the padding/margin issue. Same with a few other fields.
- Review one looks weird, you should put the currency in its own tab and close the color ones.
- Product Feature also has the focus issue like rest of the plugin had.
- You can remove Progress Bar, Circle Counter, Tabs, Icon Block, Slider, Maps, Google Maps, Lottie, Popup, Icon List
- With the left, you can put them in alphabetical order.

We need these for blocks that people like to keep unified, like Buttons, Sections, and such, not for Maps and stuff. And we also don't want to overwhelm them with defaults.

**Comment by Soare-Robert-Daniel** [comment]
> * Section & Column's default tag

Do you want them removed?

> * Accordion's Gap thing doesn't look right, the padding/margin issue. Same with a few other fields.

I don't know what to do about this. The only things that apply to it are `margin: 0px`  and `padding: 10px` for alignment.

**Comment by HardeepAsrani** [comment]
@Soare-Robert-Daniel

1. Yea, Tag can be removed.

2. Okay, I'll take care of CSS in the end and see what could be causing it and if there's an easy solution.

**Comment by HardeepAsrani** [comment]
I made minor changes @Soare-Robert-Daniel, just letting you know:

- I added Section Default tag back as I realized it was already there so harder to remove because people might be using it.
- You had mistakenly removed Font Awesome Icons block. When I said Icon Block, I meant the Icon List & its child. Sorry for the confusion.

**Comment by HardeepAsrani** [comment]
@irinelenache Can you make sure all the new global defaults work properly?

The new ones are:

- Accordion
- Review

**Review by HardeepAsrani — APPROVED** [review]

**Comment by irinelenache** [comment]
@HardeepAsrani Tested and didn't find any issue 👍

**Pull request merged**
