### PR TITLE
Flip Card Fix

### PR DESCRIPTION
**Pull request by Soare-Robert-Daniel**
#### Changelog
- Fix the wrong class name on the `save` function
- Fix alignment 

⚠️ Those are breaking changes.

### CODE REVIEW

**Comment by Soare-Robert-Daniel** [comment]
@irinelenache, the steps for testing are:

1. Insert a Flip Card and add a large image as a Featured Image in `Inspector > Front`.
2. Make sure that in Preview the image respects the default setting. It should have the size 150x150.

Go back to the editor:

1. Increase the width and the height of the card.
2. Test the vertical & horizontal positions in `Inspector > Front`.

E.g.: 
image

**Comment by irinelenache** [comment]
@Soare-Robert-Daniel Tested and the alignment works as expected 👍 
Found something else:

- [ ] The **media width & height** work only in editor, they have no effect in frontend
editor: https://vertis.d.pr/iUX3Wk
frontend: https://vertis.d.pr/UeapKl

- [ ] The **title color** doesn't work in frontend
editor: https://vertis.d.pr/F4ZUME
frontend: https://vertis.d.pr/Y13Kjc

- [ ] The **Box shadow** properties work only for the back of the card, i don't know if this is expected:
front: https://vertis.d.pr/s8pYyu
back: https://vertis.d.pr/5k3JbA

**Comment by Soare-Robert-Daniel** [comment]
> * [ ]  The **Box shadow** properties work only for the back of the card, i don't know if this is expected:
>   front: https://vertis.d.pr/s8pYyu
>   back: https://vertis.d.pr/5k3JbA

Shadows are supposed to be a highlight when flipping to the back. The behavior is ok.

@irinelenache can you do a re-test?

**Comment by irinelenache** [comment]
@Soare-Robert-Daniel The reported issues are fixed, thanks 🚀

**Pull request merged**
