### PR TITLE
Icon Enhancement

### LINKED ISSUE #802: Icon - enhancements
### Should have
- [x]  Add Alignment options in the Right sidebar also, and make them device based. 
Usecase: I have 3 boxes with Icons and text aligned to **left**, and **on mobile I want them centered**.
- [x] Change the current default size for the Icon from 16px to 32px

___
### Nice to have:
- [ ] Add Icon templates which are basically shortcuts to a certain look, that can be adjusted later.
image

- [x] At some point maybe add the Core selector with 3 Sizes and a 4-th one for Custom value. This one is from Qubely: 
image

- [ ] Maybe it's possible to add the light variation for Font Awesome. For some demos we need Icons that use a thin border, one example [is this one](https://www.figma.com/file/HH1bO1qpDwsLws7jalmTFe/Architect?node-id=344%3A2271). And even if we have the Themeisle Icon font that's thiner, I think it would help to have font-awesome variation that's thiner

### PR DESCRIPTION
**Pull request by Soare-Robert-Daniel**
Closes #802.

### Summary

- Add responsive alignment
- Change font-size to 32px as default
- New size picker for Icon Size

### Screenshots 

<image width="170" src="https://user-images.githubusercontent.com/17597852/187419148-4dfeb6e3-32aa-49e7-8f7c-54ea3d33fdc9.png" />

----

### Test instructions

1. Add FA Icons block
2. Play with the settings.
3. Add a Countdown block and do the same (they share a component, we need to make sure that it is working in both)

#### Query
```javascript
new QueryQA().select('blocks').where({ names: ['icon-alignment-and-responsive'] }).run()
```

---- 

### Checklist before the final review

- [ ] Visual elements are not affected by independent changes.
- [ ] It is at least compatible with the [minimum WordPress version](https://wordpress.org/plugins/otter-blocks/).
- [ ] It loads additional script in frontend only if it is required.
- [ ] Does not impact the [Core Web Vitals](https://web.dev/vitals/).
- [ ] In case of deprecation, old blocks are safely migrated.
- [ ] It is usable in Widgets and FSE.

### CODE REVIEW

**Comment by Soare-Robert-Daniel** [comment]
@Codeinwp/design-team, this is how the control panel for Dimensions look

https://user-images.githubusercontent.com/17597852/186854339-08e4aa16-6f0f-4377-bd71-662330d79a3a.mp4

Feel free to test it.

**Comment by JohnPixle** [comment]
The changes look good but I feel that for manipulating the icon's size it is **more intuitive to use a slider** instead of a traditional type size control. I understand that the icon essentially is a font-icon but from the user's perspective I think it will be better to use a slider.

Let me know your thoughts.

**Comment by Soare-Robert-Daniel** [comment]
@mghenciu do you think that Controler from Font Size is a good fit for Icon like the one that you suggested from Qubely?

**Comment by mghenciu** [comment]
@JohnPixle , what do you think if we use the Core pattern, where the Custom size is enabled and you can change the value inside by dragging the mouse: 

https://user-images.githubusercontent.com/52494172/186941422-1b21b2a1-7d3e-4bce-8528-7889cd0d7da1.mov

The idea with having predefined size, is to make the life easier for users, as my assumption is that you'll need one of those values; if not - that can be adjusted.


___

@Soare-Robert-Daniel , there look to be some issues there, from the fact that the Icon Selector popup doesn't close itself when clicking outside: 

https://user-images.githubusercontent.com/52494172/186941941-7c853649-cb62-44b4-8997-edb4222eb6e1.mov




from how this build reacts when importing Icons from previous builds.
I imported the one from here, and first of all all the Icons are centered, and I can't change that, from the Toolbar:
https://themeisle.com/plugins/otter-blocks/demo-blocks/icon/
[icons-sections.json.zip](https://github.com/Codeinwp/otter-blocks/files/9434512/icons-sections.json.zip)

https://user-images.githubusercontent.com/52494172/186942472-d78fd5e7-c137-4e83-8d91-d79156622b7b.mov


___
**Question**: is it possible to use this type of controls for alignment?
image

**Comment by irinelenache** [comment]
@Soare-Robert-Daniel Tested and didn't find any problem 👍 If the design team approve it, it can be moved to **Ready to merge** 🚀

**Comment by JohnPixle** [comment]
> The idea with having predefined size, is to make the life easier for users, as my assumption is that you'll need one of those values; if not - that can be adjusted.

I am eventually fine with this @mghenciu, and I noticed that the predefined values that you selected actually make sense. Thanks!

**Comment by Soare-Robert-Daniel** [comment]
> @Soare-Robert-Daniel , there look to be some issues there, from the fact that the Icon Selector popup doesn't close itself when clicking outside:

For me is working in Vivaldi (chrome based) and Firefox


https://user-images.githubusercontent.com/17597852/187612304-fc0e721d-7247-4835-b96e-0692c33e9441.mp4

**Comment by mghenciu** [comment]
> For me is working in Vivaldi (chrome based) and Firefox

ok, so this is a tricky one, I don't remember how exactly I managed to init this bug, **but found some weird repro steps now**. **It may be related to the number of clicks and the input field**:
1. Create a fresh WP instance with the Otter Dev build
2. Open a clean page
3. Add a Icon Block
4. Click on the Icon Selector
5. from the Popup - double click on the AWESOME keyword
6. then click inside the search field
7. again, double click on the AWESOME keyword
8. now, try to click outside to close the selection Popup

Using latest Chrome & latest macOS.
___
Video following the **Repro steps**, using the current build:

https://user-images.githubusercontent.com/52494172/187937523-28cdaef4-0901-4d8a-8ea7-a1d3171febf2.mov

**Comment by Soare-Robert-Daniel** [comment]
@mghenciu, that thing is messing with the internal WP component detection. 

A simple solution is to provide a Close button and not rely exclusively on outside click.

image

**Comment by mghenciu** [comment]
> @mghenciu, that thing is messing with the internal WP component detection.
> 
> A simple solution is to provide a Close button and not rely exclusively on outside click.

Not ideal, as the bug would still be there - but looks like a good workaround for now.

Maybe have it as a small X icon on top-right corner? as the blue close button is quite visible at the moment, but it will be used only when this bug happens (I mean the usual way of clicking outside, should still work):

Screenshot 2022-09-02 at 13 51 24

**Comment by Soare-Robert-Daniel** [comment]
@mghenciu something like this 

image

**Comment by mghenciu** [comment]
yeah, a bit smaller maybe (or it just looks big now because of the image size) - and using the text color (FONT AWESOME ICONS).
Similar to the one from Core >> 
image

**Review by HardeepAsrani — CHANGES_REQUESTED** [review]
Video: https://www.loom.com/share/ff75694d4404456d97b3f4518f884a19

- We shouldn't change the default size as it becomes too big. Personally, I think that's too big for the icons but the main concern here is that people, who will update the website, will just see icons which are pretty big.

- Alignment doesn't work properly in the backend.

- There's an issue with the Padding/Margin

**Comment by Soare-Robert-Daniel** [comment]
> * Alignment doesn't work properly in the backend.

I did not notice the one from the controls. I made a separate controller for alignment in Inspector. 


image

Should we keep them both or just the one from Inspector? The one from the Inspector has the responsive controller unlike the one from Controls.

> * There's an issue with the Padding/Margin

This was theme related. A style was setting the sizing to be `border-box` instead of `content-box`

**Comment by HardeepAsrani** [comment]
> Should we keep them both or just the one from Inspector? The one from the Inspector has the responsive controller unlike the one from Controls.

It's a bit confusing to have both if one of them only applies to current screensize while the control is responsive. I was confused so I'm guessing a lot of users can also be confused. What do you think @mghenciu?

**Comment by mghenciu** [comment]
As discussed with Robert on Slack, @HardeepAsrani ,

**having both of them would make sense**. We are not the only ones using this pattern (Kadence & Stackable are doing the same), and coming from Elementor - for me as an user that's expected that when switching views (Desktop -> Tablet -> Mobile), some features will be device dependent, **which is visible in the Sidebar UI.**

**Comment by HardeepAsrani** [comment]
Thank you @mghenciu for the feedback!

Then we can keep it like this @Soare-Robert-Daniel, just make it work properly.

**Comment by irinelenache** [comment]
@Soare-Robert-Daniel Checked again this PR and everything works fine on my end 👍

**Review by HardeepAsrani — CHANGES_REQUESTED** [review]
- We can reuse the align attribute instead of a new one and also provide backward compatibility for the users.

**Pull request merged**
