### PR TITLE
Add support for taxonomies in Dynamic Content

### LINKED ISSUE #1559: Dynamic values: Post Terms is not working for custom taxonomies
### Description

Otter Pro allows us to show the Post Terms in the posts using dynamic values features. But it's not working for custom taxonomies. User created a custom taxonomy with CPT UI Plugin and when they try to show the output using post terms tag, it doesn't show anything. Other options are working fine except this one.

### Step-by-step reproduction instructions

1. Create a custom taxonomy  using CPT UI Plugin
2. Try to show it under a custom post type or a default post type using dynamic value feature of Otter
3. check the output

### Screenshots, screen recording, code snippet or Help Scout ticket

HS Ticket >> https://secure.helpscout.net/conversation/2183329666/361728?folderId=212385

### Environment info

 Admin area URL: https://abacksilver.s1-tastewp.com/wp-admin   Username: poonam   Password: rewVRz8xYnw 

### Is the issue you are reporting a regression

No

### PR DESCRIPTION
**Pull request by Soare-Robert-Daniel**
Closes #1559 .

### Summary

This feature will show taxonomies that are neither a tag nor a category, usually from 3rd-party plugins.

### Screenshots 

https://github.com/Codeinwp/otter-blocks/assets/17597852/0d2e85cb-df44-4774-a9ba-d525c2a7d77a

----

### Test instructions

1. Create some custom taxonomy. In the video I used this plugin: https://wordpress.org/plugins/custom-post-type-ui/
2. Attack the create taxonomy to the Post.
3. Insert a dynamic content tag for Post Term
4. Select Taxonomy and see the result.

ℹ️ Dynamic content is quite wonky in the preview (it can be seen in the video). So better publish the page to see the results.

---- 

### Checklist before the final review

- [x] Visual elements are not affected by independent changes.
- [x] It is at least compatible with the [minimum WordPress version](https://wordpress.org/plugins/otter-blocks/).
- [x] It loads additional script in frontend only if it is required.
- [x] Does not impact the [Core Web Vitals](https://web.dev/vitals/).
- [x] In case of deprecation, old blocks are safely migrated.
- [x] It is usable in Widgets and FSE.
- [x] Copy/Paste is working if the attributes are modified.

### CODE REVIEW

**Review by HardeepAsrani — CHANGES_REQUESTED** [review]
You have the wrong implementation here. Taxonomies are the classifying of objects. Category and Tags are a taxonomy, so in your current implementation, it will just list all the Custom Taxonomies and their terms. We want to add a field that allows user to name the key of their custom taxonomy and just show the terms of that in the frontend, instead of all the taxonomies and their terms.

Let me know if it makes sense.

Also, can you fix the small visual issue when using the Popup editor with Label/Select not appearing nicely:

Screenshot 2023-05-15 at 6 51 35 PM

**Comment by Soare-Robert-Daniel** [comment]
@HardeepAsrani, this is the following look for adding a taxonomy slug:

**Comment by Soare-Robert-Daniel** [comment]
@HardeepAsrani, one of the problems with my implementation is that API Endpoint does not support extra values.

https://github.com/Codeinwp/otter-blocks/blob/2ba61681f9ddc24ce2923b9b258f0f38e328a776/src/blocks/plugins/dynamic-content/value/fields.js#L78

I need the `taxonomy` to be sent to get the correct result in Editor.

https://github.com/Codeinwp/otter-blocks/blob/2ba61681f9ddc24ce2923b9b258f0f38e328a776/plugins/otter-pro/inc/plugins/class-dynamic-content.php#L177-L182

For Frontend is working fine.

**Comment by HardeepAsrani** [comment]
As we discussed on Slack, just noting here record (in case we ever come back to this) that the endpoint accepts additional attributes too so you can pass more than just context and type.

**Comment by Soare-Robert-Daniel** [comment]
@HardeepAsrani, I made the changes as shown in the video. (I updated it to the one from the description)

The feature works nicely.

**Review by HardeepAsrani — APPROVED** [review]

**Comment by irinelenache** [comment]
@Soare-Robert-Daniel Tested and the enhancement works as expected, thank you 🚀

**Pull request merged**
