### PR TITLE
Development

### PR DESCRIPTION
**Pull request by HardeepAsrani**
### Summary

- Add Dynamic Image Module
- Load CSS inline if possible to reduce page load time
- Fix Dynamic Content not working in Query Loop
- Countdown Block Improvements
- Add notice in the Custom CSS editor when CSS has errors that can break the page
- Add Logged-in user meta condition to Block Conditions module
- Add AggregateRating to schema.org of Review Block
- Fix the Sticky feature not working
- Fix CSS inheritance in the editor
- Fix default margin not working in Icon block
- Fix Pro users seeing upsell message
- Fix camelCase CSS variables
- Fix Review Block only accepting absolute numbers
- Remove Height automatic change on Circle Counter
- Add Block Previews
- Bump minimum compatibility to 5.8

### Screenshots 

----

### Test instructions

---- 

### Checklist before the final review

- [x] Visual elements are not affected by independent changes.
- [x] It is at least compatible with the [minimum WordPress version](https://wordpress.org/plugins/otter-blocks/).
- [x] It loads additional script in frontend only if it is required.
- [x] Does not impact the [Core Web Vitals](https://web.dev/vitals/).
- [x] In case of deprecation, old blocks are safely migrated.
- [x] It is usable in Widgets and FSE.

### CODE REVIEW

**Comment by HardeepAsrani** [comment]
When you are back @irinelenache, these all the issues are fixed: https://github.com/Codeinwp/otter-blocks/milestone/14

**Comment by irinelenache** [comment]
@HardeepAsrani 

- [ ] I imported **NFT starter site** and switched to this version of Otter, and there are some changes in the sections width
before update: 1. https://vertis.d.pr/Po09uB 2. https://vertis.d.pr/lwWHCx 3. https://vertis.d.pr/CAREDW 4. https://vertis.d.pr/GaJCGx 5. https://vertis.d.pr/rg72Bl 6. https://vertis.d.pr/RSwhbG
after update: 1. https://vertis.d.pr/5qqujx 2. https://vertis.d.pr/OawL33 3. https://vertis.d.pr/URtlaQ 4. https://vertis.d.pr/DFDIrI 5. https://vertis.d.pr/jz12Na 6. https://vertis.d.pr/RWYriv
After **Regenerating styles** in otter settings, the style will look how they should, but users should be informed about this

Besides that, didn't manage to find any problem 🚀

**Comment by HardeepAsrani** [comment]
Thanks @irinelenache, I know why this is happening.

**Comment by HardeepAsrani** [comment]
@irinelenache I've also changed the render filter for Dynamic Content & Images, so can you check that again to ensure it works as expected in Editor, Widgets & FSE. Let me know if you see any changes than before or any errors in debugging logs.

I found nothing from my own testing so hoping it stays the same. 😄

**Pull request merged**
