### PR TITLE
OtterTools Controls Improvement

### LINKED ISSUE #1333: Otter icon on the toolbar is too intrusive
### Description:

Besides bringing value to our users, I think we should do our best to don't create trouble. Personally, I find the Otter icon on the toolbar by default, not a good practice looking at the features that are listed there.

Export JSON - I think this should not even be enabled by default, how often and by what % of users is being used to justify the space?
Copy/ Paste Styles? - I think some users would use it heavily, others not

While Export, as I mentioned probably, can be off by default, the copy-paste styles I think it can go into the extended toolbar menu, vs on the main toolbar. As mentioned on the Form block review, the settings should be ideally ordered by usage.

### Alternatives:

Do nothing.

@HardeepAsrani curious about your thoughts.

### PR DESCRIPTION
**Pull request by Soare-Robert-Daniel**
Closes #1333.

### Summary

Improvements:
- change the Icon when used with other plugins.

### Screenshots 

On Core and Otter blocks, the Otter icon will be displayed. For third-party, another one will be used:
image

----

### Test instructions

Please make sure that the shortcuts are displayed and that they work.
⚠️ For Windows, you will need a machine for it. Browserstack does not seem to work well.

---- 

### Checklist before the final review

- [ ] Visual elements are not affected by independent changes.
- [ ] It is at least compatible with the [minimum WordPress version](https://wordpress.org/plugins/otter-blocks/).
- [ ] It loads additional script in frontend only if it is required.
- [ ] Does not impact the [Core Web Vitals](https://web.dev/vitals/).
- [ ] In case of deprecation, old blocks are safely migrated.
- [ ] It is usable in Widgets and FSE.
- [ ] Copy/Paste is working if the attributes are modified.

### CODE REVIEW

**Comment by HardeepAsrani** [comment]
@mghenciu @JohnPixle @ineagu Do you think this can be a good idea? To not show Otter icon but this tools icon in every block (including Otter) and have the "Powered by Otter" thing in the Popover instead of Feedback link.

**Comment by JohnPixle** [comment]
I am not 100% sure about this tbh. The tool icon looks generic and can be considered as part of the core. I am not sure it is a good idea as I would personally prefer to have a clear idea on the otter-specific functionality. Although the tool icon looks good and blends well in the UI, I think it might cause more confusion.

I understand that the "powered by Otter text will help somehow.

Open to hear what others have to say. Thanks for the update!

**Comment by ineagu** [comment]
I am not sure if this helps, what I think we can do and be enough si the 1 & 2 below : 

1. Make sure the users can move/disable it from the settings page if they want.

2. Clean & Optimize 

a) The "Help us improve" is out of place there in the dropdown menu, the user is working, let's not bother them.
b) Can we move the Otter icon towards the end? before the last 2 dropdowns?
c) Can we display the keyword shortcuts? especially for copy paste and export?  https://vertis.d.pr/i/ujsStI

**Comment by mghenciu** [comment]
I agree with the suggestions from Ionut, and I think the overall idea would be to **analyse how often those options would actually be used (and based on that decide if it's worth a section in the Toolbar or not).**

Based on this assumptions:
- Copy Paste could be the option used most often
- more experienced users would prefer to use a Keyboard Shortcut for Copy Paste style, so they won't use a the Toolbar
- beginner/casual users would maybe use the Otter Toolbar Icon
- Export JSON is definitely not used very often, so it may not be needed to have it in the Toolbar
- Transform to Sticky would be rarely used

___
Alternatively, we can **remove the Icon from the Toolbar**, and move the Otter Settings under the options button, but have it in a separate Otter Settings, like this:
image

**Comment by HardeepAsrani** [comment]
> Alternatively, we can remove the Icon from the Toolbar, and move the Otter Settings under the options button, but have it in a separate Otter Settings, like this:

Can you check if we can possibly do this? @Soare-Robert-Daniel

**Comment by ineagu** [comment]
definitively, we would want to see how and if people are using those things.

**Comment by Soare-Robert-Daniel** [comment]
After some prototyping, here are some observations
- We can have an Otter Menu in the Options (three dots), but we don't have a __**working**__ option to control the location for a good separation (result below). When trying to make the feel of `group section`, I added some little hacks. The result still doesn't look too good, but we don't too many tools.
- The options are starting to get big. Almost the size of the page in a 16-inch mac display. I was thinking about adding a dropdown for the menu (to be a two clicks action) to save space.

Extending the Options has basic functionality without many customization options or how to make a better grouping.

The only component that we can use is this one https://github.com/WordPress/gutenberg/blob/HEAD/packages/block-editor/src/components/block-settings-menu-controls/README.md 

The component has an option for location, but it is unusable.

image

image

The separate Otter icon might look a little intrusive, but still has fewer downsides and more flexibility.

@mghenciu at the beginning, I tried with @HardeepAsrani to find some free keys combination and failed to find them. Most easy key combinations are bound to browsers.  I think we try to find a more odd combination but not sure if it will be accessible on usage (like Opt/Alt + Shift + B).

**Comment by ineagu** [comment]
Why not use the same keys elementor is using? Users migrating from it would know them already?Sent from my iPhoneOn Dec 5, 2022, at 11:31, Soare Robert Daniel ***@***.***> wrote:﻿
After some prototyping, here are some observations

We can have an Otter Menu in the Options (three dots), but we don't have a working option to control the location for a good separation (result below). When trying to make the feel of group section, I added some little hacks. The result still doesn't look too good, but we don't too many tools.
The options are starting to get big. Almost the size of the page in a 16-inch mac display. I was thinking about adding a dropdown for the menu (to be a two clicks action) to save space.

Extending the Options has basic functionality without many customization options or how to make a better grouping.
The only component that we can use is this one https://github.com/WordPress/gutenberg/blob/HEAD/packages/block-editor/src/components/block-settings-menu-controls/README.md
The component has an option for location, but it is unusable.


The separate Otter icon might look a little intrusive, but still has fewer downsides and more flexibility.
@mghenciu at the beginning, I tried with @HardeepAsrani to find some free keys combination and failed to find them. Most easy key combinations are bound to browsers.  I think we try to find a more odd combination but not sure if it will be accessible on usage (like Opt/Alt + Shift + B).

**Comment by Soare-Robert-Daniel** [comment]
> Why not use the same keys elementor is using? Users migrating from it would know them already?

We do not have the luxury of Elementor. Copy Style is for us is a separate feature and not integrated like in full-editors like Elementor or Stackable. For pasting style, the `Ctrl/Cmd + shift + V` might work, but not sure how it behaves on window 
Windows, where this is the command for pasting not formatted text.

This observation is based on using Gutenberg's own API for shortcuts (which I tested at the beginning). We can force the override in some hacky way but not sure if we break some workflow (or other plugins). Elementor might enforce that binding for them in their __own editor__, but in Gutenberg, we have to play nice with others. 

I can implement a prototype to see how it works and make a better opinion.

**Comment by Soare-Robert-Daniel** [comment]
image

Those combinations seams to work on Apple. The reliability is not great, you need multiple tries for it to trigger.

**Comment by Soare-Robert-Daniel** [comment]
On Firefox, `Cmd+Alt+k` is reserved by the browser which opens the Console tab for Dev Tools, and the action is canceled. No conflict in Safari. On Chrome, `Cmd+Alt+k` open the Dev Tools, but the action is still applied.

**Comment by HardeepAsrani** [comment]
To be fair this looks even worse: https://github.com/Codeinwp/otter-blocks/pull/1350#issuecomment-1337102751 - the list is too big and more intrusive.

I suggest we stop here and only take action when we have something specific in mind instead of a knee-jerk reaction.

Thank you @Soare-Robert-Daniel for helping with the quick prototype to see how things will feel.

**Comment by ineagu** [comment]
I think we can keep this as it was before, I would just remove removing the feedback button and add the shortcuts.

**Comment by HardeepAsrani** [comment]
Closing this in favor of https://github.com/Codeinwp/otter-blocks/pull/1403

**Pull request closed without merging**
