### PR TITLE
Pricing Section

### PR DESCRIPTION
**Pull request by HardeepAsrani**
This PR adds Pricing Section as a variation which should be available in the Inserter. Closes https://github.com/Codeinwp/otter-blocks/issues/699

### CODE REVIEW

**Comment by HardeepAsrani** [comment]
When you get time, can you take a look here? Thank you!

**Comment by HardeepAsrani** [comment]
@irinelenache When you get time, can you take a look here? Thank you!

**Comment by irinelenache** [comment]
@HardeepAsrani Tested and found a couple things:

- [ ] The heading alignment doesn't work in editor (in frontend is fine) https://vertis.d.pr/2heShU
- [ ] In frontend, the pricing section looks a bit different than what @mghenciu attached. 
I added some **line height** for the price and a **spacer** between the button and the separator. You can see the difference between the middle column and the other two:

image

Let me know your thoughts on this 👍

**Comment by HardeepAsrani** [comment]
@irinelenache 

>  The heading alignment doesn't work in editor (in frontend is fine) https://vertis.d.pr/2heShU

It doesn't work as it's set to Span which doesn't suit it well.

>  I added some line height for the price and a spacer between the button and the separator. You can see the difference between the middle column and the other two:

Thanks, I'll check that.

**Pull request merged**
