### PR TITLE
Various Theme-compat fixes

### LINKED ISSUE #1277: Otter x Most Popular themes
### Description:

[I made a page in Notion with findings while testing Otter with most popular Themes.](https://www.notion.so/themeisle/Testing-Neve-Otter-with-other-themes-f90a99004c7f4aee9f90ed85753363f0)
Fortunately **didn't found any major issues**, just a few that we need to look into, in the near future:

- [x] In OceanWP, in Frontend **all the fonts are converted to Serif**
- [ ] there looks to be an issue when importing content (via Wordpress importer tool), with the **Icon Block when using the Themeisle icons**. A error in console appears and those blocks need to be recovered. It's happening on multiple themes (2021, Blocksy). Import this XMLs and open the pages in edit, to see the error:
 
[nonprofit.WordPress.2022-10-19 (1).xml.zip](https://github.com/Codeinwp/otter-blocks/files/9822008/nonprofit.WordPress.2022-10-19.1.xml.zip)

[blogger.WordPress.2022-10-19.xml.zip](https://github.com/Codeinwp/otter-blocks/files/9822007/blogger.WordPress.2022-10-19.xml.zip)
___

- [x] Otter options panel & the Sync with Global toggle inconsistencies in Astra

___
For the rest of the issues, I think we can leave them for later and re-evaluate this when we also have TPC standalone and see how that works with different themes. 
 

### How to reproduce:

1. 
2.
3.

### Reference:

Screenshots & videos added in Notion

### Technical info
* WordPress version: 6.0.2
* Plugin version: 2.1

### PR DESCRIPTION
**Pull request by HardeepAsrani**
Closes #1277.

### Summary

- Leaflet Map Underline in OceanWP
- Set Section Separator to Clip after width of the Section
- Fix Tabs not working properly in Blocksy
- Fix Button Wrap
- Fix Section Columns breaking after duplicating until there are more than 6 columns
- Fixing Icon List alignment in Astra

@mghenciu All the issues should be fixed or you will find a comment noting down why it can't be changed here: https://www.notion.so/themeisle/Testing-Neve-Otter-with-other-themes-f90a99004c7f4aee9f90ed85753363f0

Let me know!
----

### Test instructions

- Make sure all the issues mentioned here are fixed or addressed: https://www.notion.so/themeisle/Testing-Neve-Otter-with-other-themes-f90a99004c7f4aee9f90ed85753363f0
---- 

### Checklist before the final review

- [x] Visual elements are not affected by independent changes.
- [x] It is at least compatible with the [minimum WordPress version](https://wordpress.org/plugins/otter-blocks/).
- [x] It loads additional script in frontend only if it is required.
- [x] Does not impact the [Core Web Vitals](https://web.dev/vitals/).
- [x] In case of deprecation, old blocks are safely migrated.
- [x] It is usable in Widgets and FSE.
- [x] Copy/Paste is working if the attributes are modified.

### CODE REVIEW

**Comment by mghenciu** [comment]
@HardeepAsrani , do you think it's 'safe' and not an overpromise to include [something like this](https://www.notion.so/themeisle/Testing-Neve-Otter-with-other-themes-f90a99004c7f4aee9f90ed85753363f0#ace4bcc2bd1a4aa3865cac99930e0233) on the Otter WP Page?

Basically a line with: **Can I use Otter with any Wordpress theme?** above the USEFUL RESOURCES section;
and say something about this.

**Comment by HardeepAsrani** [comment]
@mghenciu Yes, in fact I think we should add 5-6 FAQ items if someone can work on those, about the docs, if it works with all themes, about patterns and so on.

**Comment by mghenciu** [comment]
@AndreeaCristinaRadacina , for when you have some time:
_maybe you have some insights about what questions are/would be popular about Otter?_ maybe ask this in the support meeting, to get a better idea. We want to create a FAQ question and add a few questions, including this one: _Can I use Otter with any Wordpress theme?_

based on the HelpScout graph, the whole Otter Docs page is popular, but that's include a lot of things :) 
image

**Comment by AndreeaCristinaRadacina** [comment]
@mghenciu yes, I already talked about this.
I will come back with the questions.

**Comment by irinelenache** [comment]
@HardeepAsrani I also checked and the issues are fixed, will move this to **Ready to merge** 🚀

**Comment by mghenciu** [comment]
@HardeepAsrani , here are the FAQ suggested by the Support team (thank you @MarinescuLucia for the help):

- **Is Otter free?**
- **What page builders are compatible with Otter?** (here maybe we can ask what Page Builders are compatible with Otter: short answer - only Gutenberg)
- **Can I use Otter with any WordPress theme?**
- **Where can I get help?** (Link to the support forum and the main documentation)
- **What are the Patterns and how can I use them?**
- **Can I translate the blocks?**

And it's a very good starting point 🚀

**Comment by HardeepAsrani** [comment]
@MarinescuLucia can you help with the answers too, with links from Docs where needed? Also, given the theme isn't i18n ready, we can remove the last point. You can also create a PR against readme file, if this is something you're interested in doing and someone can guide you if you need any help.

**Pull request merged**
