### PR TITLE
Sticky Banner Mode

### PR DESCRIPTION
**Pull request by Soare-Robert-Daniel**
Closes #.

### Summary

Make the sticky block act like a banner by adding extra space at the top of the page.

New options:

- `o-sticky-header-space`: activate the header space
- `o-sticky-header-gap-{value}`: set gap space. By default, it uses the block `height`, but is not always reliable. Use this to make adjustments. Example: `o-sticky-banner-gap-50px`, adds a margin of 50px to the body.

### Screenshots 

image

----

### Test instructions

---- 

### Checklist before the final review

- [ ] Visual elements are not affected by independent changes.
- [ ] It is at least compatible with the [minimum WordPress version](https://wordpress.org/plugins/otter-blocks/).
- [ ] It loads additional script in frontend only if it is required.
- [ ] Does not impact the [Core Web Vitals](https://web.dev/vitals/).
- [ ] In case of deprecation, old blocks are safely migrated.
- [ ] It is usable in Widgets and FSE.
- [ ] Copy/Paste is working if the attributes are modified.

### CODE REVIEW

**Comment by HardeepAsrani** [comment]
@Soare-Robert-Daniel All seems fine, but the term "Banner mode" conveys no meaning. It can be renamed to something more descriptive.

**Comment by Soare-Robert-Daniel** [comment]
> @Soare-Robert-Daniel All seems fine, but the term "Banner mode" conveys no meaning. It can be renamed to something more descriptive.

Any suggestions? I don't know if this has a specific name like Evergreen Countdown.

**Comment by HardeepAsrani** [comment]
@Soare-Robert-Daniel Something like "Avoid Overflowing over Header" or something. I don't know if it has a technical term, but even having the Banner Mode is fine as long as you can put in some description to tell user what it does.

**Comment by HardeepAsrani** [comment]
Looks good to me @Soare-Robert-Daniel, tested and works fine. You can put it for QA.

**Comment by irinelenache** [comment]
@Soare-Robert-Daniel Tested and found a single problem:

- [ ] If i use the option to close the sticky by clicking a button, the header will still have the empty space that was added. Here is a video with the behaviour https://vertis.d.pr/v/nIaQ3v

**Comment by Soare-Robert-Daniel** [comment]
@irinelenache, you test this. Make sure to make a new block, I changed some names to be more appropriate with the feature name.

**Comment by irinelenache** [comment]
@Soare-Robert-Daniel Tested again and now everything works fine, thank you 🚀

**Comment by HardeepAsrani** [comment]
Thanks @irinelenache, can you remove the console.log and merge? @Soare-Robert-Daniel

**Pull request merged**
