### PR TITLE
Advance Heading enhancement

### LINKED ISSUE #823: Advanced Heading - enhancements
- [ ] Transition the Typography settings form what we have no, to Core wp 5.9.
Currently in Advanced Heading Block for example, we have a number of typography settings that can be replaced with Core Controls. If this is not possible yet, we can at least add Relative units for the Typography controls (font-size, line-height).
image

### This is the core Heading Block where it has all the typographic options inside a panel.
image

___

### PR DESCRIPTION
**Pull request by Soare-Robert-Daniel**
Closes #823 .

### Summary

A new look and responsive design.

### Screenshots 

----

### Test instructions

Before using this version, make some blocks with the current stable version for a compatibility test (you can also use the Query from below).

Two things are important:
 - responsive attributes like along, padding, and margin.
 - the block does not break when updated, and the style does not change for old versions.

#### Query
```javascript
new QueryQA().select('blocks').where({ names: ['old-adv-heading'] }).run()
```

---- 

### Checklist before the final review

- [ ] Visual elements are not affected by independent changes.
- [ ] It is at least compatible with the [minimum WordPress version](https://wordpress.org/plugins/otter-blocks/).
- [ ] It loads additional script in frontend only if it is required.
- [ ] Does not impact the [Core Web Vitals](https://web.dev/vitals/).
- [ ] In case of deprecation, old blocks are safely migrated.
- [ ] It is usable in Widgets and FSE.

### CODE REVIEW

**Comment by Soare-Robert-Daniel** [comment]
@mghenciu, this functionality for adding a link is built-in Core. Like in Core Heading, you don't have access to it from Inspector. We should remove this since Gutenberg manages it as a `format` and not a block.

image

**Comment by mghenciu** [comment]
Nice job, overall Robert 🥇 

Some things I noticed while testing:

- [ ] when changing the Headings Tag from the Toolbar, there is a weird effect - which disappears after hovering on those elements: 

https://user-images.githubusercontent.com/52494172/200802016-a650fb10-ac6c-44c7-8df3-c15d5e0ac074.mov

___

- [ ] In the current Adv Heading, when adding a new one, it will have the **Bottom margin**. With the Dev build, the bottom spacing is added in the Padding and not margin anymore. Not sure if this is intended or what the reason behind it.
___
- [ ] When adding a Adv Heading with the Dev Build, by default the **Selected Tab** is Style. This is ok, assuming that people will want to edit the Text size most often. My question is if it's possible to enclose the Colors in a Panel (right now those are open), and make the Typography Panel be open by default.
Screenshot 2022-11-09 at 12 12 13

- [ ] As mentioned above, by default the Style Tab is selected, to mitigate the idea that users would want to change the Heading alignment easily, could we add an Alignment option in the Toolbar? (core heading has this)
___
- [ ] There is a **U** unit under the Line height setting. Not sure what is that, as it doesn't sounds very common: 
Screenshot 2022-11-09 at 12 17 27

___
Is it possible to have by Default just some Controls for the **Typography**, and users be able to add more (attached)?
But I guess not, since we are using a Custom Typography Component 
image
image

**Comment by Soare-Robert-Daniel** [comment]
> * [ ]  when changing the Headings Tag from the Toolbar, there is a weird effect - which disappears after hovering on those elements:

The core component doesn't like the SVG to much.

> * [ ]  There is a **U** unit under the Line height setting. Not sure what is that, as it doesn't sounds very common:

U from `unitless`. The `line-height` can be a unitless value or a px. 

Did not find an equivalent in Core, so it is an original part. If you a better suggestion. please share 🙏

**Comment by mghenciu** [comment]
> U from unitless. The line-height can be a unitless value or a px.

I couldn't find something in Core, probably will be added in future.
can it be Unitless, EM, PX, %?

**We can use the same Symbol mentioned** [here](https://github.com/Codeinwp/neve/pull/3410#issuecomment-1075269476) (with a label on hover, saying unitless). We use the same approach in Neve.

Hope it makes sense.

**Comment by irinelenache** [comment]
@Soare-Robert-Daniel Good job 🚀 Tested the enhancements and found a single problem:

- [ ] The background, link and link hover colors were not pasted from an advanced heading to another https://vertis.d.pr/i/VOMEsb

Besides this and the weird hovering effect mentioned by Mihai, everything works fine for me 👍

**Comment by Soare-Robert-Daniel** [comment]
> * [ ]  The background, link and link hover colors were not pasted from an advanced heading to another https://vertis.d.pr/i/VOMEsb

A small clarification: the colors are pasted correctly, but things like `hightlight` and `link` are formatting elements. We do not copy format elements via Copy/Paste. 

Example: 

```html
<!-- wp:themeisle-blocks/advanced-heading {"id":"wp-block-themeisle-blocks-advanced-heading-f3e73343","highlightColor":"var(\u002d\u002dnv-c-2)","highlightBackground":"var(\u002d\u002dnv-text-color)"} -->
<h2 id="wp-block-themeisle-blocks-advanced-heading-f3e73343" class="wp-block-themeisle-blocks-advanced-heading wp-block-themeisle-blocks-advanced-heading-f3e73343">H1</h2>
<!-- /wp:themeisle-blocks/advanced-heading -->

<!-- wp:themeisle-blocks/advanced-heading {"id":"wp-block-themeisle-blocks-advanced-heading-34d1c8c1","highlightColor":"var(\u002d\u002dnv-c-2)","highlightBackground":"var(\u002d\u002dnv-text-color)"} -->
<h2 id="wp-block-themeisle-blocks-advanced-heading-34d1c8c1" class="wp-block-themeisle-blocks-advanced-heading wp-block-themeisle-blocks-advanced-heading-34d1c8c1"><span class="highlight">H2</span></h2>
<!-- /wp:themeisle-blocks/advanced-heading -->

```

In the second block, you can observe this `<span class="highlight">H2</span>` that adds the actual highlight to the selected text.

Copy/Paste only make the things like `highlightColor":"var(\u002d\u002dnv-c-2)","highlightBackground":"var(\u002d\u002dnv-text-color)"` to be the same on both blocks.

**Comment by Soare-Robert-Daniel** [comment]
@mghenciu, I found a way to replace the SVG. This is the result:

image

CSS Code:

https://github.com/Codeinwp/otter-blocks/blob/c88706a4c52be8a895ba7ac17c4a59590ec823ea/src/blocks/blocks/advanced-heading/editor.scss#L16-L22

**Pull request merged**
