### PR TITLE
Improve Heading typo component

### LINKED ISSUE #1882: Update the Typography controls in the Otter Blocks
### What problem does this address?

As mentioned [here](https://github.com/Codeinwp/otter-blocks/pull/1870#issuecomment-1733312862), in order to be more consistent and to not occupy too much space in the sidebar - **we can look into updating our existing components to the new WP UIX patterns.**

In this case it's about typography controls, but it could apply to other types of controls.
Example from Core vs Otter Typography, as seen - the panels could occupy much less space: 
Screenshot 2023-09-25 at 13 29 09

### What is your proposed solution?

_No response_

### Will this feature require documentation? (Optional)

No.

### PR DESCRIPTION
**Pull request by Soare-Robert-Daniel**
Closes #1882

### Summary

Moved the old typo component to the new one.

Development notes: It was not a smooth experience, but I was glad to find a new trick to tackle the responsive option.

### Screenshots 

Before

image

After

image

----

### Test instructions

⚠️ Before using this build, make some Heading blocks with the current version and customize them with Typography.

Switching to the PR build and checking if the options are the same as before and if they are working like before.

---- 

### Checklist before the final review

- [x] Included E2E or unit tests for the changes in this PR.
- [x] Visual elements are not affected by independent changes.
- [x] It is at least compatible with the [minimum WordPress version](https://wordpress.org/plugins/otter-blocks/).
- [x] It loads additional script in frontend only if it is required.
- [x] Does not impact the [Core Web Vitals](https://web.dev/vitals/).
- [x] In case of deprecation, old blocks are safely migrated.
- [x] It is usable in Widgets and FSE.
- [x] Copy/Paste is working if the attributes are modified.
- [x] PR is following [the best practices]()

### CODE REVIEW

**Review by HardeepAsrani — APPROVED** [review]
Looks good, for QA we should make sure that each control is tested with how it works with existing patterns.

**Comment by irinelenache** [comment]
@Soare-Robert-Daniel Tested and everything's fine regarding the PR, found a single issue that was also happening before, maybe we can fix it here:

- [ ] If i use the unitless option for line height, it will work fine in editor for values lower or equal to 3 (in frontend is fine). Here is a video with the behaviour https://vertis.d.pr/v/SvTUi1

**Comment by Soare-Robert-Daniel** [comment]
@irinelenache, thanks for the catch. I think i missed updating that editor condition.

Here is a little context on that thing. Before the new components, the heading used a slider in which after you crossed the value 3 it will use pixels as units -- on the idea that you do not need more than 3, which translates to 300%.

Now with new components, we can choose the unit and not be limited by this. But, we still need to maintain backward compatibility, thus some conditions are creeping around. 

Here is a video

https://github.com/Codeinwp/otter-blocks/assets/17597852/3bd8bd06-2261-4e54-8b99-3618c0f24715

Notice how it behaves when you remove the `"` around the number -- this is the old value type used at the start of plugin.

**Comment by irinelenache** [comment]
@Soare-Robert-Daniel Tested again and everything's fine now 👍

**Pull request merged**
