### PR TITLE
Add Global Defaults option for Heading Block & CSS improvments

### LINKED ISSUE #1490: Add Bottom Margin option for the Advanced Heading
### Description:

Right now the block doesn't have any Global Options, and to reset that 25px bottom - they would have to this each time for the Advanced Headings blocks.
Screenshot 2023-02-07 at 17 32 00
Screenshot 2023-02-07 at 17 32 25

### PR DESCRIPTION
**Pull request by Soare-Robert-Daniel**
Closes #1490

### Summary

🔧 Added Global Defaults controls for Advanced Heading Block.
🖼️ Improved the control alignment. -- This was very time consuming, and getting the selector right was not so obvious when core components have dynamic class generation.

### Screenshots 

https://github.com/Codeinwp/otter-blocks/assets/17597852/68f2e021-093b-4464-ac67-e9fbb32d81b7

#### Control Alignment Before

image

#### Control Alignment After

image
----

### Test instructions

---- 

### Checklist before the final review

- [ ] Included E2E or unit tests for the changes in this PR.
- [x] Visual elements are not affected by independent changes.
- [x] It is at least compatible with the [minimum WordPress version](https://wordpress.org/plugins/otter-blocks/).
- [x] It loads additional script in frontend only if it is required.
- [x] Does not impact the [Core Web Vitals](https://web.dev/vitals/).
- [x] In case of deprecation, old blocks are safely migrated.
- [x] It is usable in Widgets and FSE.
- [x] Copy/Paste is working if the attributes are modified.
- [x] PR is following [the best practices]()

### CODE REVIEW

**Review by HardeepAsrani — APPROVED** [review]
In terms of code, LGTM. You can get design team's feedback to confirm the functionality is working as they expect it to work.

**Comment by Soare-Robert-Daniel** [comment]
@mghenciu, if you can help with a review 🙏

**Comment by mghenciu** [comment]
> @mghenciu, if you can help with a review 🙏

Looks good, Robert - nice job 🚀 

___

Just a general question. It's still impossible to use the Core controls for Line height, letter spacing, etc? like below
This could help us save a lot of space in the sidebar

image

**Comment by Soare-Robert-Daniel** [comment]
@mghenciu, yes, we can upgrade the Typography section with ones like in Buttons  image

----

ℹ️  I recommend putting this as a separate issue, which should include more enhancements.

**Comment by rodica-andronache** [comment]
@Soare-Robert-Daniel when I change the margin option, the other options ( text color, font family etc ) get reset to the initial value https://www.loom.com/share/9f04181ee4c743d195d81d18d3637011?sid=57dd7e1a-1cd9-4779-8301-90c81ee1ae5a

**Comment by rodica-andronache** [comment]
@Soare-Robert-Daniel the first issue is fixed. 

- [ ] I've noticed another issue, when you click on Shadow > Enable Text Shadow you get "The editor has encountered an unexpected error." https://vertis.d.pr/v/GwfXzr

You can test it here:
```
https://thoughtful-toad-u3k3a.vertisite.cloud/wp-admin
user: admin
pass: o7QD1Ch)muEbHiRQ^bn2sH@F
```

- [ ] the line-height appears differently in backend https://vertis.d.pr/i/bSUOXH and frontend https://vertis.d.pr/i/rhETtw

**Comment by Soare-Robert-Daniel** [comment]
This will be on hold until #1882 is merged since the new typo comp must also be in the Global Default.

**Comment by rodica-andronache** [comment]
@Soare-Robert-Daniel thank you for the fixes, everything is working well now 👍

**Pull request merged**
