### PR TITLE
Development

### PR DESCRIPTION
**Pull request by ineagu**
- https://github.com/Codeinwp/otter-internals/issues/226
- https://github.com/Codeinwp/otter-internals/issues/225
- https://github.com/Codeinwp/otter-internals/issues/220
- https://github.com/Codeinwp/otter-internals/issues/218
- https://github.com/Codeinwp/otter-internals/issues/213
- https://github.com/Codeinwp/otter-internals/issues/208
- https://github.com/Codeinwp/otter-internals/issues/207
- https://github.com/Codeinwp/otter-internals/issues/198
- https://github.com/Codeinwp/otter-internals/issues/197
- https://github.com/Codeinwp/otter-internals/issues/196
- https://github.com/Codeinwp/otter-internals/issues/179
- https://github.com/Codeinwp/otter-internals/issues/178
- https://github.com/Codeinwp/otter-internals/issues/177
- https://github.com/Codeinwp/otter-internals/issues/175
- https://github.com/Codeinwp/otter-internals/issues/173
- https://github.com/Codeinwp/otter-internals/issues/185
- https://github.com/Codeinwp/otter-internals/issues/168
- https://github.com/Codeinwp/otter-internals/issues/190
- https://github.com/Codeinwp/otter-internals/issues/191
- https://github.com/Codeinwp/otter-internals/issues/194
- https://github.com/Codeinwp/otter-internals/issues/200
- https://github.com/Codeinwp/otter-internals/issues/204
- https://github.com/Codeinwp/otter-internals/issues/201
- https://github.com/Codeinwp/otter-internals/issues/142
- https://github.com/Codeinwp/otter-internals/issues/130
- https://github.com/Codeinwp/otter-internals/issues/128
- https://github.com/Codeinwp/otter-internals/issues/121
- https://github.com/Codeinwp/otter-internals/issues/120
- https://github.com/Codeinwp/otter-internals/issues/199
- https://github.com/Codeinwp/otter-internals/issues/217
- https://github.com/Codeinwp/otter-internals/issues/215
- https://github.com/Codeinwp/otter-internals/issues/214
- https://github.com/Codeinwp/otter-internals/issues/210
- https://github.com/Codeinwp/otter-internals/issues/206
- https://github.com/Codeinwp/otter-internals/issues/183
- https://github.com/Codeinwp/otter-internals/issues/176
- https://github.com/Codeinwp/otter-internals/issues/211
- https://github.com/Codeinwp/otter-internals/issues/184
- https://github.com/Codeinwp/otter-internals/issues/186
- https://github.com/Codeinwp/otter-internals/issues/187
- https://github.com/Codeinwp/otter-internals/issues/146
- https://github.com/Codeinwp/otter-internals/issues/117

### CODE REVIEW

**Comment by HardeepAsrani** [comment]
Hey @rodica-andronache,

Can you test Otter finally before the final release? I've listed all the issue that are part of this release in the PR description. If you need any help or any information about anything. feel free to let me know or Robert know. Thank you!

**Comment by rodica-andronache** [comment]
@HardeepAsrani yes, I'm already working on this 👍

**Comment by rodica-andronache** [comment]
@HardeepAsrani @Soare-Robert-Daniel here are some mostly small stuff I saw while testing:

- [ ]  On an instance with Otter ( free ) from this PR + Otter PRO ( the current version from store )  -> Any new block(not just from Otter) I try to add I get this error https://vertis.d.pr/i/ksGU5x
```
https://redeeming-gaur-27bf14.vertisite.cloud/wp-admin/
user: rodica
pass: rodica
```

- [ ] https://vertis.d.pr/i/hyHhaX - If possible, we can change the Twitter icon to X in both places
- [ ] https://vertis.d.pr/i/HgZjdd - pagination in the Posts block is not working, clicking on the pagination buttons doesn't change anything ( but not working in the current version either )
- [ ] https://vertis.d.pr/i/OKH4CK  - for this issue https://github.com/Codeinwp/otter-internals/issues/190, changing the column width doesn’t seam to apply
- [ ] https://vertis.d.pr/i/QpClpr - the OpenAI key field is no longer hiding the key as it does on the current version https://vertis.d.pr/i/Kbbhd4
- [ ] https://neve-test.vertisite.cloud/form/ - if I click on the submit button without adding any content in the fields, there is an error in the console, not sure if important or not https://vertis.d.pr/i/WRBWDC

**Comment by Soare-Robert-Daniel** [comment]
> * [ ]  https://vertis.d.pr/i/QpClpr - the OpenAI key field is no longer hiding the key as it does on the current version https://vertis.d.pr/i/Kbbhd4

This is expected, I switched the workflow to use masked values. When you introduce it, it will be visible, but once saved, on reload, you will see the mask. This behavior is similar to OpenAI Dashboard
image

**Comment by HardeepAsrani** [comment]
@rodica-andronache I've fixed the block conditions issue, thank you for noticing it.

**Comment by Soare-Robert-Daniel** [comment]
> * [ ]  https://vertis.d.pr/i/HgZjdd - pagination in the Posts block is not working, clicking on the pagination buttons doesn't change anything ( but not working in the current version either )

@rodica-andronache  This seems to work fine. Any missing details?

https://github.com/user-attachments/assets/5e024b58-6143-4763-8bbb-4ff3924b3ef9

**Comment by HardeepAsrani** [comment]
@rodica-andronache For the slider issue, are you using slider at 100% width or is it set to some px value? By default it's 100% which seems to work fine for me. If you set it to some higher px width then that takes the precedence.

**Comment by rodica-andronache** [comment]
@Soare-Robert-Daniel https://vertis.d.pr/v/YLVKiH You are right, the pagination is working well when you add the Posts block on a **page**.  I was adding the block on a **post** page. There is not working ( in the current version as well )

**Comment by Soare-Robert-Daniel** [comment]
@rodica-andronache, pagination is fixed now 🔥

**Comment by rodica-andronache** [comment]
@HardeepAsrani this is how I tested the issue with the Slider https://www.loom.com/share/f31aea0aef744721b33ec30f020a20e5?sid=b5b69e32-917b-4981-9144-2e264515253e

By default, when I added the slider it has with:650, so the Column width is not considered. But if I remove that 650px width, it's ok.
Let me know if that's ok or not.

The issue with the pagination works well, now 👍

**Comment by rodica-andronache** [comment]
- [ ] A small thing: Maybe we can change this text to "X" instead of "Twitter". Also the share link is using twitter.com instead of x.com
Annotation on 2024-08-08 at 16-35-49

**Comment by Soare-Robert-Daniel** [comment]
The labels and links have now been updated. It might be a bit weird with just one letter name, but it will be consistent: 

image

**Comment by HardeepAsrani** [comment]
@rodica-andronache That should be fixed now.

**Comment by rodica-andronache** [comment]
@HardeepAsrani it's working well now

**Pull request merged**
