### PR TITLE
New visibility condition based on how much the user spent during lifetime

### PR DESCRIPTION
**Pull request by arinaturcu**
Added a new condition based on how much the user spent.
Uses the WooComerce function `get_total_spent()`.

### CODE REVIEW

**Comment by HardeepAsrani** [comment]
@irinelenache Can you do QA on this? You can add Woo products with some price and use cash on delivery option to have fake spent added to your account. Thanks!

**Comment by irinelenache** [comment]
@arinaturcu Tested but the `Total spent greater than X$` doesn't work, both with/without the order marked as **Completed** 
You can check the issue here:
```
https://consolidateyoke.tastewp.com/2022/03/07/test-total-spent-conditions/
user: irinel
password: 9XxWpYpe7aQ
```

Let me know if i missed anything, thanks 🙏

**Comment by arinaturcu** [comment]
@irinelenache Thank you! :rocket: 
The issue should be fixed now.

**Comment by irinelenache** [comment]
@arinaturcu The issue is fixed now, didn't find any other problem, thank you 🚀

**Pull request merged**
