### PR TITLE
Remove unnecessary dependencies from frontend scripts

### LINKED ISSUE #524: Review JS for frontend
We need to review the JS that we use in the frontend for maximum performance. 

Things that we need to review: 

- [x] Enqueue all JS from frontend in footer (!)
- [x] #531
- [x] Make sure the JS files are minified and loaded if and only if the block that requires them is used in the current page. 
- [x] Make sure to review the JS and it works with async behavior, i.e we don't check DOM before being ready, etc. Test it on slow connections Chrome network throttle features for something like Slow 3G.

### PR DESCRIPTION
**Pull request by Soare-Robert-Daniel**
Fixes #524 

Some editor dependencies were loaded on fronted because of the js function collection.
Also, make simple functions part of the codebase instead of importing them from WP packages.

---- 

#### Description

*(You need to use the Network tab)*
We need to see if our frontend scripts load unwanted files: dom-ready, lodash, wp-editor, and anything with `wp-` should be checked. 

⚠️ Make sure to be on fresh install without additional plugins.

Also, if you think something might not be right or you are unsure about a script, please share the instance.

#### Query

```javascript
new QueryQA().select('blocks').where({ names: ['frontend-script-dependency-check'] }).run()
```

This will contain our blocks that use frontend script, except for Slider and Google Maps -- their configuration can not be exported.

### CODE REVIEW

**Comment by HardeepAsrani** [comment]
@Soare-Robert-Daniel Not sure it's good to have our own copies of Lodash packages. Might be better to use Lodash from node_modules instead with tree-shaking like this:

> import foo from 'lodash/foo';

**Comment by Soare-Robert-Daniel** [comment]
I was worried about the ExtractPlugin that it might consider it an internal dependency and load 'lodash', but it is not the case. 'lodash/omit' is not considered an internal WP deps. Thanks for the suggestion 👍 .

**Comment by Soare-Robert-Daniel** [comment]
@HardeepAsrani, unfortunately, the approach with `loadash/omit` breaks the script. The script is not working anymore if it has `import omit from loadash/omit`. I refactored the code in `slider/index.js` to no longer use omit. But, we need to see if we have some alternative to this.

**Comment by HardeepAsrani** [comment]
Let me take a look. thanks.

**Comment by selul** [comment]
@HardeepAsrani sticky.js is still loaded no matter if is used or not.

**Comment by HardeepAsrani** [comment]
@selul Yes, for that we will require the meta implementation. So first addressing the issues that can be quickly addressed.

**Comment by HardeepAsrani** [comment]
@Soare-Robert-Daniel Can you take care of the same things in Form PR? Don't use any WordPress dependencies in the front-end.

**Comment by irinelenache** [comment]
@HardeepAsrani Tested and here are some findings: 

- [ ] On a page that contains only an accordion, **animation** and **sticky** js files are loaded https://vertis.d.pr/K97P4I
- [ ] I used @Soare-Robert-Daniel's provided query on two tastewp instances with the **Shop** starter site imported, and after checking them with webpagetest.org i saw that the js size is bigger for the updated instance, even if the number of files is smaller
before this PR: https://vertis.d.pr/kJfA80
with this PR: https://vertis.d.pr/OOrSa0

_Note: Didn't test the functionalities of most block yet_

**Comment by HardeepAsrani** [comment]
>  On a page that contains only an accordion, animation and sticky js files are loaded https://vertis.d.pr/K97P4I

That's expected after this PR. We will fix it in an upcoming PR.

>  I used @Soare-Robert-Daniel's provided query on two tastewp instances with the Shop starter site imported, and after checking them with webpagetest.org i saw that the js size is bigger for the updated instance, even if the number of files is smaller

I can see the size reduce. You can try to try it on a blank website without much to know better.

**Comment by irinelenache** [comment]
@HardeepAsrani Checked again and now the js size is smaller 🚀

**Pull request merged**
