### PR TITLE
Add alignment for separetors in Countdown

### LINKED ISSUE #1109: Align Countdown separators to the Numbers and not to the Container - when using the Plan Style
### Description:

Maybe in a boxed layout, it makes sense to align the separators vertically, based on the containers (for example I want to built this):
image
Users should be able to create something like this: 
image

for example in a **Plain Context**, the separators should be aligned to the numbers:
Screenshot 2022-08-10 at 17 16 38

Screenshot 2022-08-10 at 17 29 30

Check Kadence Blocks for reference.
Additionally, **Text Transform options for the Labels would be nice**, for example to have al the labels in Uppercase.

### Alternatives:

 Do nothing

### PR DESCRIPTION
**Pull request by Soare-Robert-Daniel**
Closes #1109 .

### Summary

Add alignment option for separators.

### Screenshots 

image

----

### Test instructions

---- 

### Checklist before the final review

- [ ] Visual elements are not affected by independent changes.
- [ ] It is at least compatible with the [minimum WordPress version](https://wordpress.org/plugins/otter-blocks/).
- [ ] It loads additional script in frontend only if it is required.
- [ ] Does not impact the [Core Web Vitals](https://web.dev/vitals/).
- [ ] In case of deprecation, old blocks are safely migrated.
- [ ] It is usable in Widgets and FSE.

### CODE REVIEW

**Comment by Soare-Robert-Daniel** [comment]
@HardeepAsrani, should we also deprecate the `name` attributes from the component to avoid future problems with WP filters?

**Comment by HardeepAsrani** [comment]
@Soare-Robert-Daniel Maybe in future but we can't afford another deprecation now. 😄

**Comment by irinelenache** [comment]
@Soare-Robert-Daniel Tested and here are my findings:

- [ ] After just updating an instance that contains **Coundown** blocks with this PR, the alignment of the separator breaks
before: https://vertis.d.pr/VpYwKi
after: https://vertis.d.pr/dfQY6s

- [ ] The **default** alignment is different in editor and frontend
editor: https://vertis.d.pr/IfRFcA
frontend: https://vertis.d.pr/dOTRRf

- [ ] Changing the alignment makes a change in the block spacing in editor (no problem in frontend) https://vertis.d.pr/Y368VU

**Comment by Soare-Robert-Daniel** [comment]
@irinelenache the first two problems should be solved now for settings that make the box closer to each other. The third is ok to happen.

**Comment by irinelenache** [comment]
@Soare-Robert-Daniel Checked again and now everything works fine, thank you 🚀

**Comment by HardeepAsrani** [comment]
@mghenciu Here you think it makes sense to add the field for alignment or have one as default?

**Comment by mghenciu** [comment]
> @mghenciu Here you think it makes sense to add the field for alignment or have one as default?

I think having Control on that or **having very good defaults** was my suggestion.
I see that Robert went for adding controls already. 

and it looks better now, imo >> https://latice.us.instawp.xyz/index.php/sample-page


https://user-images.githubusercontent.com/52494172/186179931-b65633e7-8335-43a6-8759-9269e01e7c57.mov

**Pull request merged**
