### PR TITLE
Popup enhancement

### PR DESCRIPTION
**Pull request by Soare-Robert-Daniel**
Closes https://github.com/Codeinwp/otter-internals/issues/12.

### Summary

New look on inspector and functionality.

### Screenshots 

image

----

### Test instructions

1. Test if the block is not breaking.
2. Check all the new options.

---- 

### Checklist before the final review

- [ ] Visual elements are not affected by independent changes.
- [ ] It is at least compatible with the [minimum WordPress version](https://wordpress.org/plugins/otter-blocks/).
- [ ] It loads additional script in frontend only if it is required.
- [ ] Does not impact the [Core Web Vitals](https://web.dev/vitals/).
- [ ] In case of deprecation, old blocks are safely migrated.
- [ ] It is usable in Widgets and FSE.

### CODE REVIEW

**Comment by HardeepAsrani** [comment]
@Soare-Robert-Daniel Screen Type option is too big. Can you see if we can use this instead? https://wordpress.github.io/gutenberg/?path=/story/components-experimental-alignmentmatrixcontrol--default. If it's not available in the 5.8 then we can use this for 5.9 and + and use a simple Select Field for 5.8.

**Comment by Soare-Robert-Daniel** [comment]
> @Soare-Robert-Daniel Screen Type option is too big. Can you see if we can use this instead? https://wordpress.github.io/gutenberg/?path=/story/components-experimental-alignmentmatrixcontrol--default. If it's not available in the 5.8 then we can use this for 5.9 and + and use a simple Select Field for 5.8.

Do you mean the Screen Position? It is already used with that component. @mghenciu suggested making it big to fill some space.

Initial
image

After some tweaks
image (1)

Inspiration from Blocksy
image (2)

**Comment by Soare-Robert-Daniel** [comment]
@mghenciu, is this close button variant ok

**Comment by Soare-Robert-Daniel** [comment]
@HardeepAsrani, for the position of the popup on the page for the vertical and horizontal axis, in frontend I have this:

https://github.com/Codeinwp/otter-blocks/blob/7b666e0c68e6160801b19be24eb715fb6479daab/src/blocks/blocks/popup/edit.js#L90-L117

And I struggle to translate it into PHP with our CSS generator.

https://github.com/Codeinwp/otter-blocks/blob/7b6f7c8aa3b15a0b1425f4e63c911a83d691e393/inc/css/blocks/class-popup-css.php#L144-L245

**Comment by irinelenache** [comment]
@Soare-Robert-Daniel Tested and everything looks good overall, good job 🚀  Here are some of my findings: 

- [ ] The border has no color control
- [ ] The **outside** border style isn't doing anything https://vertis.d.pr/i/gwy5zE
- [ ] The **ridge** border style is duplicated https://vertis.d.pr/i/8j0C54
- [ ] If the content added in the popup is bigger than the container dimensions, it will get out of the pop https://vertis.d.pr/i/SkP66b Maybe we should make it scrollable in cases like this?
- [ ] Disable page scrolling doesn't work on mobile
- [ ] If i have a popup that should be triggered on load, with a delay with a few seconds and disabled page scrolling, i won't be able to scroll the page until the popup is visible and i close it https://vertis.d.pr/v/oMY8I5
- [ ] If i have more popups added to a page and the scrolling is disabled for all of them, it will work only for the first popup https://vertis.d.pr/v/FHdarC

**Comment by Soare-Robert-Daniel** [comment]
> * [ ]  Disable page scrolling doesn't work on mobile

Is this on a real device?

> * [ ]  If i have more popups added to a page and the scrolling is disabled for all of them, it will work only for the first popup https://vertis.d.pr/v/FHdarC

This is ok.

**Comment by irinelenache** [comment]
@Soare-Robert-Daniel Checked again and all issues are fixed now, thank you 🚀 

@mghenciu Do you want to have another look before we move it to **Ready to merge**?

**Comment by mghenciu** [comment]
Thank you for testing Irinel!

Just a few questions @Soare-Robert-Daniel 👍 

### Border Styles
I see that in the **Border** Panel we have styles now (Dashed, Double, etc). My question **is if this is for all the Blocks were we have Border or just for this one?** I am asking from a Consistency perspective, as we can keep it in one block, but if we have 14 with border styles and the rest without, that's probably not what users would expect.
image

___

### Popup width in the Container
I think we talked about this before, how the Popup width will behave when the **List View is enabled** and the Container width is changing. Currently the Popup remains the same and nothing changes in terms of width. **Can we do something about this?**
Screenshot 2022-10-25 at 13 30 25


___
### Default Popup Padding
I was trying to build [this Popup](https://elementor.com/marketing/wp-content/uploads/2022/07/11_Popup_739_416.mp4), and during the build phase, I didn't managed to make the Popup padding to 0px. **Even when set to 0px, there will still be a 20px padding. Not sure if this is expected:**
Screenshot 2022-10-25 at 14 05 19

___
Is it possible, or we can revisit this in future, to have the **Default Height be the fit-content**, and if the users want, they can adjust it manually? The challenge I see now is that as a user you'll have to build the Popup, and after that tweak the Height gradually so it fits the content nicely without the scroll. And it's a bit of a tedious work.

**Comment by Soare-Robert-Daniel** [comment]
> ### Border Styles
> I see that in the **Border** Panel we have styles now (Dashed, Double, etc). My question **is if this is for all the Blocks were we have Border or just for this one?** I am asking from a Consistency perspective, as we can keep it in one block, but if we have 14 with border styles and the rest without, that's probably not what users would expect. 

I added the border style because we have a controller for border width. I put some flexibility on it. I can remove it if it looks unnecessary or inconsistent.

> ### Popup width in the Container
> I think we talked about this before, how the Popup width will behave when the **List View is enabled** and the Container width is changing. Currently the Popup remains the same and nothing changes in terms of width. **Can we do something about this?**

Fixed


> ### Default Popup Padding
> I was trying to build [this Popup](https://elementor.com/marketing/wp-content/uploads/2022/07/11_Popup_739_416.mp4), and during the build phase, I didn't managed to make the Popup padding to 0px. **Even when set to 0px, there will still be a 20px padding. Not sure if this is expected:** 

Fixed. The default calculation was 0 instead of 20.

> Is it possible, or we can revisit this in future, to have the **Default Height be the fit-content**, and if the users want, they can adjust it manually? The challenge I see now is that as a user you'll have to build the Popup, and after that tweak the Height gradually so it fits the content nicely without the scroll. And it's a bit of a tedious work.

We need UI for this kind of choice. The user must cause between a range of numbers and a non-number value. We can use a Selector for choosing between units (or a Toggle) and fit-content, then we display a field where you can add the value of the unit.

**Comment by mghenciu** [comment]
Took a look on the Popup, trying to make the Content fit using a section, but even when using a Section in Fit to Screen mode, still there's a scroll, and it doesn't not look as what I want to build > a full height page with the content inside vertically aligned to center:

https://user-images.githubusercontent.com/52494172/197799645-27e3fd70-8056-4e81-b60f-98d9c4bc6f46.mov




___


So we can go for the **Toggle** @Soare-Robert-Daniel , or either for this type of selector (from Elementor), that by default is fit content and has also a manual option: 
image

And what do you think if by default in the Popup we go for **Vertical Alignment center?** I am referring to the Content inside the Popup

**Comment by Soare-Robert-Daniel** [comment]
@mghenciu, I added the `fit-content` for height. It will be the default for all the views, and no mix-up (fit on desktop and custom on mobile. You can test it.

**Comment by mghenciu** [comment]
The **fit content** look good, Robert 🚀 
Just to confirm, it has the same behaviour on **Mobile** also, right?

___
There's a strange thing happening when a Section is in a Popup, and I try to transition between devices: **the Block settings are disappearing,** and I am not sure if this is because of the Popup or else

https://user-images.githubusercontent.com/52494172/198004937-6a3fb1bf-4820-49f4-b82f-d4ee11930aef.mov

**Comment by Soare-Robert-Daniel** [comment]
> The **fit content** look good, Robert 🚀 Just to confirm, it has the same behaviour on **Mobile** also, right?

Yes.

> There's a strange thing happening when a Section is in a Popup, and I try to transition between devices: **the Block settings are disappearing,** and I am not sure if this is because of the Popup or else

In my instance, it is ok. You can send an instance to check if it is repeating.

**Comment by irinelenache** [comment]
@Soare-Robert-Daniel I managed to replicate @mghenciu's issue, i see it happens when you select the section from the list view, here is a video https://vertis.d.pr/v/2NqEps

You can also check on this instance 
```
 Admin area URL: https://new-popup.s1-tastewp.com/wp-admin 
 Username: irinel 
 Password: SOpzfpyPvEA 
```

**Comment by Soare-Robert-Daniel** [comment]
> @Soare-Robert-Daniel I managed to replicate @mghenciu's issue, i see it happens when you select the section from the list view, here is a video https://vertis.d.pr/v/2NqEps
> 
> You can also check on this instance

I can see it now in the instance. That is very weird behavior. @HardeepAsrani, did you encounter something like this?

**Comment by HardeepAsrani** [comment]
@Soare-Robert-Daniel Of course, the block is not really selected so user can't see the settings.

**Pull request merged**
