### PR TITLE
Fix Slider in Sections

### LINKED ISSUE #1123: Section Block: Block breaks when editing "Section Structure Settings"
I have a weird issue with section block while working on a new starter site. 
[Here is a 1-min video showing the issue.](https://www.loom.com/share/63545fbbdb664c06b28bd97118e88a08)

**Recipe:**

1. Create a new section 
2. set the section to full width  
3. Define a custom content width 
4. Click on the alignment icons to align the content

5. The block breaks.

Note: If you duplicate the broken block, it gets duplicated just fine, and shows normal (not broken). But even at the duplicated block, if you try to open the Section Structure panel again, it still breaks.

Using latest versions of everything.

Let me know if you need any help with this one.

### LINKED ISSUE #1125: Slider Block not working inside Section
### Description:

JSON for the page in the video >> 
[blocks-export.json.zip](https://github.com/Codeinwp/otter-blocks/files/9396429/blocks-export.json.zip)

https://user-images.githubusercontent.com/52494172/185983712-08605d8b-8738-4fa2-b9bb-57bb7711ec00.mov

### How to reproduce:

1. Create a fresh instance
2. Install Otter
3. Import the JSON above on a page 

### Technical info
* WordPress version: 6.0.1
* Plugin version: 2.0.11

### PR DESCRIPTION
**Pull request by Soare-Robert-Daniel**
Closes #1125.

### Summary

Add `width` property. Default is `600px`.
### Screenshots 

----

### Test instructions

1. USE A FULL SITE EDITING THEME
2. Add a Section
3. Add a Slider to it.
4. See if it's working and play with the `Width`.

---- 

### Checklist before the final review

- [ ] Visual elements are not affected by independent changes.
- [ ] It is at least compatible with the [minimum WordPress version](https://wordpress.org/plugins/otter-blocks/).
- [ ] It loads additional script in frontend only if it is required.
- [ ] Does not impact the [Core Web Vitals](https://web.dev/vitals/).
- [ ] In case of deprecation, old blocks are safely migrated.
- [ ] It is usable in Widgets and FSE.

### CODE REVIEW

**Comment by Soare-Robert-Daniel** [comment]
⚠️ This fix is not working for FSE.

**Comment by Soare-Robert-Daniel** [comment]
When you create a slider in the section is working. But after reloading the page the slider breaks (FSE, Posts, Pages).

⚠️ This issue is only for Editor.

@HardeepAsrani @arinaturcu when you have some time can you look at this issue? Core Columns are working fine with Slider. I tried to play with the CSS (adding, disabling), but I could not pinpointed the issue.

**Comment by HardeepAsrani** [comment]
@Soare-Robert-Daniel The refresh issue seems to be happening only in Full Side Editing themes, works fine in Neve. Maybe worth checking if the issue is with Slider not being initialized.

**Comment by Soare-Robert-Daniel** [comment]
I suspect that in the FSE theme, the CSS files are not loaded correctly.

**Comment by irinelenache** [comment]
@Soare-Robert-Daniel Tested and the slider works fine in editor both for FSE themes or normal ones, found a single problem:

- [ ] Using **twenty twentytwo theme**, the **Slider** won't have a bigger width than the container (with Neve you can do that). This is how a slider with 1500px width looks in [editor](https://vertis.d.pr/4SUD3f) / [frontend](https://vertis.d.pr/V01pMi) (I don't know if it's exactly an issue but maybe it's worth mentioning it). Even if i add it inside a section and set the [alignment](https://vertis.d.pr/bcwzDJ) to **wide width**, the slider still won't take bigger width values

**Comment by Soare-Robert-Daniel** [comment]
@irinelenache, can you give me your test instance?

**Review by HardeepAsrani — CHANGES_REQUESTED** [review]
@Soare-Robert-Daniel It becomes a bit of a mess when you upgrade from an older version. You can add a width option but leave it empty by default and auto make it 600px if someone adds it inside a Section.

**Pull request merged**
