### PR TITLE
Add Copy/Paste for Otter and Core blocks

### LINKED ISSUE #776: Copy Paste Styles
Originally slated for 2.0, Copy/Paste Styles from one block to another, should be available for Otter + Core blocks, import media items on paste

### PR DESCRIPTION
**Pull request by Soare-Robert-Daniel**
Closes #776 .

### Summary

Copy the style between otter blocks and core blocks.

#### Core
```
core/columns
core/column
core/group
core/paragraph
core/heading
core/list
core/image
core/button
core/buttons
core/gallery
core/cover
```

#### Otter
```
advanced-columns
advanced-column
button-group
button
font-awesome-icons
icon-list
icon-list-item
accordion
progress-bar
tabs
flip
form
circle-counter
review
advanced-heading
countdown
```

⚠️ Not all the blocks are supported.

### Screenshots 

https://user-images.githubusercontent.com/17597852/191955272-0306e5d5-aac3-44d3-ab03-a66b699edee9.mp4

image

You can check the copied values in `Application > Local Storage` in `o-copyPasteStorage`

image

----

### Test instructions

1. Create a supported block.
2. Copy its style.
3. Paste it to another block.

#### Query
```javascript
new QueryQA().select('blocks').where({ has: { plugins: ['copy-paste'] } }).run()
```

---- 

### Checklist before the final review

- [x] Visual elements are not affected by independent changes.
- [ ] It is at least compatible with the [minimum WordPress version](https://wordpress.org/plugins/otter-blocks/).
- [x] It loads additional script in frontend only if it is required.
- [x] Does not impact the [Core Web Vitals](https://web.dev/vitals/).
- [x] In case of deprecation, old blocks are safely migrated.
- [ ] It is usable in Widgets and FSE.

### CODE REVIEW

**Comment by HardeepAsrani** [comment]
@Soare-Robert-Daniel 

- One thing I noticed when I copied styles from a paragraph where I had modified the color/background to a new paragraph (which had a font size set) that the font size of the first paragraph (which was undefined) was also copied. Can you check with Elementor if this is also how it works or how do they deal with this situation?

- The paste button should be disabled unless we have something that can be pasted to that block.

- Every time I copy styles from one Section Column to another, it automatically applies border. 

I think we need to see much overall how Elementor deals when copying/pasting between two items where the first item's one value was default while the other one had a set value. Does it carry on the default value to the pasting or lets the set value stay.

Overall, it looks pretty good so far.

**Comment by Soare-Robert-Daniel** [comment]
@Codeinwp/design-team, when you have some time, can you give some feedback to see if the functionality _feels right_? There might be some bugs, but I want to see if it does what you expect it to do.

**Comment by mghenciu** [comment]
> 

Would help to know what Blocks have this feature @Soare-Robert-Daniel , as I tried to do it with the Adv. Heading block, and surprisingly it's not present there. I see it's available for some Core blocks, like Heading & Paragraph.

**Comment by Soare-Robert-Daniel** [comment]
> > 
> 
> Would help to know what Blocks have this feature @Soare-Robert-Daniel , as I tried to do it with the Adv. Heading block, and surprisingly it's not present there. I see it's available for some Core blocks, like Heading & Paragraph.

Indeed. The list is

```
CORE 

core/columns
core/column
core/group
core/paragraph
core/heading
core/list
core/image
core/button
core/buttons
core/gallery
core/cover

OTTER

themeisle-blocks/advanced-columns
themeisle-blocks/advanced-column
themeisle-blocks/button-group
themeisle-blocks/button
themeisle-blocks/font-awesome-icons
themeisle-blocks/icon-list
themeisle-blocks/icon-list-item
themeisle-blocks/accordion
themeisle-blocks/progress-bar
themeisle-blocks/tabs
themeisle-blocks/flip
themeisle-blocks/form
themeisle-blocks/circle-counter
themeisle-blocks/review
```

**Comment by Soare-Robert-Daniel** [comment]
@mghenciu Thanks for the feedback 🚀 .


> Another thing I noticed is related to the **Alignment**. While using the Core Heading Block, I saw that the alignment is not inherited. Ideally, I think it should be inherited when Copy/Pasting styles from a block to another (not just for the Heading block, but in general).

Noted.

**Comment by Soare-Robert-Daniel** [comment]
@mghenciu @JohnPixle, the feature is almost complete. I will much appreciate a quick look at it before submitting it to QA 🙇 .

**Comment by irinelenache** [comment]
@Soare-Robert-Daniel Good job 🚀 Tested and here are my findings:

- [ ] For a **paragraph**, the alignment and bold from the first was not copied to the second https://vertis.d.pr/9s7tT9 (also the size is not copied, neither if i use pixels or em)
- [ ] For the **image block**, only the width/height changed after i pasted the style from the previous image. The first also had round style, box shadow, 50% dimension https://vertis.d.pr/u2p3uV
- [ ] For the **gallery block**, neither the columns number or masonry layout is copied
- [ ] For the **button group**, the shadow properties and the button style (fill/outline) is not copied https://vertis.d.pr/65PjYN
- [ ] For the **icon list**, the style (vertical/horizontal) is not copied https://vertis.d.pr/YNpOnB
- [ ] For the **progress bar**, the title style is not copied https://vertis.d.pr/LBaCLz
- [ ] For the **flip card**, the description font size is not copied. Also, the media image selected for the front side is copied to the other flip card https://vertis.d.pr/qn3CJQ
- [ ] For the **review block** a lot of styles are not copied: image width, style (default/boxed), typography, border/stars/pros/cons color, padding, border width, border radius and shadow options
- [ ] For the **countdown block** some styles are not copied: border width, font weights, label font size, block position 

You can check the issues on this instance:
```
 Admin area URL: https://copypaste.s2-tastewp.com/wp-admin 
 Username: irinel 
 Password: RyL4N8D2KMA 
```

**Comment by mghenciu** [comment]
Nice, Robert!
The feature feels right.

for the Keyboard shortcuts, Robert, is it possible to have them variable depending on the Device (Windows vs macOS)?
My question is if we can use more native controls, like CMD for mac and Ctrl for windows.

In Elementor they use **Ctrl / Cmd + Shift + V**, which is more common, my concern here is that in Gutenberg users can also use Cmd + Shift + V to paste a text without formatting (Paste as plain text), and this is also browser dependent.

So what I am thinking is that maybe we can use Cmd + Option + C/V  and  Ctrl + Alt + C/V to make this more OS common.

___
### Tested some blocks and here my findings:

- [ ] for Sections I see that the **Alignment** is not copied, I think it should be, as it also Style related:
Screenshot 2022-09-30 at 11 54 49

___
- [ ] **Sections Backgrounds** should also be copied when Copy/Pasting style, including Images/colors/overlays; and some goes for other blocks that have this options, like the Cover block
___
- [ ] Social Sharing Block from Otter, does not have the Copy/Paste options:
Screenshot 2022-09-30 at 15 54 26

___
- [ ] For all Blocks, keep in mind the Toolbar settings, if possible to Copy/Paste them. For example on the Core Paragraph block, the Bold & Italic options are not copied:
Screenshot 2022-09-30 at 16 30 49

___

- [ ] For the Section block, the Layout and Responsive options (how columns stack on mobile) should also be copied. 

___
In future, it will be nice to have the **Copy Paste between Adv. Heading & the Core Heading Block**, and reverse.

Also I wanted to ask how does this feature works **from a Performance point of view, does it consumes a lot of resources?** I am thinking if we can integrate the Copy Style feature directly on the Copy feature. Meaning that when a user copies a block, the style will also be copied, and the user can choose to paste the Block or Paste the style. But this may add extra load so that's why I am asking.

**Comment by Soare-Robert-Daniel** [comment]
@mghenciu, the combination `Cmd + Option + C/V` is not very reliable since most browsers have some actions on that combination. The `Chome` based browser usually opens the Inspector tab.

@mghenciu @irinelenache, the options from the `Styles` section, like Fill/Outline, will not be available since they are class-based. If the block does not save some information about it, it will not be copied.

image


In the future, we might support copying the class names.

**Comment by mghenciu** [comment]
For the Keyboard shortcuts, I wasn't aware that using the Option keyword also opens the Inspector.
Usually I use Cmd + Shift + C for the inspector.

I am not sure how this is done in Figma (browser) using the Clipboard, with Option + Cmd + C/V: 
image

or in Elementor:
image

**Comment by Soare-Robert-Daniel** [comment]
For shortcuts, we are using the Core component [KeyboardShortcuts](https://developer.wordpress.org/block-editor/reference-guides/components/keyboard-shortcuts/), which does **not** enforce the shortcut. Even `CMD+ALT+C` is unreliable for blocks like Heading or Paragraph; in Vivaldi, it moves the cursor at the beginning of the sentence.

**Comment by irinelenache** [comment]
@Soare-Robert-Daniel Checked again and almost all the marked issues are fixed 👍 

>  For the progress bar, the title style is not copied https://vertis.d.pr/LBaCLz

^ This issue still happens

>  For the flip card, the description font size is not copied. Also, the media image selected for the front side is copied to the other flip card https://vertis.d.pr/qn3CJQ

^ The media image is still copied to the second flip card. Also, the flip type is not copied

**Comment by Soare-Robert-Daniel** [comment]
@irinelenache, the issues should be fixed now 👍

**Comment by irinelenache** [comment]
@Soare-Robert-Daniel The issues are fixed now, thank you 🚀 

I'll leave this in the **Ready to test** column until the design team approve it too 👍

**Comment by Soare-Robert-Daniel** [comment]
@HardeepAsrani @JohnPixle, as discussed in the meeting. The new otter toolbar will be a part of this PR.

image

A few problems encountered:
 - Feedback: I tried to add the Feedback button, but the process was not straightforward. The Dropdown does not access buttons. Some changes need to be made, but I discovered we do not have enough space between the feedback trigger and the `Made by Otter`. We should make the text short.
 - The order of the components depends on the loading process. Still need to see how we can order them. E.g.: Sticky to be always last, or Copy/Paste to be always on top
 - We need some icons for Copy/Paste since we will not shortcuts
 - I did not find a method to add to the Dropdown a shortcut activation.

**Comment by HardeepAsrani** [comment]
> Feedback: I tried to add the Feedback button, but the process was not straightforward. The Dropdown does not access buttons. Some changes need to be made, but I discovered we do not have enough space between the feedback trigger and the Made by Otter. We should make the text short.

We can leave feedback for now.

> The order of the components depends on the loading process. Still need to see how we can order them. E.g.: Sticky to be always last, or Copy/Paste to be always on top

Perhaps in the slot-fill render you can do sorting based on the feature.

> We need some icons for Copy/Paste since we will not shortcuts

Or we can just not have icons for any option there. What do you think @JohnPixle 


PS: Paste Style should have S capital.

**Comment by Soare-Robert-Daniel** [comment]
@JohnPixle @mghenciu, do you think that the `Made by Otter` mark is a bit too more since we already use the otter icon in the toolbar 

image

If we had another icon for the toolbar, that text would make more sense for advertising. Since we use the logo, I feel that we are repeating it (we can use an icon similar to [this](https://www.flaticon.com/free-icon/toolbox_930502?term=toolbox&page=1&position=32&page=1&position=32&related_id=930502&origin=tag)). Don't know if I overthink this or it is desired to more subtle.

**Comment by mghenciu** [comment]
Agree @Soare-Robert-Daniel , having both Icons doesn't makes sense. 

You can remove the Icon, and try to fit the feedback there, but I still think things are crowded so **I would go for removing in this case the Power by** entirely: 
image

___

A middle ground for this could be adjusting the feedback text to this (I would suggest this one):
image

**Comment by Soare-Robert-Daniel** [comment]
The new look:

image

**Comment by HardeepAsrani** [comment]
Screenshot 2022-10-14 at 12 27 12 AM

I wonder if we need to really show them in both places now, @mghenciu @JohnPixle what do you think?

**Pull request merged**
