### PR TITLE
Load inline style

### LINKED ISSUE #1040: don't load otter styles if no otter block or feature is being used on the page
Right now if we don't use any block or block feature from Otter we still load some CSS always https://vertis.d.pr/BCWn7y

We need to have some mechanism of detection and dequeue that if nothing from Otter is being used.

### PR DESCRIPTION
**Pull request by HardeepAsrani**
Closes #1040, #922.

### Summary

This will load all Otter CSS (blocks pre-defined CSS + Otter's CSS) inline up to 20kbs.

### Screenshots 

----

### Test instructions

@irinelenache, you just need to test to make sure blocks work like they used to, not much to test. Loading is taken care by core itself.

---- 

### Checklist before the final review

- [x] Visual elements are not affected by independent changes.
- [ ] It is at least compatible with the [minimum WordPress version](https://wordpress.org/plugins/otter-blocks/).
- [x] It loads additional script in frontend only if it is required.
- [x] Does not impact the [Core Web Vitals](https://web.dev/vitals/).
- [x] In case of deprecation, old blocks are safely migrated.
- [x] It is usable in Widgets and FSE.

### CODE REVIEW

**Comment by irinelenache** [comment]
@HardeepAsrani Good job 🚀 Tested and found a single problem:

- [ ] The sticky feature doesn't work anymore with this PR

**Comment by HardeepAsrani** [comment]
Thanks, @irinelenache. For me, the Sticky is still working. Can you try again or let me know if you had any particular configuration that I need to replicate?

**Comment by irinelenache** [comment]
@HardeepAsrani You can check on this instance:
```
https://inline-css.s1-tastewp.com/2022/07/21/test-sticky/
Username: irinel  Password: 9tj7XJ59rpQ
```

**Comment by HardeepAsrani** [comment]
```
		if ( strpos( $content, '<!-- wp:' ) === false ) {
			self::$can_load_frontend = false;
			return false;
		}
```

It doesn't seem to be related to this PR. I can't reproduce on my instance but I can on your. Seems like it's being caused here somehow @Soare-Robert-Daniel with can_load_frontend being marked as false, probably from something fired before the sticky call. I find the whole can_load_frontend redundant for us as we don't really need to have it, just the check while loading the sticky script is fine. What do you think?

**Comment by HardeepAsrani** [comment]
Let me know what you think and I'll remove that to prevent it from not loading sometimes. @Soare-Robert-Daniel

**Comment by HardeepAsrani** [comment]
@irinelenache It should be fine now, can you confirm?

**Comment by irinelenache** [comment]
@HardeepAsrani Now everything works fine, thank you 🚀

**Pull request merged**
