### PR TITLE
Pricing Table

### PR DESCRIPTION
**Pull request by Soare-Robert-Daniel**
Import the pricing table from Neve

#### TO DO
- [x] Rename CSS
- [x] Dynamically adjust the items
- [x] Add option to change the colors
- [x] Edit price, currency, labels
- [x] Add link suport for buy buttons
- [x] Border options

#### Experiment
- [ ] Shadow Options
- [ ] Hover effects
- [ ] Alternative styles support

### CODE REVIEW

**Comment by HardeepAsrani** [comment]
Few thoughts:

- I don't think we need a container and table separately. It can just be a table block and people can put them as they want, be it standalone or insider a Section block.
- If you do this, you should hide the current Pricing block that we have from Inserter so there's no confusion.
- The default border can be removed, we can maybe have a default box-shadow.
- We can remove the Table Link option.

I'm actually not sure if this is how Marius intended it to be or if he wanted Woo/EDD integration. But I suppose we can do the best of what we think and let him review it in the end.

**Review by HardeepAsrani — CHANGES_REQUESTED** [review]
Few thoughts:

- I don't think we need a container and table separately. It can just be a table block and people can put them as they want, be it standalone or insider a Section block.
- If you do this, you should hide the current Pricing block that we have from Inserter so there's no confusion.
- The default border can be removed, we can maybe have a default box-shadow.
- We can remove the Table Link option.

I'm actually not sure if this is how Marius intended it to be or if he wanted Woo/EDD integration. But I suppose we can do the best of what we think and let him review it in the end.

**Comment by Soare-Robert-Daniel** [comment]
> Few thoughts:
> 
> * I don't think we need a container and table separately. It can just be a table block and people can put them as they want, be it standalone or insider a Section block.

I thought about it; I think it is better to have total control over the container. Most table prices have at least three tables.

> * If you do this, you should hide the current Pricing block that we have from Inserter so there's no confusion.

The old is not good enough. Do we retire the block?

**Comment by HardeepAsrani** [comment]
@Soare-Robert-Daniel

1. That limits how people can use it. In case they want to have a single table beside some left and images on the left. Even Neve's table does that.

We can add some Templates for a three table layout in the Templates Library to make it easier to add a three table layout.

2. Having two Pricing blocks will cause confusion so better to remove the old one from Inserter.

**Comment by mghenciu** [comment]
- I think the default mobile view, should be responsive (columns arrangement becomes vertical). This is how it looks now, by default: 
image

- it may be a good idea to add some mock text content, for the default state and not leave it empty (I am referring to the options in the list). This is how it looks now:
Screenshot 2022-02-02 at 11 05 42

- there looks to be an error in console when I am trying to change the Old Price:
image

- for columns width I think it should go for 100% (of the column). Basically when adding the Pricing Table, the default would look like this:
image

and it should look more like this:
image


Will stop here, for now.

**Comment by HardeepAsrani** [comment]
Closing this for now in favor of keeping them as variations or templates.

**Pull request closed without merging**
