### PR TITLE
Development

### PR DESCRIPTION
**Pull request by HardeepAsrani**
- Minor improvements in About Author Block: https://github.com/Codeinwp/otter-blocks/issues/789
- Fix Section Margin/Padding values not migrating properly: https://github.com/Codeinwp/otter-blocks/issues/807
- Fix Global Defaults error in Accordion and Review: https://github.com/Codeinwp/otter-blocks/issues/805
- Fix Translation Strings in Countdown: https://github.com/Codeinwp/otter-blocks/issues/783
- Fix issues in About Author Block: https://github.com/Codeinwp/otter-blocks/issues/789
- Add an option in the Tabs block to set the default tab: https://github.com/Codeinwp/otter-blocks/issues/698
- Remove problematic animations from the Animation module: https://github.com/Codeinwp/otter-blocks/issues/792
- Fix vertical alignment not working in Section: https://github.com/Codeinwp/otter-blocks/issues/837
- Add better API validation in Google Maps block: https://github.com/Codeinwp/otter-blocks/issues/806
- Add animation to Popup block: https://github.com/Codeinwp/otter-blocks/issues/796
- Option to toggle Block Conditions module off: https://github.com/Codeinwp/otter-blocks/issues/838
- Performance improvements: https://github.com/Codeinwp/otter-blocks/issues/799
- Fix sticky module conflicts: https://github.com/Codeinwp/otter-blocks/issues/868
- Fix webp not working in Section background: https://github.com/Codeinwp/otter-blocks/issues/867
- Lottie Block Improvements: https://github.com/Codeinwp/otter-blocks/issues/810
- Fix Posts block responsiveness: https://github.com/Codeinwp/otter-blocks/issues/844
- Fix Tabs and Masonry breaking in certain conditions: https://github.com/Codeinwp/otter-blocks/issues/832
- Fix infinity loops when using ID generating blocks in Reusable Block: https://github.com/Codeinwp/otter-blocks/issues/869

### CODE REVIEW

**Comment by irinelenache** [comment]
@HardeepAsrani Tested the build and here are my findings:

- [ ] The number of columns in the **Masonry** block doesn't work in editor (in frontend it seems to work) https://vertis.d.pr/2xPGVi
- [ ] I don't remember if this was expected, but the images captions in the **Masonry** block look look different in editor/frontend
editor: https://vertis.d.pr/ZzMpcQ
frontend: https://vertis.d.pr/Mo3QpR
If this is expected, can we at least indicate this for the user?

- [ ] Sometimes when i open a new post and add some blocks, i'm getting [these errors](https://vertis.d.pr/JNvVv3) in console. I wasn't able to isolate this, but happened after i ran this script with query engine:
 `new QueryQA().select('blocks').where({ has: ['accordion'] }).run()`

- [ ] With **Print shop** starter site installed, when i add a button group and select the buttons style as **outline**, they will look different in editor/frontend without making any change to them
editor: https://vertis.d.pr/2UeudN
frontend: https://vertis.d.pr/tmUm3p
 
- [ ] The box spacing in the **countdown** block isn't working in frontend
editor: https://vertis.d.pr/vLQYvU
frontend: https://vertis.d.pr/HN63Ix

- [ ] When i'm activating the **box shadow** for the **flip card**, the block breaks and i'm getting an error in console https://vertis.d.pr/GfttLv
- [ ] In **Icon** and **Icon list** blocks, the themeisle icons don't work anymore (in frontend only) https://vertis.d.pr/Fm1rvW
- [ ] Opening otter settings doesn't work and gives an error in console https://vertis.d.pr/kFn6LL
- [ ] The **Slider** block doesn't work, nothing happens after i'm adding images for it https://vertis.d.pr/cdnQsT
- [ ] When i add a paragraph inside a tab, the paragraph color is inherited from the **Active title color** that i set (it works fine in editor only)
editor: https://vertis.d.pr/nNwAhT
frontend: https://vertis.d.pr/cSMqDF

- [ ] For the **Product review**, when i sync it with Woocommerce, the product is not loading until i refresh the page https://vertis.d.pr/PZ4aan

⚠️  If you can't replicate some issues, it may be worth to check with a slower connection, i had slow internet the entire day

Will come with another comment after i'll test the other functionalities, for now i tested only the blocks

**Comment by HardeepAsrani** [comment]
> The number of columns in the Masonry block doesn't work in editor (in frontend it seems to work) https://vertis.d.pr/2xPGVi

>  I don't remember if this was expected, but the images captions in the Masonry block look look different in editor/frontend

- Masonry is giving too much trouble after 5.9 since they changed how the gallery block is built. For now I've added a notice saying the Masonry doesn't work in the backend and only in the front.

> Sometimes when i open a new post and add some blocks, i'm getting [these errors](https://vertis.d.pr/JNvVv3) in console. I wasn't able to isolate this, but happened after i ran this script with query engine:

I can't reproduce this. Might be cause I've removed Masonry script from loading in the backend. Can you confirm?

> With Print shop starter site installed, when i add a button group and select the buttons style as outline, they will look different in editor/frontend without making any change to them

These styles are coming from Neve, so nothing we can control in Otter.

>  The box spacing in the countdown block isn't working in frontend

Fixed!

I'll edit this comment as I go through the issues.

**Comment by irinelenache** [comment]
@HardeepAsrani I marked the fixed issues with a green check, thank you 🚀 

Here are some other findings:

- [ ] The **Themeisle icons** in the **Icon list** block get smaller when the text goes on multiple lines https://vertis.d.pr/F7hJ6i I remember @Soare-Robert-Daniel fixed this at some point
- [ ] The **tabs** block doesn't look ok on mobile https://vertis.d.pr/jrHSXH
- [ ] The **progress bar** doesn't look ok on mobile when the height is bigger than the default https://vertis.d.pr/ymxEuw
- [ ] When accordions are added inside another accordion, the arrow will look the same, no matter if it open or not https://vertis.d.pr/RboCN9

**Comment by HardeepAsrani** [comment]
> The tabs block doesn't look ok on mobile https://vertis.d.pr/jrHSXH

It's actually how we made it look for mobiles. We can think and see if we can improve it but yea, that's not a bug but how it's supposed to look. Looks weird if you just have one tab.

> The progress bar doesn't look ok on mobile when the height is bigger than the default https://vertis.d.pr/ymxEuw

Fixed.

> If i add a longer paragraph inside the Popup block, the popup will have full width in frontend and i couldn't make it smaller

Modal is behaving bit different inside the editor. In the next versions, we can add a maximum width option to Popup so users can control how it looks. But we can leave it for now.

**Comment by HardeepAsrani** [comment]
@irinelenache I've fixed the above-mentioned issues. Let me know if there's anything left or we should go ahead.

**Comment by irinelenache** [comment]
@HardeepAsrani The reported issues are fixed, thank you 🚀 
Didn't find any other problems 👍

**Comment by irinelenache** [comment]
@HardeepAsrani Find another strange issue:

- [ ] After importing **Architecture studio** starter site with the last version of otter and updating to this version, when i try to edit a page the editor is not loading and i'm getting an error in console https://vertis.d.pr/hH6nRP

**Pull request merged**
