### PR TITLE
Update Fontawesome

### LINKED ISSUE #1485: Add TikTok icon to Icon block
### Description:
Icon block is missing TikTok icon, knowing the popularity of this social network we should add it:
image

### Alternatives:
Upload icon another way than using Icon block.
 
Requested here - https://wordpress.org/support/topic/icon-picker-missing-icons-when-using-font-awesome-library/

### PR DESCRIPTION
**Pull request by HardeepAsrani**
Closes #1485.

### Summary

A quick bump to Fontawesome.

### Test instructions

- Make sure the Accordion, Icons & Icon List work nicely.

---- 

### Checklist before the final review

- [x] Visual elements are not affected by independent changes.
- [x] It is at least compatible with the [minimum WordPress version](https://wordpress.org/plugins/otter-blocks/).
- [x] It loads additional script in frontend only if it is required.
- [x] Does not impact the [Core Web Vitals](https://web.dev/vitals/).
- [x] In case of deprecation, old blocks are safely migrated.
- [x] It is usable in Widgets and FSE.
- [x] Copy/Paste is working if the attributes are modified.

### CODE REVIEW

**Comment by irinelenache** [comment]
@HardeepAsrani Tested and the icon doesn't work in the accordion context, here is how it looks (closed and open) https://vertis.d.pr/i/LaL8OT

**Comment by HardeepAsrani** [comment]
@irinelenache I've fixed it, it was working with some icons and not working with some because of change in new unicodes for FA icons.

**Comment by irinelenache** [comment]
@HardeepAsrani Now it doesn't work with any icon i select in the accordion https://vertis.d.pr/i/CWhZIe

You can check here:
```
 Admin area URL: https://otternewrel.s1-tastewp.com/wp-admin 
 Username: irinel 
 Password: xFVOFEceRMQ 
```

**Comment by HardeepAsrani** [comment]
@irinelenache Wow, it was working fine for me with 20 different icons I tried. Thank you Irinel, I'll take another look and see.

**Comment by HardeepAsrani** [comment]
@irinelenache This seems to be an issue where in the last attempt, it was working with the post but wasn't working in the preview. This time it is working with the preview but not working when the post is published. Some strange stuff but I think this bug was also before this PR. I'll see what I can do to solve it given there are some bottlenecks here, just wanted to update to you here so next time when you test, you can test it all scenarios.

**Comment by HardeepAsrani** [comment]
@irinelenache I've tried to make something that works with various cases, can you see how it goes? Also, maybe just check it with multiple things, like adding few patterns to make sure everything looks the same on both ends, in the preview and final post.

**Comment by irinelenache** [comment]
@HardeepAsrani Checked again and the tiktok icon isn't visible at all, neither in selector, editor or frontend https://vertis.d.pr/v/FlEByn Rest of the things regarding the icons seem to work fine

You can check here:
```
 Admin area URL: https://hideticket.s1-tastewp.com/wp-admin 
 Username: irinel 
 Password: PLEXCHp6i1s 
```

**Comment by irinelenache** [comment]
@HardeepAsrani As we talked on Slack, the problem was because of using a Chrome Adblocker, so everything's fine here 🚀

**Pull request merged**
