### PR TITLE
Block Registration API 2

### PR DESCRIPTION
**Pull request by HardeepAsrani**
This migrates all the blocks in Otter to Block V2 API.

For QA team:

- You need to make sure all the blocks work perfectly.
- The migration from the last version works smoothly.
- The blocks work fine on 5.6 too.
- Most importantly, I had to make shit tons of changes to Section block so make sure it works fine and doesn't break.

### CODE REVIEW

**Comment by HardeepAsrani** [comment]
Need your QA eyes here @irinelenache when you're free.

**Comment by irinelenache** [comment]
@HardeepAsrani Did some testing and found a few issues:
(Didn't test the migration and compatibility with older wp versions yet)

- [ ] **Advanced heading** shadow properties don't work as expected when the color is selected from the palette https://vertis.d.pr/DpH1dL
- [ ] If i add a **Circle counter** and a **progress bar** next to it like [this](https://vertis.d.pr/pikuVr), it will look like [this in frontend](https://vertis.d.pr/Dr3Qn6)
- [ ] The **flip card** media width, height and aligning are not respected in frontend
editor: https://vertis.d.pr/zzaON7
frontend: https://vertis.d.pr/80JJKV

- [ ] When **Product review** is synced with Woocommerce, the selected text color doesn't have any effect on the product description https://vertis.d.pr/VwZWm0
- [ ] The buttons in the **Review comparison** look different in editor/frontend
editor: https://vertis.d.pr/Ng78DC
frontend: https://vertis.d.pr/SJPFcd

**Comment by HardeepAsrani** [comment]
@irinelenache 

>  Advanced heading shadow properties don't work as expected when the color is selected from the palette https://vertis.d.pr/DpH1dL

That happens because Neve uses variables and currently we can't put opacity with them. It's fine for now.

> If i add a Circle counter and a progress bar next to it like this, it will look like this in frontend

Added some default margin.

> The flip card media width, height and aligning are not respected in frontend

Not related to this PR, I'll open a separate PR.

> When Product review is synced with Woocommerce, the selected text color doesn't have any effect on the product description https://vertis.d.pr/VwZWm0

Fixed.

> The buttons in the Review comparison look different in editor/frontend

It happens because of Neve's editor styles. It's fine.

Are there any other issues?

Thank you!

**Comment by irinelenache** [comment]
@HardeepAsrani

> When Product review is synced with Woocommerce, the selected text color doesn't have any effect on the product description https://vertis.d.pr/VwZWm0
> 
> Fixed.

This one still happens in front-end, it works fine in editor only.

Besides of that, everything seems to work fine 👍

**Comment by HardeepAsrani** [comment]
@irinelenache seems to be working fine for me, I tried on many browsers. Anyway, small thing. We can let it go.

**Pull request merged**
