### PR TITLE
Button Group Enhancement

### LINKED ISSUE #1396: Button Group Sidebar rework
### Description:

Translate the latest UI improvements we did for other blocks, also for the Button Group block, as it's one of the most used blocks.

### PR DESCRIPTION
**Pull request by Soare-Robert-Daniel**
Closes #1396.

### Summary

- UI refresh.
- Global Defaults Support.
- Responsive attributes.
- New Typography component.

----

### Test instructions

Main focus:
- Old blocks must not break when upgraded.
- Responsive attributes.

ℹ️ Shadow is not inherited. You need to set both Normal and Hover.

---- 

### Checklist before the final review

- [ ] Visual elements are not affected by independent changes.
- [ ] It is at least compatible with the [minimum WordPress version](https://wordpress.org/plugins/otter-blocks/).
- [ ] It loads additional script in frontend only if it is required.
- [ ] Does not impact the [Core Web Vitals](https://web.dev/vitals/).
- [ ] In case of deprecation, old blocks are safely migrated.
- [ ] It is usable in Widgets and FSE.
- [ ] Copy/Paste is working if the attributes are modified.

### CODE REVIEW

**Comment by mghenciu** [comment]
### Tested the build and this are my findings:
- by Default, I see that the Style panel is selected when opening/adding a Button Group or a single button. Not sure what's the reason behind this.
- **I think we can add some options in the Top Toolbar** for the Button group (right now is empty), getting inspiration from the Core Buttons. I would suggest to add at least the Alignment:
Screenshot 2023-01-18 at 11 00 40

___

- [ ] Spacing should be **Space Between** (as spacing sounds too general). If there is a Translation concern, we can leave it as it is.
image

___

- [ ] **Panel naming should be consistent**, so either use Settings with capital S or without, everywhere (in Figma it's without): 
Screenshot 2023-01-18 at 11 08 53

___

- [ ] **Buttons should have the same default Padding in backend**, when Outlined or Filled. Currently the Filled one has 15px30px, and Outlined 10px12px. In frontend, they look ok:
image
  

___

- [ ] **For the Single Button shadow Global Syncing, I think the settings are too granular**. My assumption is that people would usually either sync the shadow or not, and not each of those controls. So I would suggest having just the option to sync shadow (@JohnPixle , let me know in case you have a different opinion about this): 
Screenshot 2023-01-18 at 11 21 13

___
Another thing about the Shadow, is that the control looks a bit different from the Section block. I think we talked about this before, but I am not sure if it's a technical limitation or something: 
image
Screenshot 2023-01-18 at 11 27 04

**Comment by mghenciu** [comment]
The issues mentioned above are fixed. Thank you, Robert!
But I noticed that now all the buttons have a Shadow in backend (attached video):

https://user-images.githubusercontent.com/52494172/213213425-7ebec5a9-5387-426e-84ae-2c8f3ce5809f.mov

**Comment by HardeepAsrani** [comment]
- I find the Typography control to be very unsettling different (...) that don't really tell me what it will do. Should we just keep it to a Open/Close panel for now? The Global Sync controls don't help much here. @mghenciu @JohnPixle 
Screenshot 2023-01-23 at 5 18 44 AM

- Can we follow what Core does with the size of the controls? We can save a lot of space that way.
Screenshot 2023-01-23 at 5 18 57 AM
Screenshot 2023-01-23 at 5 19 09 AM

- Finally, I see all the Panels are open by default so we can close some. Guessing Robert did it for testing/dev but we can close them now.

**Comment by mghenciu** [comment]
Can you please elaborate more on the first question?
___

If this is about the Typography controls, **YES** those were intended to be as in Core. [Figma](https://www.figma.com/file/LRrhO1ovZnXFibXVsezR8a/Otter?node-id=1147%3A17344&t=IlANxXOP4rxCIcaJ-1)
___
> Finally, I see all the Panels are open by default so we can close some. Guessing Robert did it for testing/dev but we can close them now.

I agree with you. My assumption is that users will open the Typography Panel rarely, so I think **we can have it closed by default.**

**Comment by irinelenache** [comment]
@Soare-Robert-Daniel Tested and here is what i found:

- [ ] After adding this PR, some existing blocks changed their appearance. [This button](https://d.pr/j2i93m) changed to [this](https://vertis.d.pr/i/epLP05)
- [ ] After just hitting **Update** in the post editor, without making any change, most of the buttons became bordered 
before update: https://vertis.d.pr/i/mLXluZ
after update: https://vertis.d.pr/i/eozxoA

- [ ] In the editor, the previously added button groups changed from [this](https://vertis.d.pr/i/kHN2nX) to [this](https://vertis.d.pr/i/bM4Qvg)

^ These mentioned issues can be checke on this post https://otter-enh.s4-tastewp.com/2023/01/31/test-button-groups/

- [ ] There is a weird behaviour when i change the alignment and the button size. I made a video with it https://vertis.d.pr/v/cJ0Jrb
- [ ] When i just set the style variation for the buttons, without making any other change, they will look different in editor and frontend. You can see in this video https://vertis.d.pr/v/WNeXph

^ These mentioned issues can be chacked on this post https://otter-enh.s4-tastewp.com/2023/01/31/new-created-button-group/

Here are the credentials:
```
 Admin area URL: https://otter-enh.s4-tastewp.com/wp-admin 
 Username: irinel 
 Password: eXxX0pag7p0 
```

**Comment by Soare-Robert-Daniel** [comment]
> * [ ]  In the editor, the previously added button groups changed from [this](https://vertis.d.pr/i/kHN2nX) to [this](https://vertis.d.pr/i/bM4Qvg)

I have updated the hover and color conditions. Should work better now. Also, in the old version, the style outline did not worked correctly (the background was not transparent) - this why you see a sudden change in some buttons.

> * [ ]  When i just set the style variation for the buttons, without making any other change, they will look different in editor and frontend. You can see in this video https://vertis.d.pr/v/WNeXph

Now they should look more alike. Also, the theme heavy influence the look for Plain and Outline. 

On Outline, the background is transparent, and in Plain only the text is showed. Since most theme use white for text color and background with contrast (blue, red, black), when you remove the background, the button is invisible.

**Comment by irinelenache** [comment]
@Soare-Robert-Daniel The marked issues are fixed, thank you ✅ Here are some other findings:

- [ ] The button size doesn't work in editor https://vertis.d.pr/v/W7wAaU
- [ ] I think the background and border color controls shouldn't be present when the button style is plain, they won't work and that might be confusing
- [ ] Same for the Outline style, maybe we can remove the background color
- [ ] The button colors don't work in editor (the hover colors work) and that's pretty confusing https://vertis.d.pr/v/Vaqo0V . Maybe we can at least notice the users that the buttons are influenced by the theme style and they'll look different in editor/frontend?

Let me know what you think 👍

**Comment by Soare-Robert-Daniel** [comment]
🙏  Fixed the regression with CSS

> * [ ]  I think the background and border color controls shouldn't be present when the button style is plain, they won't work and that might be confusing
> * [ ]  Same for the Outline style, maybe we can remove the background color

If we remove them, the controls will look underwhelmed, especially for Plain in which you have only the text color (like in the image bellow). CC: @mghenciu 

image

**Comment by Soare-Robert-Daniel** [comment]
I discussed with @mghenciu and the style should work like in Core (Button): They act like a default value but do not override the actual value.

So, the outline style has a background as transparent, but if you set the value in the Color panel, it will change the color to the set value. I made the changes to express this idea. 

Since styles do not enforce some settings, there is no need to remove things.

**Comment by irinelenache** [comment]
@Soare-Robert-Daniel Thank you for explaining 👍 

One more small issue:

- [ ] The border color isn't working in the editor (it works fine in frontend) https://vertis.d.pr/v/aki1A6

If that's expected and can't be fixed, we can move this to **Ready to merge**

**Comment by Soare-Robert-Daniel** [comment]
The minor issue in the Editor is now fixed.

@HardeepAsrani, we have an inconsistency with the Global CSS: if I sync an attribute, and the value from Global CSS is undefined, that attribute will be broken because even though the CSS var is empty, the style is considered valid and override other settings.

image

Thus, the theme value is override 

image

**Comment by irinelenache** [comment]
@Soare-Robert-Daniel Tested and everything's fine now, thank you 🚀

**Comment by HardeepAsrani** [comment]
@Soare-Robert-Daniel Here I'm expecting that if you have synced with Global Default, you must have set something there.

Apart from that, this is ready to go, right?

**Comment by Soare-Robert-Daniel** [comment]
@HardeepAsrani, yes, it is.

**Comment by HardeepAsrani** [comment]
Screenshot 2023-02-13 at 10 52 24 AM

@Soare-Robert-Daniel You can merge this, just make sure to fix this CSS issue first.

**Pull request merged**
