### PR TITLE
Manage text color for Dark Backgrounds

### LINKED ISSUE #1440: Initialise by default the Text color on the Advanced Heading
### Description:

**I think from an UIX point of view, it may be better to have the Text Color already initialised for the Advanced Heading block.**
At this point, when adding a new Adv. Heading or when converting a Heading to Adv. Heading, the color panel is empty, and there is just the + Icon. To change the color, right now an user would need at least **5 clicks**, and I think this add too much friction.
Screenshot 2023-01-12 at 18 51 29

cc. @JohnPixle

### PR DESCRIPTION
**Pull request by HardeepAsrani**
Closes #1440.

### Summary

@mghenciu @JohnPixle This is just a test before I implement it in other blocks but this is the implementation I was talking about in the github. Can you both let me know what you think of it and if you see any issues here?

Paragraph block in particular doesn't work nicely in Neve as Neve tries to force a font color but you should be able to use it with Heading/Adv Heading or other themes.

#### Update

Implemented in: Review, Accordion, Section, Popup, Tabs, Posts, Advanced Heading, Business Hours, Flip

### Screenshots 

----

### Test instructions

Make sure the the text color becomes light if the block has a dark background color, and old blocks aren't affected (as in don't break)

---- 

### Checklist before the final review

- [x] Visual elements are not affected by independent changes.
- [x] It is at least compatible with the [minimum WordPress version](https://wordpress.org/plugins/otter-blocks/).
- [x] It loads additional script in frontend only if it is required.
- [x] Does not impact the [Core Web Vitals](https://web.dev/vitals/).
- [x] In case of deprecation, old blocks are safely migrated.
- [x] It is usable in Widgets and FSE.
- [x] Copy/Paste is working if the attributes are modified.

### CODE REVIEW

**Comment by mghenciu** [comment]
Looks good, Hardeep!
I also tested with the Adv. Heading in a Section going from white to dark, and the color is responsive.
Would love to see this in the Product Review block, and other blocks text based.

Also, wanted to mention that this doesn't solves the issue I mentioned [here](https://github.com/Codeinwp/otter-blocks/issues/1440), with the Text Color not being added by default. Is there any chance to achieve it?

**Comment by HardeepAsrani** [comment]
@mghenciu We can show it by default. That's not hard to do, I think I misunderstood your initial question and thought you wanted to have the color inside, not just the panel. 😄

**Comment by HardeepAsrani** [comment]
I've implemented in Review, Accordion, Section, Popup, Tabs, Posts, Advanced Heading, Business Hours, Flip - anything else, or I should put it up for QA @mghenciu

**Comment by HardeepAsrani** [comment]
^ @JohnPixle

**Comment by mghenciu** [comment]
> I've implemented in Review, Accordion, Section, Popup, Tabs, Posts, Advanced Heading, Business Hours, Flip - anything else, or I should put it up for QA @mghenciu

Awesome job, Hardeep!
Mega-nice that it also works if I copy an Adv. Heading from a Dark section on a Light one, it will adapt 🚀 

___

Few things I noticed:

- [ ] I think this could also apply for the **Tabs border**, similarly how it works on the Accordion:
image
Right now it's dark on both Light & Dark backgrounds.

- [ ] Same for the **Border** of the Countdown block
image


- [ ] **Sharing Icons text should use the Icon Color**. At this point it's Dark and doesn't look good in a light Context:
image
image
Note: this may be a general issue with this block, not from this PR. 

___

- [ ] on another note, is it possible to have the Forms in one line (right now those are on multiple lines)? and the Icon + Icons list, close to each other : 
Screenshot 2023-01-20 at 12 45 48

I can make another issue, if needed.

___
Tested the insertion for all of our blocks, and except the things mentioned above - it looks ready for QA 🏎️

**Comment by HardeepAsrani** [comment]
I'll take care of the other mentioned points, about this:

>  on another note, is it possible to have the Forms in one line (right now those are on multiple lines)? and the Icon + Icons list, close to each other :

Maybe we can manage this outside but I wonder if we should remove those Variations from Inserter?

**Comment by HardeepAsrani** [comment]
To give more context: we can probably have more premade templates, like RSVP, Quote and such, so perhaps we should only show them when you add the block, and not outside else we will have a lot of variations appearing.

**Comment by HardeepAsrani** [comment]
@mghenciu For the border issue, it's hard to control the border. We can just make the border variable white if the Section has a dark background, but then it has an issue if the section has another section inside which has white background.

**Comment by irinelenache** [comment]
@HardeepAsrani Tested and everything's fine on my end ✅

**Comment by HardeepAsrani** [comment]
@irinelenache Awesome, that's it for the release, now we can get that tested and release. Thanks for squeezing in extra stuff for the release!

**Pull request merged**
