### PR TITLE
[WiP] Woo Blocks

### PR DESCRIPTION
**Pull request by HardeepAsrani**

### CODE REVIEW

**Comment by HardeepAsrani** [comment]
@irinelenache Can you review this? You need to have WooCommerce & Neve Pro with Booster active. Once you've that, you can create edit, or create a Woo product and you'll see an option to enable Woo Builder from where you can add the new Woo blocks and create a custom WooCommerce block like this:

Screenshot 2021-12-10 at 1 42 47 AM

Let me know how it goes.

**Comment by irinelenache** [comment]
@HardeepAsrani Tested and found a few problems:

- [ ] When i only **disable WooCommerce builder**, the page is not entirely rolled back to its original state (All blocks are still visible in the description tab). I have to delete all blocks before disabling the builder in order to have the page look as before.  https://vertis.d.pr/NiLYxP https://vertis.d.pr/RfAw5p
- [ ] The **Product Add to cart** is not aligned with the quantity input https://vertis.d.pr/2Pwzbk
- [ ] The stock appears both in **Product stock** block and in **Add to cart** block (https://vertis.d.pr/nyvtvk). I don't know if it's a problem but wanted to let you know.
- [ ] The description tab is not visible when Woo builder is enabled https://vertis.d.pr/RQziMG
- [ ] The product navigation isn't visible for a product created with Woo builder
product created with woo builder: https://vertis.d.pr/pxyT7K
default product: https://vertis.d.pr/3QvJbY
- [ ] The exclusive products aren't visible for a product created with Woo builder

Besides this it seems to work fine 🚀 
Let me know if you have any special behaviour to test 👍

**Comment by HardeepAsrani** [comment]
@irinelenache 

1. Makes sense, we can maybe make it empty.
2. CSS issue, not related to us.
3. That's how Woo works.
4. Yea because blocks are added to description. If you show description tab, it will be infinite loop.
5. I don't get this. Can you make exactly what you're referring to in the image?
6. Can you please explain this with more details?

**Comment by irinelenache** [comment]
@HardeepAsrani For the points 5 & 6:
Neve has some customizer settings that enable **Product navigation** and **Exclusive products** (https://vertis.d.pr/LR5EVF). These features don't work anymore when a product is created with WooCommerce Builder.

**Comment by HardeepAsrani** [comment]
@irinelenache Got it. Were all other options from Neve were working properly apart from these two? Thank you!

**Comment by HardeepAsrani** [comment]
@irinelenache All should be fixed. Let me know how it goes.

**Comment by irinelenache** [comment]
@HardeepAsrani Now i can't add any block from Otter, they don't appear in editor's block list, neither when i want to add a post or enable the WooCommerce builder.

You can check it here:
```
 Admin area URL: https://caredriving.tastewp.com/wp-admin 
 Username: irinel 
 Password: HedrkuPbhKk 
```

**Comment by HardeepAsrani** [comment]
@irinelenache I am able to do that from the tastewp instance you provided. 

Screenshot 2021-12-18 at 1 56 19 AM

**Comment by irinelenache** [comment]
@HardeepAsrani Still doesn't work for me, i get some errors in console too https://vertis.d.pr/IPnhCw . It's related to my configuration.
**It doesn't work** with `MacBook Pro 13-inch, 2017, macOS Big Sur 11.5.2` and `Chrome Version 93.0.4577.82 (Official Build) (x86_64)` and **it works** with `Safari Version 14.1.2 (16611.3.10.1.6)`

**Comment by HardeepAsrani** [comment]
@irinelenache can you check now and see if it works? I have tested with all browsers this time and it seems to work just fine for me. Thank you!

**Comment by irinelenache** [comment]
@HardeepAsrani Tested again and everything seems to work as expected 🚀

**Pull request merged**
