### PR TITLE
Release 1.3.2

### PR DESCRIPTION
**Pull request by HardeepAsrani**
- Add tracking toggle to Option Page
- Use React Hooks for Option Panel

### CODE REVIEW

**Comment by rodica-andronache** [comment]
@HardeepAsrani I've tested all the blocks in WP 5.2 and 5.3 and most of the things worked well for me. Here's some things I've seen:

Issues:
- **Section** block is missing the images https://prnt.sc/qktk21
- the **Our Blog** template is not loading at first when I add it in the post. I get the "This block has encountered an error and cant be previewed." On frontend is working well, and in the editor as well, after save and refresh https://prnt.sc/qkukav

This is the current behavior in the plugin, it's not related to this PR, but I wanted to be sure that's correct.
- in the **Posts** block: authors that are Subscribers don’t appear in the post meta in the dashboard, just on front-end https://prnt.sc/qkuiuf

I also had some questions:
- What are the **Highlight Color** and **Highlight Background** options doing in the Advanced tab? I'm not sure how to test the options
- I remember at some point, that this spacing between sections could be controlled with drag and drop there, but I saw that's not happening anymore. Is that ok? https://prnt.sc/qkulcb

**Comment by HardeepAsrani** [comment]
> Section block is missing the images https://prnt.sc/qktk21

@rodica-andronache This doesn't happen with me. Which plugins and themes were active? Can you see the CSS of svg inside those buttons and see what's causing it?

**Comment by HardeepAsrani** [comment]
> in the Posts block: authors that are Subscribers don’t appear in the post meta in the dashboard, just on front-end https://prnt.sc/qkuiuf

Subscribers aren't supposed to be Post Author, as they're only subscribers. You should test it with Contributor.

**Comment by rodica-andronache** [comment]
@HardeepAsrani the images from the Section block are visible just in Firefox. ( Chrome and Safari not )
You can check it here if needed https://regulatory-vampire.jurassic.ninja/wp-admin (admin/admin)

**Pull request merged**
