### PR TITLE
Development

### PR DESCRIPTION
**Pull request by HardeepAsrani**
- https://github.com/Codeinwp/otter-blocks/issues/999
- https://github.com/Codeinwp/otter-blocks/issues/1072
- https://github.com/Codeinwp/otter-blocks/issues/1083
- https://github.com/Codeinwp/otter-blocks/issues/1092
- https://github.com/Codeinwp/otter-blocks/issues/652
- https://github.com/Codeinwp/otter-blocks/issues/1089
- https://github.com/Codeinwp/otter-blocks/issues/1090
- https://github.com/Codeinwp/otter-blocks/issues/1093
- https://github.com/Codeinwp/otter-blocks/issues/986
- https://github.com/Codeinwp/otter-blocks/issues/1107
- https://github.com/Codeinwp/otter-blocks/issues/1111
- https://github.com/Codeinwp/otter-blocks/issues/1078
- https://github.com/Codeinwp/otter-blocks/issues/912
- https://github.com/Codeinwp/otter-blocks/issues/1085
- https://github.com/Codeinwp/otter-blocks/issues/1073
- https://github.com/Codeinwp/otter-blocks/issues/1110

---- 

### Checklist before the final review

- [ ] Visual elements are not affected by independent changes.
- [x] It is at least compatible with the [minimum WordPress version](https://wordpress.org/plugins/otter-blocks/).
- [x] It loads additional script in frontend only if it is required.
- [ ] Does not impact the [Core Web Vitals](https://web.dev/vitals/).
- [x] In case of deprecation, old blocks are safely migrated.
- [x] It is usable in Widgets and FSE.

### CODE REVIEW

**Comment by HardeepAsrani** [comment]
@irinelenache We're ready for a release. Can you put this through QA before we do the release? Thank you!

**Comment by irinelenache** [comment]
@HardeepAsrani Here are my findings:

- [ ] The shadow for the **Advanced heading** doesn't work with colors selected from the palette https://vertis.d.pr/2rse3u
- [ ] For the **progress bar**, the percentage is not visible in editor when its position is set to **Outer** https://vertis.d.pr/VXOQXQ (In frontend it works fine)
- [ ] When i'm changing the font for the **button group**, the block breaks and i'm getting an error in console https://vertis.d.pr/OKASLL
- [ ] When there is a button with icon only in the button group, it will not be centered if Themeisle icons are used and the alignment is full width
how it looks with FA icon: https://vertis.d.pr/ZieVUu
how it looks with Themeisle icons: https://vertis.d.pr/CUM7Oj

_Note: testing is not finished, will update the comment as i find more issues_

**Comment by Soare-Robert-Daniel** [comment]
> * [ ]  The shadow for the **Advanced heading** doesn't work with colors selected from the palette https://vertis.d.pr/2rse3u

@HardeepAsrani the color controller offers neve vars instead of hex values when choosing from predefined values.

**Comment by HardeepAsrani** [comment]
> @HardeepAsrani the color controller offers neve vars instead of hex values when choosing from predefined values.

@Soare-Robert-Daniel We had implemented something similar in the past, if I remember correctly, where we converted the value to hex, right?

**Comment by HardeepAsrani** [comment]
@irinelenache The issues should be fixed. The Heading one about Shadow can be left as it's not related to this release and we can fix it separately.

**Comment by HardeepAsrani** [comment]
@irinelenache forgot to add, this PR now should also fix the issue with non-super admins not being able to properly save some blocks on Network sites.

**Comment by irinelenache** [comment]
@HardeepAsrani I marked the fixed issues, also the Network issue is fixed, thank you 🚀 

> When i use alignment - right for the Lottie animation, the block will get over the comments section https://vertis.d.pr/O5ahDn

^ This one is still happening

- [ ] With the percentage set as **Outer** for the **Progress bar**, the text size will be different in editor/frontend
editor: https://vertis.d.pr/rUk7To
frontend: https://vertis.d.pr/hl69KB

- [ ] None of the styles work in FSE frontend (they work in editor only)
editor: https://vertis.d.pr/566nNi
frontend: https://vertis.d.pr/dkyt6D

Besides these, everything seems to work fine 👍

**Comment by HardeepAsrani** [comment]
@irinelenache

1. That's normal. That's not an issue. Even Image block behaves the same way as it adding floating property.

2. I'll check that.

3. Can you check with production build? Might be an issue with the particular build.

**Comment by HardeepAsrani** [comment]
@irinelenache I've fixed the second issue.

**Comment by irinelenache** [comment]
@HardeepAsrani The styles in FSE work fine now, maybe it was a caching issue 👍 

The latest issues linked to this release should also be fixed?

**Comment by HardeepAsrani** [comment]
@irinelenache Yea but they don't require additional testing. They're one line fixes.

**Comment by HardeepAsrani** [comment]
It's good to go then, @irinelenache?

**Comment by HardeepAsrani** [comment]
It's good to go then, @irinelenache?

**Comment by HardeepAsrani** [comment]
It's good to go then, @irinelenache?

**Comment by irinelenache** [comment]
@HardeepAsrani Everything's ok on my end, so good to go 🚀

**Pull request merged**
