### PR TITLE
Add the option to hide the blocks in Inserter.

### PR DESCRIPTION
**Pull request by Soare-Robert-Daniel**
Closes #.

### Summary

Add UI for disabling Otter Blocks in Editor Inserter. This feature allows users to select what blocks they want to use.

The blocks on the page are not affected.

ℹ️ Added a shortcut in named `Blocks`s below Settings. When you enter, it will create a redirect to Dashboard with the Tab set on `Blocks`

### Screenshots 

image

https://github.com/Codeinwp/otter-blocks/assets/17597852/a066b765-342d-4de7-af58-4bb812032114

----

### Test instructions

Test the enable/disable functions. They should work like in the video attached. 

---- 

### Checklist before the final review

- [ ] Included E2E or unit tests for the changes in this PR.
- [x] Visual elements are not affected by independent changes.
- [x] It is at least compatible with the [minimum WordPress version](https://wordpress.org/plugins/otter-blocks/).
- [x] It loads additional script in frontend only if it is required.
- [x] Does not impact the [Core Web Vitals](https://web.dev/vitals/).
- [x] In case of deprecation, old blocks are safely migrated.
- [x] It is usable in Widgets and FSE.
- [x] Copy/Paste is working if the attributes are modified.
- [x] PR is following [the best practices]()

### CODE REVIEW

**Comment by mghenciu** [comment]
Looking good, Robert.

Some things I noticed:

- [ ] the border radius of the Cards is not as the one in Figma, nor consistent with the other cards we have. Please make sure those are consistent.
- [ ] the Learn more/upgrade to Pro, should open in a New Tab - in order to not disturb too much the user flow
- [ ] the Pro pill also needs to be consistent with what we already have in the product. No need to invent a new one
- [ ] let's keep the bounding box to max 930px, as the other pages.
- [ ] in order to make this fit more nicely in this max-width, we can decrease the Block names to 15px
- [ ] also, please change the color of the block names to #3c434a, same for the Icon Color
- [ ] make sure all the icons have the Dark color. Ping me in case you don't have it. [Most of them should be here](https://www.figma.com/file/dLNEZwxPRfh5X906ClqdA0/Otter-Icons?type=design&node-id=452-2761&mode=design&t=WO3rPwuNuVcdOcDy-11).
- [ ] please make sure the Icons are consistent with the one we have in [Figma](https://www.figma.com/file/dLNEZwxPRfh5X906ClqdA0/Otter-Icons?type=design&node-id=217-141&mode=design&t=WO3rPwuNuVcdOcDy-11). For example I see for the Plugin Card, in the build we use something different. In case you don't have a specific Icon, ping me and I'll create one
- [ ] for example this one I made it for the [WooCommerce Comparison Table ](https://www.figma.com/file/dLNEZwxPRfh5X906ClqdA0/Otter-Icons?type=design&node-id=217-1141&mode=design&t=WO3rPwuNuVcdOcDy-11)

**Comment by HardeepAsrani** [comment]
@Soare-Robert-Daniel This doesn't work the other way around. If you disable something in the editor, it still shows up in the settings page.

Also, we don't show it as a menu item in Dashboard menu @mghenciu?

**Review by HardeepAsrani — APPROVED** [review]

**Review by HardeepAsrani — CHANGES_REQUESTED** [review]
Code looks good, just left a comment with questions. Sorry for approving it my mistake.

**Comment by mghenciu** [comment]
> Also, we don't show it as a menu item in Dashboard menu @mghenciu?

**Yes**, @Soare-Robert-Daniel , probably it would make sense to have it as a Menu Item in the Dashboard menu.
Also, I noticed now that there are no Confirmation Toasts when disabling/enabling a block. Before, I think those were present.

**Comment by Soare-Robert-Daniel** [comment]
@HardeepAsrani, I recommend keeping the tab in Settings. Making another page will require some extra work on the PHP side for the registering page and additional CSS.

@mghenciu Yes, it was some notification. I changed the saving system to be more straightforward. I can re-add them if you see them as necessary.

**Comment by mghenciu** [comment]
> Yes, it was some notification. I changed the saving system to be more straightforward. I can re-add them if you see them as necessary.

I think the Confirmation toast is helpful, and we should keep it.

**Comment by Soare-Robert-Daniel** [comment]
> For the separate page, isn't it possible to use something like a link with anchor? Like https://createglove.s2-tastewp.com/wp-admin/admin.php?page=otter#blocks

Yes, we can do a simple URL parsing. Also, we can extends this to other tabs like Integration, feedback, etc.

**Review by HardeepAsrani — APPROVED** [review]
Looks good, we can fix the issues pointed out by Mihai about Toast & use URL params to add Blocks page to the top-level Otter menu.

**Comment by mghenciu** [comment]
Could you please use the same Icon for the WooCommerce Comparison Table block, as the one from Review Comparison Table? @Soare-Robert-Daniel 

to have them consistent.

**Comment by Soare-Robert-Daniel** [comment]
@HardeepAsrani, something like this?

https://github.com/Codeinwp/otter-blocks/assets/17597852/f5403ece-3c3b-4a2f-9b36-ea46af90f426

**Comment by HardeepAsrani** [comment]
@Soare-Robert-Daniel Yes, exactly that. Make sure it only happens when you click on Blocks and not any other item. Then you can put it to QA.

**Comment by HardeepAsrani** [comment]
@Soare-Robert-Daniel We got some feedback from support forum. Can we make sure when you hide AI Block, we also remove the toolbar icon for Content AI from all blocks?

**Comment by irinelenache** [comment]
@Soare-Robert-Daniel Tested and here is what i found:

- [ ] When i go to Otter settings, the **Dashboard** tab doesn't appear as selected https://vertis.d.pr/v/Pu0UTP
- [ ] All blocks appear in a loading state until i go to the editor and disable one of them https://vertis.d.pr/i/XRsHZH 
- [ ] ^ In the same context, clicking on **Disable all** is throwing a console error https://vertis.d.pr/i/AFuMvY
- [ ] **Create form with AI** option is available even if the **AI block** is disabled https://vertis.d.pr/i/kCI0Rx
- [ ] If i use the Otter pro plugin without a license, the pro blocks will be available to enable/disable in the Blocks tab, even if they don't appear in editor inserter or editor Otter settings

**Comment by Soare-Robert-Daniel** [comment]
> * [ ]  All blocks appear in a loading state until i go to the editor and disable one of them https://vertis.d.pr/i/XRsHZH

This depends on the speed of the server to fetch the data.

> * [ ]  ^ In the same context, clicking on **Disable all** is throwing a console error https://vertis.d.pr/i/AFuMvY

The buttons will now be hidden while waiting for the server.

> * [ ]  **Create form with AI** option is available even if the **AI block** is disabled https://vertis.d.pr/i/kCI0Rx

This will stay. The problem with the AI Toolbar is that it might be annoying for some users since it targets core blocks. For this, it is not a case since it is a feature of the Form.

**Comment by irinelenache** [comment]
@Soare-Robert-Daniel Thank you for the fixes and the clarifications 👍 
Regarding this:

>  All blocks appear in a loading state until i go to the editor and disable one of them https://vertis.d.pr/i/XRsHZH
> > This depends on the speed of the server to fetch the data.

On a fresh TasteWP instance i waited several minutes and the loading was still going on, nothing changed until i changed the visibility of one block in the editor. Maybe we can do better in terms of UX, as some users will probably think it's not working

**Comment by irinelenache** [comment]
@Soare-Robert-Daniel Tested and everything's fine now, thank you 🚀

**Pull request merged**
