### PR TITLE
Redo Section Block Controls

### PR DESCRIPTION
**Pull request by HardeepAsrani**

### CODE REVIEW

**Comment by HardeepAsrani** [comment]
We will be making a lot of similar changes with this PR so wanted to make sure things work before we go about doing the entire haul.

Can you @irinelenache do an extensive QA on this change in particular?

We've replaced the Padding/Margin/Border/Border Radius controls in Section Block (only Section, not its Columns so far) with a new Box Control.

This change also replaces the 6-7 different attributes we used to just one.

Here's what you have to test:

- Padding, Margin, Border Width & Border Radius controls work just fine, same with Global defaults & front-end CSS.
- We need to test the backward compatibility of these options too. Make sure in Padding/Margin, you test all the Devices (Desktop/Tablet/Mobile settings) and when they're linked and unlinked. So you make dozens of section with current version of the plugin and then install this version to make sure nothing breaks.

Few things that will break:
- Global Defaults won't have backward compatibility.
- For front-end CSS, if the user uses the current version which has a default of 20px, it won't be transferred to the new version.

Let me know if you have any questions.

**Comment by irinelenache** [comment]
@HardeepAsrani Tested this and found a few things:

- [ ] Clicking the Reset button for the Margin control doesn't work and gives an error in the console https://vertis.d.pr/KS0C2H
- [ ] The border radius control can be a bit unintuitive as it outlines **sides** and not **corners** https://vertis.d.pr/sWHlCv
- [ ] If i make some changes to the Padding and Margin and try to change the view from Desktop to Mobile, the block breaks https://vertis.d.pr/VBijn9

Besides of this, it seems to work fine 👍 
Will have to test with all devices after the last mentioned issue is fixed

**Comment by HardeepAsrani** [comment]
@irinelenache I've fixed the first two issues.

The third one I'm not able to reproduce. Can you try that again?

**Comment by irinelenache** [comment]
@HardeepAsrani The checked issues are fixed, thanks 👍 

For the third one, you can follow the steps from the video on this instance:
```
https://breezy-ostrich.jurassic.ninja
user: demo
password: 8uNXgXLHqRBc
```
If you can't replicate it, maybe it's because of my setup:
MacBook Pro 13-inch, macOS Big Sur Version 11.5.2 / Google Chrome Version 93.0.4577.82 (Official Build) (x86_64)

**Comment by HardeepAsrani** [comment]
Alright @irinelenache, I'll try that. Any other issues apart from these? Specially in coming from an older version of Section to new?

**Comment by irinelenache** [comment]
@HardeepAsrani Didn't find any other issues 👍

**Comment by HardeepAsrani** [comment]
Things that we changed:

- Padding/Margin/Border Width & Radius in Section & its Columns
- Background Image & Background Position in Section & its Columns, in Section also the Background Overlay Image & Position
- Removed Columns Gap in Section

Can you do the test to make sure nothing breaks here when coming from an old version while making sure that the new version works as expected? @irinelenache 

Also, the zip file won't be automatically generated because of merge conflicts, you will have to run npm install && composer install && npm run build yourself.

Let me know how it goes or if you have any questions. Thank you!

**Comment by irinelenache** [comment]
@HardeepAsrani Found something strange:

I created a post that looked like [this](https://vertis.d.pr/SI7KVe) with the latest version of Otter, then updated to this PR. I updated the post without making any change and everything was working in frontend until i clicked on **Edit post** again. The editor wasn't loading and i got [these errors](https://vertis.d.pr/IgXbRK) in console.

**Comment by HardeepAsrani** [comment]
@irinelenache Can you try to recreate it on tastewp and share the credentials on Slack?

**Comment by irinelenache** [comment]
@HardeepAsrani Tried replicating it again with the build you sent on Slack but now it worked as expected. Maybe it was a one time error. Will ping you if i encounter it again 👍

**Comment by HardeepAsrani** [comment]
Alright @irinelenache - let me know if you find anything else or if it's good to merge.

**Comment by irinelenache** [comment]
@HardeepAsrani For me it's good to merge 👍

**Comment by HardeepAsrani** [comment]
Thanks @irinelenache - I hope you also tested it with WP 5.6 and 5.7 to make sure this is backward compatible?

**Comment by irinelenache** [comment]
@HardeepAsrani Did a short testing with older wp versions and didn't find any problem, you can check it too to be sure about special behaviours

**Comment by HardeepAsrani** [comment]
Waiting for a headsup from @Soare-Robert-Daniel here so we can move forward. Let me know if you find anything here.

**Comment by Soare-Robert-Daniel** [comment]
@HardeepAsrani, got no problem with the new UI for border, margin, padding.

However, found some issues with migrated block. They give an error like 
image

The `depreacted.js` might be incorrect.

**Comment by HardeepAsrani** [comment]
@Soare-Robert-Daniel Should be fine, `object` should've been in quotes. Should be fixed now. Can you make sure the error isn't there anymore?

**Comment by Soare-Robert-Daniel** [comment]
@HardeepAsrani, the problem with deprecation has been solved 👍 .

If we do a refactor, I think we can look at the toolbar. It has some deprecation notices. 
image

Also, you have this problem when using section in `widgets`:
```html
<pre style="color: #e20c0c;margin:0;margin-top:-35px;"><br>
<b>Notice</b>:  wp_enqueue_script() was called <strong>incorrectly</strong>. "wp-editor" script should not be enqueued together with the new widgets editor (wp-edit-widgets or wp-customize-widgets). Please see <a href="https://wordpress.org/support/article/debugging-in-wordpress/">Debugging in WordPress</a> for more information. (This message was added in version 5.8.0.) in <b>/lookable/wordpress/wp-includes/functions.php</b> on line <b>5663</b><br>
</pre>
```

**Comment by HardeepAsrani** [comment]
@Soare-Robert-Daniel It's already fixed in v2.

**Pull request merged**
