### PR TITLE
Version 2.2.3

### PR DESCRIPTION
**Pull request by HardeepAsrani**
### Summary

- https://github.com/Codeinwp/otter-blocks/issues/1396
- https://github.com/Codeinwp/otter-blocks/issues/1489
- https://github.com/Codeinwp/otter-blocks/issues/1439
- https://github.com/Codeinwp/otter-blocks/issues/1485 (Update FontAwesome)
- https://github.com/Codeinwp/otter-blocks/issues/629
- https://github.com/Codeinwp/otter-blocks/issues/1429
- https://github.com/Codeinwp/otter-blocks/issues/1488
- https://github.com/Codeinwp/otter-blocks/issues/1465
- https://github.com/Codeinwp/otter-blocks/issues/1511
- https://github.com/Codeinwp/otter-blocks/issues/795
- https://github.com/Codeinwp/otter-blocks/issues/1515
- https://github.com/Codeinwp/otter-blocks/issues/1510
- https://github.com/Codeinwp/otter-blocks/issues/1491
- https://github.com/Codeinwp/otter-blocks/issues/1507
- https://github.com/Codeinwp/otter-blocks/issues/1508

----

### Test instructions

This can be tested for a final pre-release QA. The changes have also been deployed on: https://staging.demosites.io/

---- 

### Checklist before the final review

- [x] Visual elements are not affected by independent changes.
- [x] It is at least compatible with the [minimum WordPress version](https://wordpress.org/plugins/otter-blocks/).
- [x] It loads additional script in frontend only if it is required.
- [x] Does not impact the [Core Web Vitals](https://web.dev/vitals/).
- [x] In case of deprecation, old blocks are safely migrated.
- [x] It is usable in Widgets and FSE.
- [x] Copy/Paste is working if the attributes are modified.

### CODE REVIEW

**Comment by irinelenache** [comment]
@HardeepAsrani Tested the release builds and here is what i found so far:

- [ ] The buttons font size changed from [this](https://vertis.d.pr/i/aErW1b) to [this](https://vertis.d.pr/i/A46Bfh), on the NFT Illustrator demo
- [ ] The advanced heading lost their bottom padding and changed from [this](https://vertis.d.pr/i/rTuhY7) to [this](https://vertis.d.pr/i/AexRKd)
- [ ] The icons have a bottom margin on Real estate agency demo, changed from [this](https://vertis.d.pr/i/yQhvUr) to [this](https://vertis.d.pr/i/lcEC7Y)
- [ ] The icon size in the Icon list block is changing alongside with the font size, but it has no effect in editor or frontend until i do any changes to it also https://vertis.d.pr/v/BO1d4s
- [ ] When creating nested accordions, the top border is missing for the first nested accordion item https://vertis.d.pr/i/odxm67

**Comment by Soare-Robert-Daniel** [comment]
> * [ ]  The advanced heading lost their bottom padding and changed from [this](https://vertis.d.pr/i/rTuhY7) to [this](https://vertis.d.pr/i/AexRKd)
> * [ ]  The icons have a bottom margin on Real estate agency demo, changed from [this](https://vertis.d.pr/i/yQhvUr) to [this](https://vertis.d.pr/i/lcEC7Y)

@irinelenache, do you still have the instance test 🙏  ? I could not reproduce those issues.

**Comment by HardeepAsrani** [comment]
@Soare-Robert-Daniel https://staging.demosites.io/real-estate-agency-gb/ https://demosites.io/real-estate-agency-gb/

Those are demo sites, you can see there.

You can also see if they're related to this:
- https://github.com/Codeinwp/otter-blocks/issues/1402
- https://github.com/Codeinwp/otter-blocks/issues/1038

These were bugs previously that we fixed.

**Comment by HardeepAsrani** [comment]
I've also merged a couple of small PRs that already went through QA and shouldn't affect much.

**Comment by Soare-Robert-Daniel** [comment]
The NFT and Real Estate on stagging are outdated. The Icon block Real Estate still uses the deprecated tag `p`, which adds a `margin-bottom`. The NFT needs a style regeneration. Its CSS for Adv Headin is outdated.

When importing, the problem is not visible since their update themself (that's why I could not reproduce them) or when they are viewed on https://demosites.io/nft-illustrator-gb/about/ 

This is just an internal problem. No problem for users 👌

**Comment by irinelenache** [comment]
@HardeepAsrani Tested again and everything's fine on my end, didn't find any more problems 👍

**Pull request merged**
