### PR TITLE
Plugin Count for Text

### LINKED ISSUE #558: Count Block or Counting/Typed Headline
This can appear in the Animations Panel of Heading/Advance Heading, Quote & Paragraph blocks. The typing part is easier but the Count animation should only appear work on numbers.

We can redesign how the Animation tab looks so users can choose between these two + the existing loading animations, and then select what they want.

We can also use Format, if needed, to allow user to select only specific numbers in a headline to animate: https://developer.wordpress.org/block-editor/how-to-guides/format-api/1-register-format/

### PR DESCRIPTION
**Pull request by Soare-Robert-Daniel**
Close #558

### CODE REVIEW

**Comment by Soare-Robert-Daniel** [comment]
## Testing

This plugin acts as an addon for Paragraph and Advance Heading Block, and is a part of the *Animation* module.

Insert a number, select it, add the option via the dropdown menu.

:warning: This is working with text that contains numbers from `0-9`, `-`, `+`, `%`, `$`, `€`, `,`, `.`.

E.g.:

- 1230
- 100.23
- +34
- +45.49
- 100%
- 9.99$
- -10%

image


#### Options

The options appear in the Animation tab. The name of the animation must be `Count Numbers`. You can select the Delay and the Speed.

#### Checking the tag

After activating the option, you need to check the tag `<o-anim-count>`  in the code editor.

E.g.:


```html
<p class="animated o-count"><o-anim-count>120.000</o-anim-count></p>
```

They also must be present in the frontend.

image

**Comment by irinelenache** [comment]
@Soare-Robert-Daniel Nice work 🚀 Tested the feature and found a few things:

- [ ] The counted text has some **underline** in frontend https://vertis.d.pr/CYqdhp , both for Advanced heading and simple Paragraph
- [ ] With **Delay** activated, the initial number before the animation starts is not 0, and that's a bit confusing https://vertis.d.pr/DioHZh
- [ ] When the number is something like **1.0009** , the 0 is not visible while counting https://vertis.d.pr/gJRDzp
- [ ] The animation doesn't work with a **small number** (16 was the minimum that was working without decimals)

**Comment by Soare-Robert-Daniel** [comment]
> * [x]  The counted text has some **underline** in frontend https://vertis.d.pr/CYqdhp , both for Advanced heading and simple 

This was a visual indicator to see that is selected.

Now is working for small numbers, and when the delay is present the number will show 0.

**Comment by irinelenache** [comment]
@Soare-Robert-Daniel 

>  When the number is something like 1.0009 , the 0 is not visible while counting https://vertis.d.pr/gJRDzp

^ This one is still happening https://vertis.d.pr/tlEQKT

Rest of the issues are fixed, thank you 👍

**Comment by Soare-Robert-Daniel** [comment]
> > When the number is something like 1.0009 , the 0 is not visible while counting https://vertis.d.pr/gJRDzp
> 
> ^ This one is still happening https://vertis.d.pr/tlEQKT

By 0, do you mean to see the number 0 at the beginning? If yes, I do not see it necessary.

**Comment by irinelenache** [comment]
@Soare-Robert-Daniel For the example i provided (1.0009) it looks confusing when the number that's increasing is ... 9997, 9998, 9999 and then 1.0000 ...

**Comment by Soare-Robert-Daniel** [comment]
> @Soare-Robert-Daniel For the example i provided (1.0009) it looks confusing when the number that's increasing is ... 9997, 9998, 9999 and then 1.0000 ...

Very odd. For me is working. Can you check if this is working for you:

```html
<!-- wp:paragraph -->
<p><o-anim-count>1.0009</o-anim-count></p>
<!-- /wp:paragraph -->
```

**Comment by irinelenache** [comment]
@Soare-Robert-Daniel Tested again and it works when `. (dot)` is used for decimals 👍 . It should be noted that when someone wants to animate a big number, a billion for example, he should use commas in order to make the number easier to read. If he uses dots, it will work like this https://vertis.d.pr/cQrBVH

**Comment by Soare-Robert-Daniel** [comment]
We use the American notation. Dot as delimiter for big numbers is not valid.

**Review by HardeepAsrani — DISMISSED** [review]
@Soare-Robert-Daniel I've left the review here: https://www.loom.com/share/cac5ddc2787e48ec8e6a900cef3fbec2

To put it in text,

- Change the Format button name.
- Make sure user can't apply it if the value isn't a valid number format.
- Improve the UI (more details in the video)


Functionality-wise, it's pretty neat and does the job perfectly. Good job!

PS: Remove the empty scss file & console log from the code.

**Comment by Soare-Robert-Daniel** [comment]
> * Change the Format button name.

What do you mean exactly?

> * Make sure user can't apply it if the value isn't a valid number format.

I had this in some commit but I removed it. Suppose that you have a number like this `1000`. If you put a non-format character and become like this `10a00`, you no longer have the option to remove the count animation `tag` on the whole thing. Or if you delete the number and so you have an empty tag like `<o-anim-count> </o-anim-count>`, and you write some text in this without knowing about the tag.

The problem is that I do not know a better and simple system to know about the tag and remove it anytime. You could say that we can do this by changing the animation in the Animation panel, I think is possible but I want to do it when we revamp that thing.

> * Improve the UI (more details in the video)

This will be a separate topic and should not be included in this PR. We need to rethink the whole module, especially with the support for custom formats to place animations. Let's keep the custom format and animation separate and more independently until we have a plan for a more robust and flexible implementation.

**Comment by HardeepAsrani** [comment]
@Soare-Robert-Daniel 

1. & 2. I have made some changes for that: https://www.loom.com/share/214685d52aec41c8b502622f0d252577 - is there any issues apart from the one I mentioned in the video by this change?

3. The current UI is pretty sucky and it's impossible to even know that this feature exist unless you are already aware of it. Animations and Count will stay separate, just a better UI so people know that they can use it. It is fine, I'll take care of it and see what I can come up with.

**Comment by HardeepAsrani** [comment]
@Soare-Robert-Daniel Let me know your thoughts: https://www.loom.com/share/9056f37ebfc541c082c2a30262928767

**Pull request merged**
