### PR TITLE
Better placeholders for content blocks

### LINKED ISSUE #1439: Better Onboarding & Placeholders for Content Blocks
### Description:

As Ionut pointed out in his feedback: https://www.loom.com/share/c7da93d212434ac8985ac1846581762c, we can have better placeholders and defaults for our content blocks.

Moving from here: https://github.com/Codeinwp/otter-internals/issues/60

### PR DESCRIPTION
**Pull request by arinaturcu**
Closes #1439.

### Summary

- Changes default content in **Accordion**, **Icon List** and **Flip** blocks.
- Adds a custom appender button for the accordion.
- Changed the default style of the Accordion block to `Boxed`
### Screenshots 
Screenshot 2023-02-06 at 23 13 39

----

### Test instructions

- For the Accordion and Icon list, the content is set as actual text, and for the Flip card, the new content is just a placeholder.
- When adding an Accordion, the default set style should be the `Boxed` one.
- When adding a new Accordion item or a new Icon list item, the title of the element should be set depending on the number of existing elements: if there ar 2 existing item, the third one will be named by default `Accordion item 3` or `List tem 3`

---- 

### Checklist before the final review

- [x] Visual elements are not affected by independent changes.
- [x] It is at least compatible with the [minimum WordPress version](https://wordpress.org/plugins/otter-blocks/).
- [x] It loads additional script in frontend only if it is required.
- [x] Does not impact the [Core Web Vitals](https://web.dev/vitals/).
- [x] In case of deprecation, old blocks are safely migrated.
- [x] It is usable in Widgets and FSE.
- [x] Copy/Paste is working if the attributes are modified.

### CODE REVIEW

**Review by HardeepAsrani — CHANGES_REQUESTED** [review]
Screenshot 2023-02-02 at 4 03 25 PM

- Accordion looks very simple here, I thought we were going for a bolder look: https://github.com/Codeinwp/otter-blocks/issues/1439#issuecomment-1383963095

- In Accordion, we can perhaps only display Add Accordion Item button when the Block is selected.

- In Flip, we should perhaps use Placeholders instead of actual text. If I make a Flip with just title and no description, upon updating to this branch, it automatically adds the description.

Screenshot 2023-02-02 at 4 05 07 PM

@Codeinwp/design-team let me know if you have any additional feedback.

**Comment by mghenciu** [comment]
> https://github.com/orgs/Codeinwp/teams/design-team let me know if you have any additional feedback.

As discussed also with @Soare-Robert-Daniel , the button should be more subtle - for example like the one from the Accordion + Text.

**Comment by arinaturcu** [comment]
> - Accordion looks very simple here, I thought we were going for a bolder look: https://github.com/Codeinwp/otter-blocks/issues/1439#issuecomment-1383963095

@HardeepAsrani That is the default style of the block. Should we make the `Boxed` style the default one?

**Comment by mghenciu** [comment]
I think we talked about this at some point, and decided to use the line style.
But looking on it after some time, I think Accordion looks better with the Boxed Style (compared to the Tabs blocks).

Sorry for the inconvenience Arina.

**Comment by arinaturcu** [comment]
Thanks for the feedback! 🚀 
I tackled the things @HardeepAsrani  mentioned and made the appender button more subtle.

**Review by HardeepAsrani — APPROVED** [review]

**Comment by irinelenache** [comment]
@arinaturcu Tested the enhancements and everything's fine here, thank you 🚀

**Pull request merged**
