### PR TITLE
Fix Otter Blocks crashing on Widgets

### LINKED ISSUE #626: Weird errors on Widget Screen
Robert & I found some errors on the Widgets screen with Otter blocks which are not consistent. Sometimes they happen, sometimes they don't. We need @irinelenache your QA eyes to help us find what actions are causing these errors and how to reproduce them consistently.

Here are a few ways that we get an error:

- Add a Section block to the widget page. Click on it. Press the Delete button on your Mac (or Backspace in Windows) and you see an error in the console. Make sure Section is still in placeholder with no layout selected.
- Add a Section block, select all the widgets, and press delete. The entire page breaks down then but it is no consistent.

It will be good to find out:

- What errors are appearing and how to reproduce them?
- If they are from Otter or you can also reproduce them with Otter?
- And if they're from Otter, can you reproduce them with blocks other than Section too?
- And if you find a pattern, does it happen on post editor too?

You can test them with the latest Otter from WordPress.org.

### PR DESCRIPTION
**Pull request by Soare-Robert-Daniel**
Fix #626

### CODE REVIEW

**Comment by irinelenache** [comment]
@HardeepAsrani @Soare-Robert-Daniel Tested this PR and managed to replicate the issue again:

- [ ] You have to add an accordion block, add some content to it and delete it by using backspace, when only Accordion item is selected in editor. I made a small video with it: https://www.loom.com/share/b7030d845e92409482112989e3463057
- [ ] When i have the Leaflet map added to a post, i get an error in frontend
```
Uncaught ReferenceError: L is not defined
    at leaflet-gesture-handling.min.js?ver=1.7.0:1
```
, also, when i add the block in editor, i get this notice 
```
Mixed Content: The page at '<URL>' was loaded over HTTPS, but requested an insecure element '<URL>'. This request was automatically upgraded to HTTPS, For more information see <URL>
```

**Comment by HardeepAsrani** [comment]
@irinelenache 

1. Neither I nor Robert was able to reproduce this. Can you try to reproduce it somewhere online and send us creds?
2. @Soare-Robert-Daniel Can you check if it has to do something with Async/defer?
3. That's fine, we don't have to worry much about it.

**Comment by irinelenache** [comment]
@HardeepAsrani I found the exact steps to reproduce it:
1. Create a post that contains an accordion (I used **Test title / Test content** as data)
2. Open the post in front-end
3. Open another edit window by clicking here https://vertis.d.pr/XH55UI
4. Click on the block and press backspace

You can check it here:
```
https://damagescience.tastewp.com/2021/11/23/test-error/
user: irinel
password: ShNBz5Hsl9I
```

**Comment by HardeepAsrani** [comment]
@irinelenache Thanks, I can reproduce it now.

**Comment by HardeepAsrani** [comment]
@irinelenache It seems to be an issue with Gutenberg. I can reproduce this in new WP instance without Otter too.

**Pull request merged**
