### PR TITLE
Fix Tabs scoping

### LINKED ISSUE #696: Issue with the Tabs Block
When we use tabs under a tab, the content of all tabs appears under the first tab. 

Markup 2022-01-31 at 19 51 03

1. Create a page and add Tab Block
2. Add atleast 2 tabs
3. Under the content of 1st tab add another Tab Block
4. Now add 2 or 3 tabs here.
5. Check the preview of the page.

However, only the first tab content should appear after loading the page in browser.

Test Instance: https://shadebird.tastewp.com/tab-test/
user: Poonam
pass: AKMtcIEz_0k

HS Ticket: https://secure.helpscout.net/conversation/1772945324/308118/

### PR DESCRIPTION
**Pull request by Soare-Robert-Daniel**
Fix #696

### CODE REVIEW

**Comment by HardeepAsrani** [comment]
@irinelenache Can you test? Thank you!

**Comment by irinelenache** [comment]
@HardeepAsrani @Soare-Robert-Daniel Tested and the issue is fixed on the frontend side.
In editor, the tabs block will look like this https://vertis.d.pr/zEm02B

**Comment by HardeepAsrani** [comment]
@Soare-Robert-Daniel Might be worth checking if that is due to the new PR that we merged. If you have trouble generating the CSS files with `npm start`, run `rm -rf build` before `npm start`

**Comment by HardeepAsrani** [comment]
@Soare-Robert-Daniel nevermind, forgot this was against the development, not v2.

**Comment by irinelenache** [comment]
@Soare-Robert-Daniel The issue is fixed now, thanks 🚀

**Pull request merged**
