### PR TITLE
Fix zero padding/margin not migrating

### PR DESCRIPTION
**Pull request by HardeepAsrani**
Can you check @mghenciu if the issue is still there with this?

### CODE REVIEW

**Comment by mghenciu** [comment]
Can't test the above **Dev build**, as I get an error when trying to import a Starter Site from TPC.
Tried twice and same thing happened.
image

**Comment by HardeepAsrani** [comment]
@mghenciu I think that's to do with the name of the `otter-blocks-dev` folder name. Plugin tries to install otter-blocks again as the name of the dev build is different. I will fix that but for now you can just unzip the folder and rename it to `otter-blocks`

**Comment by HardeepAsrani** [comment]
@mghenciu You can avoid the test for now, don't think it fully fixes the issue.

**Comment by HardeepAsrani** [comment]
@mghenciu Can you help me in testing this?

Here's how to test. First of all, do this test on two sites. This branch versus current version of Otter from WordPress.org.

- Import a template and compare how it looks after the import with the one on demosites.io and see if it looks the same or there are any changes. And we can compare between this branch versus 2.0
- After that, edit the page and press update button so that JS deprecation takes place and then publish and do the comparison again.

You can try it with few templates to see how it looks.

Make sure to rename the otter-blocks-dev to otter-blocks so it works properly.

Let me know if it works better than before.

**Comment by mghenciu** [comment]
### Import without doing anything else ✅
Looks good on the Left side (this build), and not good with the old release (margins present) on the Right side.
Screenshot 2022-03-21 at 09 12 07
___
### After Editing the page ✅
image

___
I tried with multiple demos, and it looks good:
https://originatetrain.s2-tastewp.com/ ✅ 
https://extendharbor.s1-tastewp.com/ 🟥 
___
https://otter-new-build.us.instawp.xyz/ ✅ 
https://otter-old-build.us.instawp.xyz/ 🟥

**Comment by HardeepAsrani** [comment]
Props to @wags1128 for reporting & helping in fixing this.

**Pull request merged**
