### PR TITLE
TESTING: DO NOT MERGE!

### PR DESCRIPTION
**Pull request by HardeepAsrani**

### CODE REVIEW

**Comment by irinelenache** [comment]
@HardeepAsrani Compared this PR with the stable version and the slowness is still visible, mostly after keeping the editor open for some time. You can see how the editor performs when you try to delete some text by holding `backspace`

**Comment by HardeepAsrani** [comment]
@irinelenache was there a visible difference or it's pretty much the same?

**Comment by irinelenache** [comment]
@HardeepAsrani Yes the difference is visible but it will still get slow eventually depending on the time the editor stays open, so there is still a memory leak somewhere 😢

**Comment by HardeepAsrani** [comment]
Thanks, closing it then!

**Pull request closed without merging**
