### PR TITLE
Switch to using block.json format

### PR DESCRIPTION
**Pull request by HardeepAsrani**
We changed the blocks to work using block.json API instead of the initial API. This now splits the CSS files for the blocks and enqueue them independently. This makes a major process in the build process and hopefully, it shouldn't cause many issues.

This PR also removes the Resizer from Section as it was never good but has become even worse since 5.9.

Closes: https://github.com/Codeinwp/otter-blocks/issues/532

### CODE REVIEW

**Comment by HardeepAsrani** [comment]
@irinelenache @Soare-Robert-Daniel Once you've time, can you both test this to make sure nothing breaks and all blocks work as expected?

Robert, can you also make sure the build process works properly for you?

**Comment by irinelenache** [comment]
@HardeepAsrani Tested and found something:

- [ ] After importing Shop starter site, i got some errors on the Home page, and elements don't look as before https://vertis.d.pr/dp2aTh
- [ ] Images don't work for the Product review, neither when is synced with Woocommerce or manually created https://vertis.d.pr/xqkpLH

**Comment by HardeepAsrani** [comment]
Thanks @irinelenache, rest works okay?

**Comment by irinelenache** [comment]
@HardeepAsrani Those are the only problems that i found, maybe @Soare-Robert-Daniel can have a different approach and find something more 🤞

**Comment by Soare-Robert-Daniel** [comment]
Blocks seem to work fine in the new editor, no crashes when inserting.

**Comment by HardeepAsrani** [comment]
@irinelenache Can you check now?

**Comment by irinelenache** [comment]
@HardeepAsrani Tested again and the issues are fixed, thanks 🚀

**Comment by HardeepAsrani** [comment]
Thanks @irinelenache, merging this and hoping it won't break everything. :)

**Pull request merged**
