### PR TITLE
Add Font preview

### LINKED ISSUE #1488: Font preview in Advanced Heading
### Description:
When changing the font family of the advanced heading, there are many options, and if I select one ( without knowing how it looks ) and I don't like it, I have to search again, select another font, then repeat until I find the suitable one.

Can we have something like a preview when hovering over an option?
image

### Alternatives:
Keep it as it is.

### PR DESCRIPTION
**Pull request by Soare-Robert-Daniel**
Closes #1488 .

### Summary

Add Font preview for Font Family Select component.

### Screenshots 

https://user-images.githubusercontent.com/17597852/219354379-ee8ec68b-7063-4d8b-8807-7074d5c4ec6b.mp4

----

### Test instructions

ℹ️ Since it uses the Google API for optimized fonts, some browser settings and extensions block the request. If the browser which you are testing is aggressively blocking Google API, you will see in the console errors like `ERR_BLOCKED_BY_CLIENT` 

ℹ️ Making the request takes time; each font loading has 2 requests. It might be faster or slower, depending on your internet speed and CPU. Check the video to see the effect.

ℹ️ First time, it will look slow, but after, the browser will cache the request so that the next time it will be much faster. This happens only if you don't disable the cache.

ℹ️ Not all fonts will be available; depending on the server setup, you will see errors about CORS policy.

ℹ️ Make sure to publish the page if you want to see the font in Frontend.

---- 

### Checklist before the final review

- [ ] Visual elements are not affected by independent changes.
- [ ] It is at least compatible with the [minimum WordPress version](https://wordpress.org/plugins/otter-blocks/).
- [ ] It loads additional script in frontend only if it is required.
- [ ] Does not impact the [Core Web Vitals](https://web.dev/vitals/).
- [ ] In case of deprecation, old blocks are safely migrated.
- [ ] It is usable in Widgets and FSE.
- [ ] Copy/Paste is working if the attributes are modified.

### CODE REVIEW

**Review by HardeepAsrani — CHANGES_REQUESTED** [review]
Some fonts don't seem to load or work: https://www.loom.com/share/257c77dde1e34d53aefb1ecf26421f32

This being one of the examples: https://fonts.google.com/noto/specimen/Noto+Sans+Anatolian+Hieroglyphs

Also, even if all the fonts have loaded once, if I scroll back and forth, it tries to load them again. Can't we not load things again on each time the select is opened?

**Comment by Soare-Robert-Daniel** [comment]
> This is one of the examples: https://fonts.google.com/noto/specimen/Noto+Sans+Anatolian+Hieroglyphs

This is a misunderstanding where the text needs to be hieroglyphs. This font does not translate A-Z to the hieroglyphs. The hieroglyphs are their own Unicode: https://symbl.cc/en/14506/

Also, in Google Fonts, if you preview the text, you get the following: 

image

In our editor, if you select that font and insert those unicode codes, they will blend nicely with the text:

image

If I select another font, like Abel, they don't show up:

image

---

For some unknown reason, the hook that loads the fonts in the frontend is activated before the function that collects the font from the block.

The hook: https://github.com/Codeinwp/otter-blocks/blob/d66fc8818130fd4872df2e97629584bbe016e4a5/inc/css/class-block-frontend.php#L56

The Adv Font Collector: https://github.com/Codeinwp/otter-blocks/blob/d66fc8818130fd4872df2e97629584bbe016e4a5/inc/css/blocks/class-advanced-heading-css.php#L34-L37

@HardeepAsrani, Have you made some changes with the hooks?

**Review by HardeepAsrani — APPROVED** [review]

**Comment by irinelenache** [comment]
@Soare-Robert-Daniel Tested and the feature seems to work fine, found only a strange edge case, let me know if you can reproduce it:

- [ ] When i open the font selector and scroll a few times up and down, there will be a scrollbar that appears and disappears until i close the selector https://vertis.d.pr/v/0Uxtmz

**Comment by Soare-Robert-Daniel** [comment]
> * [ ]  When i open the font selector and scroll a few times up and down, there will be a scrollbar that appears and disappears until i close the selector https://vertis.d.pr/v/0Uxtmz

Opening the popup sometime create extra space in Sidebar and activate the scroll in Sidebar in janky way. It is a common issue from that Core component to sometime behave like that.

**Comment by HardeepAsrani** [comment]
@irinelenache Yes, it's fine, that sometimes can happen in this component in certain conditions but it's not a blocker. We can merge it.

**Pull request merged**
