### PR TITLE
Experimental: Dynamic Values

### PR DESCRIPTION
**Pull request by HardeepAsrani**
Details: https://github.com/Codeinwp/otter-internals/issues/19

You can use % in the editor or the Control on text to add a dynamic value. Some values are part of Pro while some are available for free users as well.

The video is old but it should give you an idea on how to use the extension: https://www.loom.com/share/3aaf5dad554646319761822fc2353fc5

### CODE REVIEW

**Comment by HardeepAsrani** [comment]
@selul Here, we will have to run few regex calls for search and replace. Would it be a good idea to save the regex matches into post meta or transient so we don't do it on each load?

**Comment by selul** [comment]
@HardeepAsrani can you share a sample of a possible match and how it will look like, or the regex101 link which you tested on.

Also, any idea why you don't use preg_replace instead?, you can get some inspiration from the magic tags feature in Neve https://github.com/Codeinwp/neve/blob/master/header-footer-grid/Core/Magic_Tags.php#L88

**Comment by HardeepAsrani** [comment]
Thanks, @selul, that has made the function very slim: https://github.com/Codeinwp/otter-blocks/pull/860/files#diff-43d66124ff671f88a1a72d40f2263094a21aded4e2a3c472b0174260d441794aR36-R44

**Comment by selul** [comment]
@HardeepAsrani looks good, I don't see the regex as being slow so no need for caching on this fmho.

**Comment by HardeepAsrani** [comment]
@selul @mghenciu Here is a list of dynamic content that I've thought of adding:

- Post ID
- Post Title
- Post Excerpt
- Post Date
- Post Time
- Post Terms
- Post Custom Field
---
- Site Title
- Site Tagline
---
- Logged-in user Name
- Logged-in user Description
- Logged-in user Meta
---
- Author-in user Name
- Author-in user Description
- Author-in user Meta
---

Let me know if you want to add/remove anything. I'm expecting this to be mostly used on Blog/Pages, not Products of LearnDash so that's why didn't think of adding that so far. Also, none of these require an ID (as post content is inside the loop, of course, will need to test with FSE too).

Let me know your thoughts. (So far I've implemented all but 2 items from the Posts list, so this feature shouldn't take more than a day worth of work to finish).

**Comment by irinelenache** [comment]
@HardeepAsrani Nice job 🚀  Tested and here are my findings:

- [ ] The **text options** (bold, italic, etc..) don't work in frontend
editor: https://vertis.d.pr/OeWrXY
frontend: https://vertis.d.pr/TxBPhN

- [ ] The **dynamic value modal** opens only in a place in editor, no matter where is the selected dynamic value https://vertis.d.pr/ZOde6u
- [ ] If i select some text and assign it a dynamic value, i **can't unassign it** by clicking again on the setting because it's disabled https://vertis.d.pr/FiFDxu
- [ ] I'd expect the dynamic value setting to be disabled if i just click on a word and don't select any text https://vertis.d.pr/vUovdc
- [ ] If i add a custom field with a longer name, the input field goes multiline because the text cursor is still there (also gives the impression that i can type something else) https://vertis.d.pr/jhluSg
- [ ] With Otter pro installed, when i hit `%` , not all the dynamic values will be visible in the dropdown. If i select one of the visible ones and change it in the modal, **the value in the editor won't change** (in frontend it works fine) https://vertis.d.pr/rk4xOT
- [ ] When i try to add custom fields using **ACF**, the dropdown will contain the **field ids** https://vertis.d.pr/gQb5tR (I'd expect to see the field name/field label)
- [ ] The custom fields added with **ACF** are not visible in frontend (both with default values or changed values)
editor: https://vertis.d.pr/ADS0WW
frontend: https://vertis.d.pr/1yAGos

**Comment by HardeepAsrani** [comment]
@irinelenache 

> The text options (bold, italic, etc..) don't work in frontend

That really depends on how you add it. If you add around the dynamic value then it will work, if you add it inside then it won't. We can't really do anything here.

>  The dynamic value modal opens only in a place in editor, no matter where is the selected dynamic value https://vertis.d.pr/ZOde6u

Should be fixed now.

>  If i select some text and assign it a dynamic value, i can't unassign it by clicking again on the setting because it's disabled https://vertis.d.pr/FiFDxu

Should be fixed now. The popup that opens will have the option to delete the format.

Updating this comment as I test other findings.

**Comment by HardeepAsrani** [comment]
@irinelenache 

> The text options (bold, italic, etc..) don't work in frontend

That really depends on how you add it. If you add around the dynamic value then it will work, if you add it inside then it won't. We can't really do anything here.

>  The dynamic value modal opens only in a place in editor, no matter where is the selected dynamic value https://vertis.d.pr/ZOde6u

Should be fixed now.

>  If i select some text and assign it a dynamic value, i can't unassign it by clicking again on the setting because it's disabled https://vertis.d.pr/FiFDxu

Should be fixed now. The popup that opens will have the option to delete the format.

Updating this comment as I test other findings.

**Comment by irinelenache** [comment]
@HardeepAsrani Checked the fixed issues and they work fine 🚀 

Only one question: Do we plan to make the dynamic values work in the sidebar too? I tried to add them and they don't work neither in single post or archive

**Comment by HardeepAsrani** [comment]
@irinelenache Good point, didn't think of that. Thanks for keeping that in mind.

**Comment by HardeepAsrani** [comment]
@irinelenache I've updated it with FSE & Widgets compatibility. Make sure to test on both, thanks!

**Comment by HardeepAsrani** [comment]
@mghenciu Also it's early so we can also replace `%` with some other prefix. I just took it for the prototype. We can replace it with whatever prefix we desire, like `-o` or something other.

**Comment by HardeepAsrani** [comment]
@irinelenache I've also re-added ACF support, this time with just a dropdown.

**Comment by mghenciu** [comment]
@HardeepAsrani , I think it's ok without the modal, as long as we have some kind of visual hint that those are from Otter, and they can be unlocked with Otter Pro. Probably the title tag should be fine, if doable.

___
As for the **%**, as you mentioned the main flow will be to add dynamic values from the Toolbar. **And to be honest **%** already looks more familiar, easy to use, compared to having multiple characters**, like _-o_; 
or something more developer oriented like { post_title }, I think it's also a bit hard for users.

**So I would stick to one symbol**, of course one that doesn't conflicts with other things in the WP gutenberg space.
It can be %, $, or # (like git does it).

**Comment by HardeepAsrani** [comment]
@irinelenache Thank you. I've fixed it. I'll merge this now.

**Pull request merged**
