### PR TITLE
fix: wrong word-break was not working for text without spaces

### PR DESCRIPTION
**Pull request by UVLabs**
When `word-break: keep-all` is used it doesn't respect breaks in the flow of text for languages such as Chinese and Japanese.

This causes the text to "overflow" off the page:

image

As per MDN for `keep-all` value:

> Word breaks should not be used for Chinese/Japanese/Korean (CJK) text. Non-CJK text behavior is the same as for normal.

https://developer.mozilla.org/en-US/docs/Web/CSS/word-break

Expected behavior introduced by this pull:

image

This was reported in Neve but this block is by Otter https://github.com/Codeinwp/neve-pro-addon/issues/1933

### CODE REVIEW

**Comment by UVLabs** [comment]
@HardeepAsrani I made the changes here so they only apply for the affected languages

**Comment by irinelenache** [comment]
@UVLabs Tested and this is how a section with 3 columns looks with this PR:

image

Here is the instance:
 ```
Admin area URL: https://weakvalue.s3-tastewp.com/wp-admin 
 Username: irinel 
 Password: uWpP7UJtcVA 
```

Please let me know if it's a bug or i didn't exactly understand the issue 🙏

**Comment by UVLabs** [comment]
@irinelenache Sorry a change was made in the latest commit to make this patch only apply when the site lang is either Chinese, Japanese or Korean

So you'd have to change your site language to one of those languages in the WP general settings. This is how Japanese looks in Japanese(the one after italiano):

image

**Comment by irinelenache** [comment]
@UVLabs Tested again and the issue is fixed, thanks for explaining 🚀

**Pull request merged**
