### PR TITLE
Add Flip Block

### LINKED ISSUE #535: Flip Block
@JohnPixle, @mghenciu, can you recommend some resources for this type of block?

I have done some testing, and the option to append any blocks on both sides is not viable. The prototype works the same as this [one](https://www.w3schools.com/howto/howto_css_flip_card.asp).

I can make one side to have blocks insertion for complete editing, but the other must be standard (like the one from Neve Pro where you need to use that text editor to add content | or just an image like [this](https://www.w3schools.com/howto/howto_css_flip_card.asp)). Besides putting an image as a `face`, I want to see if there are other variants.

### PR DESCRIPTION
**Pull request by Soare-Robert-Daniel**
Close #535

Content Options
- [x] Align content
- [x] Invert
- Front
  - [x] Add image/icon
  - [x] Add title
  - [x] Add description

Styling Options
 - [x] Add padding
 - [x] Shadows
- Background
  - [x] Color
  - [x] Image
  - [ ] Gradient?
 - Border
   - [x] Radius
   - [ ] Width

### CODE REVIEW

**Comment by mghenciu** [comment]
Following up from Slack, @Soare-Robert-Daniel, ideally, in the v1 this would be one of the use-cases, where the Block should shine ->

We have this section under the [Gym Site](https://demosites.io/fitness-gb/groups/).
image
Using the flip block, I want to transform this section in something shorter:
- with, a Trainer Image + Name + Speciality, on the front side
- on the back side, a short description/paragraph about that person + social links

I tried to[ achieve that result a](https://sourbushes.tastewp.com/a5213-groups/)nd here are my notes so far:
image

- the headline on the front side should have an adequate size (now, is way too big even for a single word)
- the text color on the front-side is not adjustable. So how will this work on dark sections or/and in dark mode
- the front side becomes Scrollable (not sure if this is what we want)
- what would be the usecase, when an user will use both sliders? let's say, have an image 30x60px. 
Wouldn't it make more sense to have a single size slider, which sets the image width in percetanges?
image

Try to take the usecase mentioned above and one more (for example build a section with an Icon, which represents a Service) - and refine the block based on this use-cases, to achieve the MVP for this block.

Thank you!

**Review by HardeepAsrani — CHANGES_REQUESTED** [review]
I will do the code review later but here are some things for now:

- In Inspector, only the first panel should be open by default, rest can be closed.
- Colors for Front/Back can be moved to their respective panels.
- You should add the image like other blocks do, see Cover Block for example. Their placeholder looks nice, our looks bit out of design with rest of Gutenberg.
- We can have better default styling, currently it looks bit tacky. A basic simple design will be good, don't need a default background color or such.
- You can also ask @irinelenache for the QA to make sure nothing breaks.
- And also, can you rebase this branch as I can see a lot of useless diffs which make it harder to review.

What do you think about the points I mentioned? @mghenciu

**Comment by Soare-Robert-Daniel** [comment]
@HardeepAsrani, making the front side with an `innerblock` is difficult, we need to separate them as separate blocks since a block can have only one `InnerBlock`. I tried it at first, but I did not succeed since multiple layers of `div` were making the CSS difficult and unresponsive.

**Comment by HardeepAsrani** [comment]
Let me know if a review is required here. Make sure you fix the diff issue.

**Pull request merged**
