### PR TITLE
Use Ai for patterns recommendation

### PR DESCRIPTION
**Pull request by Soare-Robert-Daniel**
Closes #.

### Summary

Use AI for pattern recommendation.

### Screenshots 

image

image

----

### Test instructions

⚠️ Make sure to have an OpenAI key.

Test the new pattern recommended. Focus on functionality rather than what patterns it suggests. If a pattern is broken by its nature, the issue will be separated.

---- 

### Checklist before the final review

- [ ] Included E2E or unit tests for the changes in this PR.
- [x] Visual elements are not affected by independent changes.
- [x] It is at least compatible with the [minimum WordPress version](https://wordpress.org/plugins/otter-blocks/).
- [x] It loads additional script in frontend only if it is required.
- [x] Does not impact the [Core Web Vitals](https://web.dev/vitals/).
- [x] In case of deprecation, old blocks are safely migrated.
- [x] It is usable in Widgets and FSE.
- [x] Copy/Paste is working if the attributes are modified.
- [x] PR is following [the best practices]()

### CODE REVIEW

**Comment by mghenciu** [comment]
In the context of the Layout builder, I would suggest we make the Input Field to be extendable either like the Textarea boxes have an icon in the right-bottom corner, or make it extend automatically. Because currently, if a user goes beyond 2 lines of text - it's already hard to read. Here is an example from ChatGPT: 
image


____

Overall I think it's good start.
Both the replace and the insert below options didn't worked for me.

Regarding the functionality, what do you think if we use an approach like Relume - where we first focus on having a good page/site structure (site map), and after that assign the corresponding patterns to each section?
So first it could be a panel with containers that represents sections, the user can re-arrange them, regenerate and so on.
After this step, those containers will be replace with Patterns from our library.

Here are some of the Prompts with the Results, in case anyone else is curious:
_a contact page for construction company, with a Header Section, details like address, phone number, email, and a contact form._

<details><summary>Result</summary>

image

</details>



_a page that will be used to showcase services for a printing company. The services include: printing Books, Business Cards, Packaging design, Advertising services, printing Stickers._ 

<details><summary>Result</summary>

https://github.com/Codeinwp/otter-blocks/assets/52494172/a9fc84f5-6dc1-492b-9de5-08d3040b81cc

</details>


_this is the homepage for wedding. It should have a minimalist style, with pink colors. it should mention the details about the wedding like the location, hour, schedule. the page should also contain a RSVP form_

<details><summary>Result</summary>

image

</details>

___

I think the Template Cards look different on the Form Block vs AI block. We should have them consistent:
image

**Review by HardeepAsrani — APPROVED** [review]
In terms of code, it looks good. The results aren't quite impressive but I can live with that for the initial version, we can refine it in upcoming versions more. We can make the design changes, remove unnecessary console logs and put it for QA.

And also update the prompt here: https://github.com/Codeinwp/store-themeisle/blob/master/web/app/plugins/templates-cloud/inc/class-otter-prompts.php

You can create a PR with the updated prompts, and I can review/test and merge it.

**Comment by mghenciu** [comment]
For the Icon, let's [ use this one](https://www.figma.com/file/dLNEZwxPRfh5X906ClqdA0/Otter-Icons?type=design&node-id=217-141&mode=design&t=GOZsngaI7ecXSFwz-11).

image

And what do you think if we use another name like: **AI Layout Generator** | **AI Page Generator** ?


___

On another note, is there any benefit to rush with the Release of this feature? one would be getting some idea if users are interested in it (if we track this) and what prompts they use, so we can improve it.
I mean, wouldn't it be better to wait for the Open AI november release - and maybe after that stage we can get better suggestions.

**Comment by Soare-Robert-Daniel** [comment]
@mghenciu, so I simplified the naming of all options. I will go with `Layout Generator`. `Page Generator,` we can use it if we also did personalized content inside the patterns, but there is no case for it now. Also, I removed the prefix `AI` from the naming since it is already in the `AI Block` box; no need to repeat it.

image

Also, this will go to the users in this release to refine it later. If it is about prompts, it can be solved very easily since prompts are renewed once a week, so when we change them, the user does not need to upgrade anything.

**Comment by mghenciu** [comment]
Is it possible to anonymously track what prompts users use?
This may help to understands what words they actually use in prompts and what they need.

**Comment by irinelenache** [comment]
@Soare-Robert-Daniel Tested and here is what i found:

- [ ] The layout of the OpenAI Key field in the editor looks a bit broken https://vertis.d.pr/i/zb8IIF
- [ ] Initially i got this error when i tried to generate something (both for Content and Layout generator) https://vertis.d.pr/i/b2JzjJ
- [ ] Sometimes the prompt doesn't generate anything https://vertis.d.pr/v/vCsBZu It should at least give an informative message about finding no results

**Comment by irinelenache** [comment]
@Soare-Robert-Daniel The mentioned issues are fixed, thank you ✔️ Found another strange issue:

- [ ] When i hit the **Insert below** button and i delete the AI block, the generated sections won't be visible until i refresh the editor (in frontend they are fine) https://vertis.d.pr/v/JLm4KG

You can check here:
```
 Admin area URL: https://aipatterns.s4-tastewp.com/wp-admin 
 Username: irinel 
 Password: B4BO7KKtk4Q 
```

**Comment by irinelenache** [comment]
@Soare-Robert-Daniel Checked again and now everything's fine, thank you ✅

**Pull request merged**
