### PR TITLE
Posts Block Enhancements

### LINKED ISSUE #814: Post Block - enhancements
This one has gone through a redesign recently, I would not get heavily involved at this point, but we can discuss about the following:

- adding plain / card / border styles.  In this case, instead of having the "List" as a "style", we can use a  toggle to "convert to list layout".
- Update the UI control to core UI wherever possible.
Screenshot 2022-03-18 at 11 19 12

___

### PR DESCRIPTION
**Pull request by HardeepAsrani**
Closes #814, #1148.

### Summary

This should redo the Posts Category with new styles and options.

Now it shows multiple categories in the Meta field if enabled while showing only one in the top-level Category field as multiple there looked ugly.

Make sure to test it with older versions to confirm everything is ported properly.

---- 

### Checklist before the final review

- [ ] Visual elements are not affected by independent changes.
- [x] It is at least compatible with the [minimum WordPress version](https://wordpress.org/plugins/otter-blocks/).
- [x] It loads additional script in frontend only if it is required.
- [x] Does not impact the [Core Web Vitals](https://web.dev/vitals/).
- [x] In case of deprecation, old blocks are safely migrated.
- [x] It is usable in Widgets and FSE.

### CODE REVIEW

**Comment by HardeepAsrani** [comment]
@mghenciu @JohnPixle It's ready for testing.

**Comment by HardeepAsrani** [comment]
> I can't edit a Posts block added with the previous version and i'm getting some error in console https://vertis.d.pr/7z5hb0

> The block breaks when i activate the Category in the Meta https://vertis.d.pr/9sSeDm I think the previous mentioned issue happens because it was activated on the block added in the previous version

@irinelenache I can't reproduce. Can you send the JSON for the older version?

**Comment by HardeepAsrani** [comment]
>  The meta size is applied both to the post meta and the category that is displayed separately https://vertis.d.pr/MNc3w5 (I don't know if this is desired but maybe the category can have a different control)

I'll leave this for design team to decide.

**Comment by HardeepAsrani** [comment]
>  When the border is activated, changing the style from Default to Boxed is changing the items padding https://vertis.d.pr/UgD9kN

That's normal. The Boxed style has padding added to it.

**Comment by HardeepAsrani** [comment]
>  Changing the image size isn't working https://vertis.d.pr/T1wVyq

That's for the image size, as in file being used, not the size in display.

**Comment by irinelenache** [comment]
@HardeepAsrani  The marked issues are fixed, thank you 🚀 

> I can't edit a Posts block added with the previous version and i'm getting some error in console https://vertis.d.pr/7z5hb0
> 
> The block breaks when i activate the Category in the Meta https://vertis.d.pr/9sSeDm I think the previous mentioned issue happens because it was activated on the block added in the previous version
> 
> @irinelenache I can't reproduce. Can you send the JSON for the older version?

I managed to isolate the issue, it happens when you activate the **Featured post** option and you also enable the category in the meta of the posts. You can also check this post https://posts-block.s2-tastewp.com/2022/10/07/posts-block/

Some other findings:

- [ ] The max value for content padding is 500 https://vertis.d.pr/u1MVXe
- [ ] How can i change the image size now? The control that was [here](https://vertis.d.pr/Gge1ec) is missing
- [ ] The category shown [here](https://vertis.d.pr/gxQGB5) is the first one in alphabetical order, can we do something so the user can choose which category is visible?

Here is the testing instance:
```
 Admin area URL: https://posts-block.s2-tastewp.com/wp-admin 
 Username: irinel 
 Password: o1AUnX28tUc 
```

**Comment by HardeepAsrani** [comment]
> The max value for content padding is 500 https://vertis.d.pr/u1MVXe

Yea, we added a high value that can be useful if someone is using one column layout.

> How can i change the image size now? The control that was [here](https://vertis.d.pr/Gge1ec) is missing

If you are using List layout, you can see it in Image panel.
Screenshot 2022-10-07 at 6 00 23 PM

> The category shown [here](https://vertis.d.pr/gxQGB5) is the first one in alphabetical order, can we do something so the user can choose which category is visible?

Not really, it's always the first category.

**Comment by HardeepAsrani** [comment]
The issue with block crashing should be fixed.

**Comment by JohnPixle** [comment]
@HardeepAsrani @Soare-Robert-Daniel Thanks for the update here, overall great work on the block, really digging it. I have some feedback too, posted below. I also created quick looms for each point. Let me know your thoughts:

- [ ] When in list mode, the row gap cannot go lower than the default value (For example if I want to set it to 0, I can't). Let's also note that there is a different row gap between the posts list and the Featured post. [**Video**](https://www.loom.com/share/de48e41a6ac44dca83500fb32ca2377c)

- [ ] Instead of character count, shall we have the post excerpt count in words? I think it's a more common practice.
Screenshot 2022-10-10 at 12 08 43



- [ ] In list layout, If the image width value is low, it is not being adjusted in a proper way. However, if I remove the     `flex-basis: 33.33%;` from the image, I get the expected result. I think this is causing the issue? [**Video**](https://www.loom.com/share/3bceb57ddd3a4dae97f67c1bdabe8e7e)

- [ ] In list layout, we need some kind of responsive control for the image width. [**Video**](https://www.loom.com/share/b33cb6ec07dd40808d3c4b137fb5eb16)


- [ ] When he user is using a "featured post" ideally we want to have an image height control. Also, there appears to be an issue with the width of the featured post, as shown in the [**video.** ](https://www.loom.com/share/9ef4dec1daca401d97445635442260cc)


- [ ] text color should affect link color as well. Currently any link in the meta inherits the theme link color. Let's simplify things by applying the text color on links as well.

- [ ] Since we dont offer any "design" options anymore in this tab, perhaps we should rename `Design and Layout` into `Layout` or `Block elements`? Let me know what you think.
Screenshot 2022-10-10 at 12 19 21


Also keeping @irinelenache in the loop

**Comment by HardeepAsrani** [comment]
@JohnPixle

> Instead of character count, shall we have the post excerpt count in words? I think it's a more common practice.

We can't because of Backward compatibility.

> In list layout, If the image width value is low, it is not being adjusted in a proper way. However, if I remove the flex-basis: 33.33%; from the image, I get the expected result. I think this is causing the issue? [Video](https://www.loom.com/share/3bceb57ddd3a4dae97f67c1bdabe8e7e)

Given that all the images might not be of same sizes, we set a minimum container limit for it. If we remove the 33% flex, images can appear of different sizes, and by default might take a lot more space than they should. I don't know what is a perfect solution here but also we had to make the image container to take full size (previously they looked different) to make use of Border & Background Color.

> Also, there appears to be an issue with the width of the featured post, as shown in the video. 

I can't reproduce that issue on my side. Are you able to reproduce it on all themes or in some themes in particular?

**Comment by HardeepAsrani** [comment]
PS: I've added Image Width responsive options + fixed inheritance issues. Let me know how it looks now.

**Comment by mghenciu** [comment]
I also did some quick testing, here are my findings (hope I didn't reported something already said by John or Irinel):

- [ ]  when using the **List View** there should be some top padding by default. Right now there's no padding-top. This is especially noticeable using the Boxed view:

Screenshot 2022-10-11 at 16 11 27

 
___

- [ ] can't the Border radius controls be for each side? for the Blog box and also for the Image 
image


___

- [ ] We need to think of how do we handle grid behaviour on Tablet & Mobile. One idea would be to have responsive controls for this, or on Mobile to stack them on top of each other. Right now it uses the same number of columns on all devices: 
image
 
___

- [ ] Maybe we should add the option for Vertical Alignment if the Posts are in List View (**justify-content**): 
image

**Comment by HardeepAsrani** [comment]
Screenshot 2022-10-11 at 11 38 10 PM

@mghenciu We already have Vertical Alignment controls.

**Comment by HardeepAsrani** [comment]
@mghenciu All the mentioned issues should be fixed now.

**Comment by mghenciu** [comment]
> @mghenciu All the mentioned issues should be fixed now.

Nice work with the quick fix @HardeepAsrani 🏎️ !

___
Some things I noticed:

- [ ] there are **two Layout Panels**. I think John suggested above a different name for one of them:
Screenshot 2022-10-12 at 10 48 50

___

- [ ] The Posts Type description should be similar like the one in core, meaning that the helper text is below the Selector and with a secondary color: 
image

___

- [ ] @JohnPixle , I am thinking it may be better to have (by default) the Meta a smaller size compared to the excerpt. Right now both of them are **16px**. Maybe we can have 16px for the Excerpt and 12 or 14px for the Meta - this way the Visual Hierarchy will be better:
Screenshot 2022-10-12 at 11 07 11

We are using this approach in Neve also.

___

- [ ] Is it possible to have the Reset for Border radius at the bottom of the Control, similarly how it's on the Border Panel?
Otherwise it's sticking to the Clear button:  
Screenshot 2022-10-12 at 11 14 04

___

- [ ] The Style Panel is visible on both Tabs:

https://user-images.githubusercontent.com/52494172/195289054-a379f83b-1f89-4364-a0a6-a943f8d8f824.mov

**Comment by HardeepAsrani** [comment]
@mghenciu All should be better. Box Shadow is a known issue where it doesn't work with CSS variables.

**Comment by mghenciu** [comment]
Looks good @HardeepAsrani , the changes I mentioned are fixed.
For the Shadows, didn't Arina used something like this on the Accordion block? or it's a different implementation
___

- [ ] Just one small change, I would just increase the default Gap for Rows & Columns, both in grid mode and list. It should be **around 30px between items**.

___
### Consistency
I see that on the Style Tab, the Colors panel is opened by default and has a different look. I guess this is intended, but I am not getting **the reason behind this change**, as we agreed to be consistent in using the same UIX patterns for all blocks. 
For example this is how the Colors look on the Flip block, and this is from the Posts block:
Screenshot 2022-10-14 at 11 37 31

**Comment by HardeepAsrani** [comment]
Screenshot 2022-10-15 at 12 00 59 AM

@mghenciu That's just you using a different version of WordPress. This is how Flip blocks look on my WordPress 6.1 beta.

**Comment by HardeepAsrani** [comment]
@mghenciu I've used Arina's solution and it should work now + I've also changed the default values for Gaps. I'll merge it now. It's already Friday night so we can have the release on Monday after the meeting, and can make any changes if needed.

**Pull request merged**
