### PR TITLE
fix: widget_styles

### PR DESCRIPTION
**Pull request by preda-bogdan**
Closes Codeinwp/neve#4150.

### Summary

The condition for enqueueing frontend styles for the widgets blocked the styles from registering.

### Screenshots 
image

----

### Test instructions

1. Use Neve
2. Add Otter blocks to the footer widget area
3. Customize the widgets with styles
4. Check that the styles are preserved on the frontend.

---- 

### Checklist before the final review

- [ ] Included E2E or unit tests for the changes in this PR.
- [x] Visual elements are not affected by independent changes.
- [x] It is at least compatible with the [minimum WordPress version](https://wordpress.org/plugins/otter-blocks/).
- [x] It loads additional script in frontend only if it is required.
- [x] Does not impact the [Core Web Vitals](https://web.dev/vitals/).
- [x] In case of deprecation, old blocks are safely migrated.
- [x] It is usable in Widgets and FSE.
- [x] Copy/Paste is working if the attributes are modified.
- [x] PR is following [the best practices]()

### CODE REVIEW

**Comment by HardeepAsrani** [comment]
@Soare-Robert-Daniel @preda-bogdan Looking at the code, we are now getting the stylesheet from saved options even if the saved CSS file exists. This might be fixing the issue but the workflow seems to be wrong. The later code also becomes redundant if the CSS file doesn't exist.

Let me know if I'm wrong in how it's working.

**Comment by preda-bogdan** [comment]
@HardeepAsrani You were right, that was not the proper fix after some more digging I found out that we were never saving the styles when updating via the REST endpoint as a result of the changes introduced here: https://github.com/Codeinwp/otter-blocks/pull/1867

This should work as expected now.
Let me know if you see any issues with the current implementation, if approved, I can move this to testing.

Thank you!

**Review by HardeepAsrani — APPROVED** [review]
Looks good. 🚀

**Review by Soare-Robert-Daniel — APPROVED** [review]
Looks good. Also, you can use some of the phrases for function description: `Autoloads widgets in REST API context to update CSS data.`, `In REST API context, this method ensures widget autoloading for CSS data refresh.`, `Handles widget autoloading in REST API to update associated CSS.`, `Autoloads widgets during REST API requests for CSS updates.`

**Comment by Soare-Robert-Daniel** [comment]
> Do you know if the blocks worked in the customizer context before? From my testing, this has never worked for Otter blocks, is there something that I was missing for the partial rendering?

I think @HardeepAsrani can clarify this. I know that we always had trouble with the CSS in Customizer and Widgets. My attempt to try to solve the widgets was fully complete and more on the reported issue. The entire pipeline is very cumbersome as you need to account for a lot of edge cases (like Neve Custom Layouts).

**Comment by irinelenache** [comment]
@preda-bogdan Tested and now everything works fine, thank you 🚀

**Comment by preda-bogdan** [comment]
@irinelenache Thank you for testing, and for your attention to details! 💯

**Review by Soare-Robert-Daniel — APPROVED** [review]

**Pull request merged**
