### PR TITLE
Improve Web Core Vitals

### PR DESCRIPTION
**Pull request by Soare-Robert-Daniel**
Changelog:
 - **Maps**: Move `height` value to the render function so that the maps can have the space already allocated, this will eliminate the layout shift when the maps are loaded.  Updated the dependency files, upgraded the connection to `https`. Fixed loading issues.
 - **Glide**: Delay the loading of glide CSS deps for improving FP & FCP. Add `height` via php to eliminate layout shift after loading the image.

⚠️ **Test with http/2 connection for checking the loading request**. Reference: [http vs http2](https://www.greenlanemarketing.com/resources/articles/seo-101-http-vs-http2/)

@ineagu can you share some insight?

---

### Testing the [First Contentful Paint (FCP)](https://web.dev/fcp/)

To improve this, we need to make sure the critical CSS is loading and the non-critical is delayed. 

Example:

image

Observations:
 - Critical CSS (theme CSS, block CSS) are loaded and parsed first. Their priority is high.  Non-Critical styles start mostly after the critical styles are done.
 - The First Paint (FP) is given by the longest process from critical CSS styles, in this case, `style.css` provided by `twenttwenty` theme.

Improvements:
- Delay non-critical CSS styles by moving them in the footer. Commit: https://github.com/Codeinwp/otter-blocks/pull/614/commits/7dd5648045112930cb66a513bf92158d7570abd7
- Load only the used styles so that they can be loaded and parsed faster. Currently, in otter, we give styles for all the blocks. Detect unused CSS with [DevTools](https://developer.chrome.com/docs/devtools/coverage/)

Example Coverage:
image

### Testing the [Cumulative Layout Shift (CLS)](https://web.dev/cls/)

If you add in the page blocks like maps (google and simple), slider, and preview it, you will that they have an empty space and after loading the maps or the images, they expand and so it moves the content.

This is not good, especially if the block is at the beginning of the page.

This PR will allocate the necessary space and display a loading placeholder to indicate that something must be there.

Example:

The page has in this order: `1 x Section Block( with Header with Solid Background by Otter), 5 x Maps Block, 3 x Slides Block`

image

image

As you can see, the CLS is very small, the tiny value is caused after the Glide CSS (`glide.core.min.css`) is loaded and it had some unpositioned elements until all the necessary assets (`glide.theme.min.css`) are finished.
image

 ---

### Testing the PR

Use the **current version or the `development` branch**. Insert many maps and slides, plus some other blocks, go to the Lighthouse tab and check for performance. The score should be worse.

Switch to this PR and check again.

⚠️ **Make sure to use HTTP/2 or HTTPS. WP Taste is good for testing.**
⚠️ **Do not use blocks there are not present in PR if you test with the `development branch. E.g.: Flip Block**.
⚠️ **Use only our blocks**.

### CODE REVIEW

**Comment by HardeepAsrani** [comment]
How will this help? Genuinely asking as I don't have much idea.

**Comment by ineagu** [comment]
Few thoughts based on what I saw with Robert.

1.We saw some weird behaviour on localhost when it was not loading more than x files in parallel, I assumed is http or http 1/2 issue, it works fine on tastewp.

Moving from there we have those metrics that we can actually test:

1.FCP

For this one we need first to make sure there is no js running in the head & there is minimal css running (sort of critical css), I think we need to find a balance between code complexity,  speed and UX.

For example on the maps section, maybe we want to load directly in the html a blurred 10px enlarged image as a placeholder instead of an empty container, to let the user know there is a map there before having the map.

2. CLS

This is connected with 1, we need to make sure the css that we ship in head is enough to. avoid shifting elements in the page

3.LCP

This one is easier, we need to make sure there is not a ton of JS loaded that also does a lot of processing. E.g the map section can be an issue here.

The option that we have now with loading directly the map, would affect the largest contentful paint if the map is in viewport, an option where the map would start loading on scroll or user interaction, would not affect it.

Again is a tradeoff between speed and UX.

**Comment by HardeepAsrani** [comment]
@ineagu @Soare-Robert-Daniel This can be useful here https://developers.google.com/maps/documentation/maps-static/overview

**Comment by HardeepAsrani** [comment]
@Soare-Robert-Daniel What's the status here? Anything else left?

**Comment by Soare-Robert-Daniel** [comment]
I think this issue is left: https://github.com/Codeinwp/otter-blocks/issues/638

**Comment by HardeepAsrani** [comment]
@Soare-Robert-Daniel We can treat it as a separate issue but everything for here is done? Even loading image map at beginning?

**Comment by HardeepAsrani** [comment]
Any for width and height, you can see what looks good. WordPress by default has some sizes so we can choose those instead of loading full size images.

**Comment by Soare-Robert-Daniel** [comment]
@HardeepAsrani, all we need is testing that everything is working. Also, we can try some sites made in otter and see how much improve the performance.

**Comment by Soare-Robert-Daniel** [comment]
@HardeepAsrani, another complaint from Lighthouse is that the images from the `slides` do not have fixed `width` and `height`.
https://github.com/Codeinwp/otter-blocks/blob/45cd071f10aacca388eae1983864fda3ecfb98ee/src/blocks/blocks/slider/style.scss#L20-L25

image

This usually appears when the slider has big unoptimized images. Should we let this to plugins that optimize the images?

**Comment by Soare-Robert-Daniel** [comment]
@HardeepAsrani, I made a merge with `development` on local and test with WP 5.5.3 and WP 5.9 Beta. The pages are not breaking when upgrading from stable to this version.

**Comment by HardeepAsrani** [comment]
@Soare-Robert-Daniel I suppose we can let it go for the images as it handles the sizes. Can you talk to @irinelenache about how he can test and compare to a previous version?

**Comment by irinelenache** [comment]
@Soare-Robert-Daniel Sometimes the slider doesn't work for me with this PR and i get an error in console https://vertis.d.pr/ItKzJy

Also, the Performance score is slightly lower when Neve is activated, compared to Twentytwentyone (89 vs 99)

You can check the issue on this instance:
```
 Admin area URL: https://wrestlejellyfish.tastewp.com/wp-admin 
 Username: irinel 
 Password: tbuAcIJRM6E 
```

**Comment by Soare-Robert-Daniel** [comment]
@irinelenache, the rare error with the `slider` should be solved.

> Also, the Performance score is slightly lower when Neve is activated, compared to Twentytwentyone (89 vs 99)

When making this comparison, it is good not to have unoptimized images on the site. And it needs a proper investigation on analysis to see if it's the theme fault.

**Comment by HardeepAsrani** [comment]
@irinelenache @Soare-Robert-Daniel Any update on this or is it ready for merging?

**Comment by Soare-Robert-Daniel** [comment]
@HardeepAsrani, it only needs a test for Slider to be sure that the `window.Glide` is ready before initializing.

**Comment by irinelenache** [comment]
@Soare-Robert-Daniel @HardeepAsrani Tested again and didn't encounter any error using the **Slider** 🚀

**Comment by HardeepAsrani** [comment]
@Soare-Robert-Daniel Feel free to merge if you're satisfied.

**Pull request merged**
