### PR TITLE
Slider Block & Maps Block

### PR DESCRIPTION
**Pull request by HardeepAsrani**
Closes https://github.com/Codeinwp/otter-internals/issues/8.

### Summary

This brings the enhancements to Slider Block and also adds the Inspector Tabs to Google Maps block. @mghenciu @JohnPixle 

Also Adds Responsive Height Control to Google/Leaflet Map, previously it was a single input.

---- 

### Checklist before the final review

- [ ] Visual elements are not affected by independent changes.
- [x] It is at least compatible with the [minimum WordPress version](https://wordpress.org/plugins/otter-blocks/).
- [x] It loads additional script in frontend only if it is required.
- [x] Does not impact the [Core Web Vitals](https://web.dev/vitals/).
- [x] In case of deprecation, old blocks are safely migrated.
- [x] It is usable in Widgets and FSE.

### CODE REVIEW

**Comment by mghenciu** [comment]
The Structure looks good, @HardeepAsrani , nice work. 🚀 

___

Same thing mentioned here about [consistency](https://github.com/Codeinwp/otter-blocks/pull/1171#issuecomment-1278682057) for the Color Panel. In this case things are also different on the Border Panel, there are different type of controls and some spacing is missing.
This is how it looks on the **Posts** Block: 
image

And here is the **Slider** block:
Screenshot 2022-10-14 at 11 51 57

___
For the other additional Controls, are we planning to add them later? like this ones 
image

___
For the **Google Maps**, the structure changes look good. 
But there are some inconsistencies between Figma and the Build:
- Map height is not responsive
- Map type is in a different panel, compared to Figma
- Markers should have increment (Marker 1, Marker 2, etc)

**Comment by HardeepAsrani** [comment]
@mghenciu The cancel button will have some margin once it's merged, as we've made those changes in Posts PR so didn't want to make the same changes here. Once both are merged, the Clear button will have some spacing. Also, we can't change the position as the Box Control has its own Clear button.

**Comment by HardeepAsrani** [comment]
> Markers should have increment (Marker 1, Marker 2, etc)

People can actually put their custom name in the market that's why we don't use incremental names, people might add/remove and end up with multiple markers with same number.

**Comment by HardeepAsrani** [comment]
@mghenciu I've added the height option.

Would be nice if you can move blocks which are done to a different panel: https://www.figma.com/file/LRrhO1ovZnXFibXVsezR8a/Otter?node-id=114%3A2 - so we can know which are done and which are needed to be done. Gets bit confusing.

**Comment by mghenciu** [comment]
> > Markers should have increment (Marker 1, Marker 2, etc)
> 
> People can actually put their custom name in the market that's why we don't use incremental names, people might add/remove and end up with multiple markers with same number.

For sure Hardeep, users can adjust the names. I was just thinking about the first steps when inserting a block. 
My assumption here is that having everything unnamed, requires more brain work for the user to understand what is going on there (for example selecting the Initial Tab, or moving the markers on the Map):  
image

This shouldn't have a lot of logic, just something like: **on new Marker/Accordion Item/Tab item insert count the Items -> and the new item name will be Marker Count + 1.**
But if it requires a lot of code logic, we can leave for later.

**Comment by HardeepAsrani** [comment]
It requires not a lot of logic but we can't have Consistency with the numbers as Custom Marker text is actually saved there. We might end up with
Marker 1
Marker 4
Marker 3

And so on. Which I find to be even worse. 😄

**Comment by irinelenache** [comment]
@HardeepAsrani After updating to this PR, all previously added Sliders are broken, here is a video with the behaviour https://vertis.d.pr/v/zSAQTN . Also, after Regenerating styles, all posts are broken in frontend https://vertis.d.pr/i/NHoapr

**Comment by HardeepAsrani** [comment]
@irinelenache It was a typo in namespace name. Should be fixed.

**Comment by irinelenache** [comment]
@HardeepAsrani Tested again and didn't find any problem with the Slider and the Leaflet map 🚀 

For the Google maps block, when i'm adding it to the post the block will break and i'm getting an error in console https://vertis.d.pr/v/CcNmZn

**Comment by HardeepAsrani** [comment]
@irinelenache can you check again?

**Comment by irinelenache** [comment]
@HardeepAsrani Checked again and now everything works fine, thank you 🚀

**Pull request merged**
