### PR TITLE
Remove Woo Comparison Table

### LINKED ISSUE #1034: Migrating Woo Comparison table to Sparks
### Description:
We need to migrate the current comparison table to Sparks and remove it from Otter.

### PR DESCRIPTION
**Pull request by HardeepAsrani**
Closes #1034.

### Summary
This removes Woo Comparison table and switches to the one in Sparks if that is available.

---- 

### Checklist before the final review

- [x] Visual elements are not affected by independent changes.
- [x] It is at least compatible with the [minimum WordPress version](https://wordpress.org/plugins/otter-blocks/).
- [x] It loads additional script in frontend only if it is required.
- [x] Does not impact the [Core Web Vitals](https://web.dev/vitals/).
- [x] In case of deprecation, old blocks are safely migrated.
- [x] It is usable in Widgets and FSE.

### CODE REVIEW

**Comment by HardeepAsrani** [comment]
@irinelenache If you test with this: https://github.com/Codeinwp/sparks-for-woocommerce/pull/36

The block from Otter should automatically switch to one from Sparks. In the frontend before the migration will be empty, only happens when you open the editor.

Also, it's more about the attributes getting migrated than how it looks, so just make sure things are migrated properly.

Let me know how it goes!

**Comment by irinelenache** [comment]
@HardeepAsrani 

- [ ] With Otter installed & activated, the comparison block will still uppear under Otter category of blocks https://vertis.d.pr/vrt8va
- [ ] The colors selected in the editor for Background and Header text don't work if Otter is installed and activated

**Comment by HardeepAsrani** [comment]
>  The colors selected in the editor for Background and Header text don't work if Otter is installed and activated

What do you mean?

**Comment by mskapusuz** [comment]
> > The colors selected in the editor for Background and Header text don't work if Otter is installed and activated
> 
> What do you mean?

I think I reproduced the issue; the background doesn't work for the Comparison Table block. To test it, I rollbacked to old versions, and I can say that regression occurred during the Otter Pro release. (before the Sparks release)

so bg color;

doesn't work with: Neve 3.3.0 + Neve Pro 2.3.0 + Otter 2.1.0 + Otter Pro 2.1.0
but works with: Otter 2.0.2 + Neve Pro 2.2.3 + Neve 3.2.3

I'll handle it.

Screen Shot 2022-10-30 at 00 08 44
Screen Shot 2022-10-30 at 00 00 50

**Comment by mskapusuz** [comment]
**Last update:**

I've reviewed the bg color and block style issue; the issue is not related to the Otter Pro release. The issue was occurred during the lowercasing CSS variables on Neve Pro (to better support PageSpeed - https://github.com/Codeinwp/neve-pro-addon/pull/1977)

So, the css var in Neve Pro was: `--bgcolor`
but in Otter: `--bgColor`

Current case:
In Sparks the css variable isL `--bgcolor`
in Otter postmeta and codebase: `--bgColor`

Also an another problem with moving to Sparks is: `div.nv-ct-container` has been renamed as `div.sp-ct-container`

Therefore probably we should have a migrator for the saved css

**Pull request merged**
