### PR TITLE
Default open tab

### PR DESCRIPTION
**Pull request by arinaturcu**
Adds a select control for choosing which tab is open by default.

### CODE REVIEW

**Comment by HardeepAsrani** [comment]
Hey @arinaturcu, I made a couple of changes: https://github.com/Codeinwp/otter-blocks/pull/800/commits/e5eb474a75c46e2c3f8a58df5a914f3c9ebd4e35

The major one is to only show the data-default-open only if it is set to yes. If we don't make it conditional, all tabs block that were made before this version will break.

All yours @irinelenache!

**Comment by irinelenache** [comment]
@arinaturcu @HardeepAsrani Tested and found some things:

- [ ] After just adding some tabs and content to them, without making any change to the order or style, they won't be visible in frontend until clicking on them https://vertis.d.pr/dC6rmN (If i make any change to the **Initial tab** setting, it works fine)
- [ ] After adding the tabs, without making any change to the **Initial tab** option, when i change the order of the tabs, the initial tab option doesn't change accordingly https://vertis.d.pr/nuyhHG

Besides that, everything seems to work fine 🚀

**Comment by arinaturcu** [comment]
@irinelenache Thank you for testing! :rocket: 

The issues should be fixed now, let me know if they persist or if you find anything else.

**Comment by HardeepAsrani** [comment]
@arinaturcu The issue that Irinel pointed out needs to be fixed?

**Comment by arinaturcu** [comment]
@HardeepAsrani yes, working on it.

**Comment by HardeepAsrani** [comment]
Thanks for letting me know!

**Comment by arinaturcu** [comment]
@irinelenache Hope everything works fine now :robot:

**Comment by irinelenache** [comment]
@arinaturcu Tested again and now everything works fine, thank you 🚀

**Comment by Soare-Robert-Daniel** [comment]
@arinaturcu, @HardeepAsrani  while fixing #832. I found this weird behavior: If I make new tabs without modifying the name, all of them will be open on the front end. If I change the name, the problem is still happening. The problem is solved only if I go to the SelectControl and choose a tab, this way the other will reset. 


https://user-images.githubusercontent.com/17597852/160578446-59ae7a76-1415-4bbe-955b-a4dd6c32d79e.mp4

I suspect that there is no mechanism that updated the `defaultOpen` when the tab's name change. Also, we should only open a single tab in the frontend script even if multiple items have the `defaultOpen` set to true.

I will integrate the changes in #841

**Pull request merged**
