### PR TITLE
Improve Product Review Block design.

### LINKED ISSUE #1312: Making use of Finmasters' Review Design
### Description:

@JohnPixle @mghenciu I think we can take use of the design that @milicavs used for the Finmasters website: https://finmasters.com/experian-boost-review/ - What do you both think?

If yes, then we will have to see how we can make the design work wth her other suggestion that we plan on adding: https://github.com/Codeinwp/otter-blocks/issues/1260

What do you think?

### PR DESCRIPTION
**Pull request by Soare-Robert-Daniel**
Closes #1312 .

### Summary

Improve Product Review block design by allowing to be more compact.

Thanks to @mghenciu for the feedback.

#### One Column with Inline active

image

#### Two Column with Inline active

image

https://github.com/Codeinwp/otter-blocks/assets/17597852/b4c48080-1313-4012-b82e-1ee6dbf4b5c2

----

### Test instructions

1. Make sure that nothing is breaking.
2. New Inline style does not break the layout
 

---- 

### Checklist before the final review

- [x] Visual elements are not affected by independent changes.
- [x] It is at least compatible with the [minimum WordPress version](https://wordpress.org/plugins/otter-blocks/).
- [x] It loads additional script in frontend only if it is required.
- [x] Does not impact the [Core Web Vitals](https://web.dev/vitals/).
- [x] In case of deprecation, old blocks are safely migrated.
- [x] It is usable in Widgets and FSE.
- [x] Copy/Paste is working if the attributes are modified.
- [x] PR is following [the best practices]()

### CODE REVIEW

**Comment by HardeepAsrani** [comment]
Here I think instead of having a new toggle, we can just use Block Styles for the Inline option, and just keep it one column when it's set to inline. What do you think @JohnPixle?

**Review by HardeepAsrani — CHANGES_REQUESTED** [review]
Awaiting confirmation from John.

**Review by HardeepAsrani — APPROVED** [review]

**Comment by rodica-andronache** [comment]
@Soare-Robert-Daniel 
One Column with Inline rating enabled - on mobile looks broken https://vertis.d.pr/i/fTz3Ne compared to how it looks when Inline rating is not enabled https://vertis.d.pr/i/p15ev4

Same happens for Two columns

**Comment by Soare-Robert-Daniel** [comment]
@Codeinwp/design-team, should we also add the following style with the number under the start from inline to the base one?

This is with the new feature.

image

This is the original

image

**Comment by Soare-Robert-Daniel** [comment]
@JohnPixle, thanks for the feedback.

Also, I will check the reported issue 🙏

**Comment by Soare-Robert-Daniel** [comment]
@JohnPixle, in your instance, you have two versions of Otter installed simultaneously.

image

You should disable one of them.

Also, I double-checked on Wp Taste that the build is ok.

**Comment by rodica-andronache** [comment]
@Soare-Robert-Daniel everything's working well 👍

**Pull request merged**
