### PR TITLE
Development

### PR DESCRIPTION
**Pull request by HardeepAsrani**
- https://github.com/Codeinwp/otter-blocks/issues/1221
- https://github.com/Codeinwp/otter-blocks/issues/1210
- https://github.com/Codeinwp/otter-blocks/issues/1241
- https://github.com/Codeinwp/otter-blocks/issues/1181
- https://github.com/Codeinwp/otter-blocks/issues/1238
- https://github.com/Codeinwp/otter-blocks/issues/1220
- https://github.com/Codeinwp/otter-blocks/issues/1208
- https://github.com/Codeinwp/otter-blocks/issues/1203
- https://github.com/Codeinwp/otter-internals/issues/32
- https://github.com/Codeinwp/otter-blocks/issues/1257
- https://github.com/Codeinwp/otter-blocks/issues/1223
- https://github.com/Codeinwp/otter-blocks/issues/713
- https://github.com/Codeinwp/otter-blocks/issues/1148
- https://github.com/Codeinwp/otter-blocks/issues/814
- https://github.com/Codeinwp/otter-blocks/issues/1268
- Add closing to Sticky in Float Mode
- Add class to body when some element is active in Sticky

### CODE REVIEW

**Comment by irinelenache** [comment]
@HardeepAsrani Tested the PR and apart of the alignment issue mentioned [here](https://github.com/Codeinwp/otter-blocks/issues/1203#issuecomment-1274929511), i didn't find any problem 🚀

**Comment by HardeepAsrani** [comment]
@JohnPixle @mghenciu I've fixed the patterns. You can check now. Every should work on 5.9 and above; only 3 don't work in 5.8 which I've excluded. There is an alignment issue in 5.8 with buttons but that's all, everything else works fine.

@irinelenache We've made many changes so can you go thru QA again? Make sure to test with previous versions of WP.

**Comment by irinelenache** [comment]
@HardeepAsrani Checked again and everything seems to work fine with the older versions 🚀 

Found a single problem, not necessarily related to the PR i guess:
- When i have a post with some Woocommerce dynamic data (a product image) and i'm disabling the Woocommerce plugin, there will be a fatal error on that post and i can't edit it until i activate Woocommerce again

   post with woo activated: https://vertis.d.pr/BS5PzC
   post with woo deactivated: https://vertis.d.pr/FlBPzt

**Comment by HardeepAsrani** [comment]
Thank you Irinel, it's been fixed.

**Pull request merged**
