### PR TITLE
Improve Marketing Integration info & bug fix

### LINKED ISSUE #1290: Add option to disable email notifications if user has enabled subscription
A user asked if it's possible to disable the email notifications that are sent to the admin when a person subscribes to the form from the maintenance/coming soon page. Maybe we could add an option to be able to do this.

As an alternative solution, I think we could create a doc explaining how to achieve this with custom code.

Suggested [here](https://wordpress.org/support/topic/disable-email-notifications-12/).

### PR DESCRIPTION
**Pull request by Soare-Robert-Daniel**
Closes #1290

### Summary

🖊️  Improved the Marketing Action explanations.
🐛 Fixed a bug related to the default action.

### Screenshots 

image

image

image

----

### Test instructions

⚠️ This is tied to the `development` branch. When `next` will be merged, I will update this.

⚠️ You will need a Mailchimp and Sendinblue account.

1. Make a Form
2. Fill in the Marketing integration options.
3. Ensure that they work as expected.

---- 

### Checklist before the final review

- [ ] Included E2E or unit tests for the changes in this PR.
- [x] Visual elements are not affected by independent changes.
- [x] It is at least compatible with the [minimum WordPress version](https://wordpress.org/plugins/otter-blocks/).
- [x] It loads additional script in frontend only if it is required.
- [x] Does not impact the [Core Web Vitals](https://web.dev/vitals/).
- [x] In case of deprecation, old blocks are safely migrated.
- [x] It is usable in Widgets and FSE.
- [x] Copy/Paste is working if the attributes are modified.
- [x] PR is following [the best practices]()

### CODE REVIEW

**Review by HardeepAsrani — CHANGES_REQUESTED** [review]

**Comment by Soare-Robert-Daniel** [comment]
🔧 The message is now changed and also added a new message to inform the user that they might lose some data with the combination of Email saving and Subscriber Only combo.

ℹ️ This new message will also serve as a small upsell on the Database Pro option.

image

**Review by HardeepAsrani — APPROVED** [review]

**Comment by irinelenache** [comment]
@Soare-Robert-Daniel From what i understand, if i use **Email Only** as save location and **Subscribe only** as submit action, i shouln't receive any email and the contact should be added in the marketing integration tool (i used Mailchimp). While testing this behaviour, i received the email and the contact wasn't added to the marketing integration tool, so it's not working on my end.
Please let me know if i misunderstood anything 🙏 

Can be checked here:
```
URL: https://otter-stuff.vertisite.cloud/15c42-web-agency-gb-contact-us/
Username: kikevepiwu4475
Password: nAfE6HGJrILlpUc3wOeu
```

**Comment by Soare-Robert-Daniel** [comment]
The problem was that when you update the page via Update button, the Integration settings will disappear thus the error reported. When implementing the deferred save, the mechanism replace the entire value, the change in form did not account for the information in the old value, thus the loss of information.

@irinelenache, I updated your testing instance to the latest build.

**Comment by irinelenache** [comment]
@Soare-Robert-Daniel 

- [ ] After the loading finishes in the **Form options** and **Marketing integration** tabs, it takes another ~20 seconds for the data to be visible there https://vertis.d.pr/v/lhhFDX
- [ ] The contacts are not added to Mailchimp when the form is submitted. I also tried using the **Test service** button which doesn't give any error but no new contact is added there

**Comment by Soare-Robert-Daniel** [comment]
> * [ ]  After the loading finishes in the **Form options** and **Marketing integration** tabs, it takes another ~20 seconds for the data to be visible there https://vertis.d.pr/v/lhhFDX

This depends on the WP instance until it gest the options.

> * [ ]  The contacts are not added to Mailchimp when the form is submitted. I also tried using the **Test service** button which doesn't give any error but no new contact is added there

This should be working.

----

@irinelenache,if you can provide a recording in Slack with how you set until test might be helpful 🙏

**Comment by irinelenache** [comment]
@Soare-Robert-Daniel Tested again and now everything works as expected 👍

**Comment by AndreeaCristinaRadacina** [comment]
hey @Soare-Robert-Daniel,

Can you change "news letter" to "newsletter"?
image

**Comment by AndreeaCristinaRadacina** [comment]
Question here:
If I use Database & Email as a save location, it says in the note that I will receive notifications via email.
However, if I also use the "Subscribe Only" as an action, no notification should appear in the email. 

As a result, the submissions appear under Form Submissions, and no email is received, which is not the ideal behavior since I was able to select Database & Email.


My suggestion: If Database & Email is selected, the Subscribe Only option should be greyed out.

**Comment by AndreeaCristinaRadacina** [comment]
- [ ] We should replace "Form to" with "Email To", for consistency:

image

- [ ] it says something about third-party consent, but I cannot see any checkbox

**Pull request merged**
