### PR TITLE
Add RankMath for Posts block

### LINKED ISSUE #1871: Add compatibility with Rank Math for having internal links in the Posts block
### What problem does this address?

A user who added the Posts block in their pages noticed in the SEO score of Rank Math that internal links are not available in our Posts block.

### What is your proposed solution?

This can be done by adding Rank Math integration according to [this guide](https://rankmath.com/kb/content-analysis-api/).

Requested here: https://wordpress.org/support/topic/integrate-rankmath-with-otter/#post-17061539
Discussion with Rank Math support: https://wordpress.org/support/topic/woocommerce-product-block-not-classed-as-internal-link/#post-16971398

### Will this feature require documentation? (Optional)

No.

### PR DESCRIPTION
**Pull request by Soare-Robert-Daniel**
Closes #1871

### Summary

Add RankMath integration for Posts Block

Some notes on development:
- At first I tried to add inside the Edit component on the idea that each Block when is created its adding its own hook. The process was pretty messing with reactivity so I decided add a simple script that initiate at loading and scan everything at once -- reliable solution decoupled from react component, much easier to maintain and possible crashes on the block.
- I wanted to initiate the hook after the `rank-math-app.js` is loaded in the page via script loading. My attempt was unsuccessful so I used a simple try system.

### Screenshots 

https://github.com/Codeinwp/otter-blocks/assets/17597852/90e629e6-eff4-43da-bfec-9a28468f1289

----

### Test instructions

ℹ️ You will need RankMath plugin

1. Insert a Posts Block
2. Check the RankMath of the page.
3. You should not see the error message with `Add internal links in your content` since Post block will add references to other posts.

image

---- 

### Checklist before the final review

- [ ] Included E2E or unit tests for the changes in this PR.
- [x] Visual elements are not affected by independent changes.
- [x] It is at least compatible with the [minimum WordPress version](https://wordpress.org/plugins/otter-blocks/).
- [x] It loads additional script in frontend only if it is required.
- [x] Does not impact the [Core Web Vitals](https://web.dev/vitals/).
- [x] In case of deprecation, old blocks are safely migrated.
- [x] It is usable in Widgets and FSE.
- [x] Copy/Paste is working if the attributes are modified.
- [x] PR is following [the best practices]()

### CODE REVIEW

**Review by HardeepAsrani — COMMENTED** [review]
Any reason why we are using HTML selectors to implement it and adding all the checks if RankMath exists instead of just passing the content (like [here](https://github.com/Codeinwp/otter-blocks/blob/master/src/blocks/blocks/posts/components/layout/index.js#L177)) through the filter?

Even if RankMath isn't active, I think, the filter shouldn't do any harm.

**Comment by Soare-Robert-Daniel** [comment]
The advantage of the current technique is that it can be separated into individual scripts and used with other blocks that may need math rank support. Also, using the HTML that gets the entire final structure frees us from maintaining it when doing structural changes.

Also, the function that gets the content and adds it to the filter must be initialized once. As mentioned before, putting this inside the components was not working the way I liked -- too much management for such little value.

**Comment by HardeepAsrani** [comment]
@Soare-Robert-Daniel Okay, that is a way to go but I'm not much confident about this line

`const rankMathScript = document.querySelector( 'script[src*="rank-math-app"]' );`

Can't we at least have a better detection that to look for the script in DOM? They might change the name, or have a different name in Pro version and so on. If any of that happens, we won't be aware that the integration doesn't work.

**Comment by Soare-Robert-Daniel** [comment]
@HardeepAsrani, we can remove that and just use the interval checker for the global value.

**Review by HardeepAsrani — APPROVED** [review]

**Comment by rodica-andronache** [comment]
@Soare-Robert-Daniel tested and everything's working well 👍

**Pull request merged**
