### PR TITLE
Fix popup padding on mobile

### LINKED ISSUE #1546: Pop-up content not visible on mobile devices
### Description

The pop-up works fine on Desktop but the content is not visible on mobile devices. The height of the pop-up is low and most of it is limited and most of it is occupied by same padding, content being visible through a thin line.

### Step-by-step reproduction instructions

1. Add a pop-up
2. Put some content in it
3. Open the page on a mobile device - it's not replicable in the browser responsive mode, only on actual device, or probably on BrowserStack also.

An example here, there is a button with the text "Anchor" that opens a pop-up with a heading element.

http://neve.stefancoti.com/otter-page/

### Current behavior

IMG_2358

### Expected behavior

Markup on 2023-03-08 at 11:56:09

https://secure.helpscout.net/conversation/2176801845/360815/

_P.S. About the regression question, I don't know if it worked properly before, never tested it on a mobile device._

### Environment info

WordPress 6.1.1
Otter: 2.2.3

### Is the issue you are reporting a regression

No

### PR DESCRIPTION
**Pull request by Soare-Robert-Daniel**
Closes #1546.

### Summary

Swap the padding from the header to the content modal. This way it will make space for the `overflow`.

### Screenshots 

Before:

image

After:

image

----

### Test instructions

1. Add popup block.
2. Add some content with a big Heading at the begging.
3. Check if it is ok on mobile

---- 

### Checklist before the final review

- [x] Visual elements are not affected by independent changes.
- [x] It is at least compatible with the [minimum WordPress version](https://wordpress.org/plugins/otter-blocks/).
- [x] It loads additional script in frontend only if it is required.
- [x] Does not impact the [Core Web Vitals](https://web.dev/vitals/).
- [x] In case of deprecation, old blocks are safely migrated.
- [x] It is usable in Widgets and FSE.
- [x] Copy/Paste is working if the attributes are modified.

### CODE REVIEW

**Review by HardeepAsrani — APPROVED** [review]

**Comment by irinelenache** [comment]
@Soare-Robert-Daniel Tested and the issue is not fixed for me, maybe i missed something
The issue persists on mobile (Tested on real Iphone 11 and on Browserstack) and also on Safari desktop https://vertis.d.pr/i/803blG

You can check here:
```
 Admin area URL: https://hookupsellneve.s2-tastewp.com/2023/03/10/popups/
 Username: irinel 
 Password: OvmmrG-4dhc 
```

**Comment by Soare-Robert-Daniel** [comment]
Thanks, @irinelenache. It seems that Safari `overflow` is not very smart. 

@HardeepAsrani, we need to establish a minimum height for the modal body to tackle Safari.

Chrome: 

image

Safari:

Screenshot 2023-03-10 at 11 32 32

The `fit-content` property on height is not a good option for Safari:

https://github.com/Codeinwp/otter-blocks/blob/0a4828c7821180b35c72904ab49d54483eea2443/src/blocks/blocks/popup/style.scss#L18-L20

This was introduced at this request: https://github.com/Codeinwp/otter-blocks/pull/1261#issuecomment-1290647932

Should we return to the previous options of setting the height as `400px`?

**Comment by HardeepAsrani** [comment]
@Soare-Robert-Daniel Instead of content-fit, can you test height as `auto` and see how it works compared to 400px and content-fit?

**Comment by Soare-Robert-Daniel** [comment]
@HardeepAsrani `auto` works well 👌

**Review by HardeepAsrani — APPROVED** [review]

**Comment by irinelenache** [comment]
@Soare-Robert-Daniel Tested again and now the issue is fixed, thank you 👍

**Pull request merged**
