### PR TITLE
Fix typing slowness

### LINKED ISSUE #799: Slow Typing after adding multiple blocks (seems to need optimization)
When using multiple blocks whilst being on the latest version, you will start encountering slow typing in the Edit mode. I tried narrowing it down to a number of blocks to be used until you encounter this issue and it got me to approximately 20 blocks (more or less) for a new page.

If I try the same method on an already existing page, then the number decreases to about 5.

This issue was reported by one of our users and we initially thought it was an edge case but I think it has something to do with some optimization issue as I could replicate it multiple times on multiple instances.

Steps to reproduce:

1) Install the latest version of Otter
2) Edit an existing page (or create a new one but you'll need to add more blocks)
3) Start adding Otter Blocks to the said page
4) At some point, you'll notice that if you try to write (name a button, paragraph, heading etc) there is a noticeable delay from the moment you type on the keyboard to when the letters actually appear in the block

Expected behavior:
No delay from the input

Current Behavior:
Noticeable delayed text input

Reference:
[User Reported Here](https://secure.helpscout.net/conversation/1813047537/313355?folderId=212390)
[Screencast showing the current behavior after adding 5 new Otter blocks to an existing page](https://vertis.d.pr/spZl3B)

Testing instance:
User: admin
Pass: r6y7olamFiSYQGAjVLy9St)F
Website: https://spottedsun.s2-tastewp.com/wp-admin

Environment:
WP Version:5.9.2
Otter Version: 2.0.1

### PR DESCRIPTION
**Pull request by Soare-Robert-Daniel**
Closes #799 .

### Summary

The Condition Inspector is triggering for every block, thus any computation becomes expensive. This update will make sure that the data is done only when needed. Also, I suspect that the useSelect was doing synchronization with the global store, thus the _indirect_ overhead in the Profiler for `onStoreChange`.

@HardeepAsrani @selul @Skystream96 @preda-bogdan @abaicus feel free to take a look.

### Screenshots 

The site was tested with the following query: `new QueryQA().select('blocks').run()` which puts all the block template available (more than 70 blocks in total).

**Performance result**

Current version:
Screenshot 2022-07-06 at 13 50 31

As you can see, a lot of red dots indicated a huge load with like a 100ms computation time per typing.

Updated: 

No more red dots. 30 ms computation time per typing. _So 3x increase in performance._

Screenshot 2022-07-06 at 13 49 52

----

#### Query
```javascript
new QueryQA().select('blocks').run()
```

---- 

### Checklist before the final review

- [ ] Visual elements are not affected by independent changes.
- [ ] It is at least compatible with the [minimum WordPress version](https://wordpress.org/plugins/otter-blocks/).
- [ ] It loads additional script in frontend only if it is required.
- [ ] Does not impact the [Core Web Vitals](https://web.dev/vitals/).
- [ ] In case of deprecation, old blocks are safely migrated.
- [ ] It is usable in Widgets and FSE.

### CODE REVIEW

**Comment by selul** [comment]
Awesome 🚀

**Comment by irinelenache** [comment]
@HardeepAsrani @Soare-Robert-Daniel I checked how it behaves with lots of blocks and keeping the editor open for a longer period of time and i didn't encounter any slowness now 🚀

**Comment by irinelenache** [comment]
@HardeepAsrani I checked again and found a small issue. When i select the **Post category** visibility condition, the dropdown with the existing categories is not opening https://vertis.d.pr/7Iu538

**Comment by HardeepAsrani** [comment]
@Soare-Robert-Daniel Can you look to it?

**Comment by Soare-Robert-Daniel** [comment]
If we call the function from the `select` before the component initialization it might not return the correct output. 

@irinelenache the problem is solved.

**Comment by Soare-Robert-Daniel** [comment]
@HardeepAsrani getting the info about posts is a bit tricky since the data is not always available. Sometime you get it immediately, sometime after 3-5 seconds.

I have added a timer to retrieve the data when is ready.

@irinelenache I have updated that test site 🚀

**Comment by preda-bogdan** [comment]
@Soare-Robert-Daniel I don't think using a wait time of X seconds is a good practice. Also, you need to clean up the `Promise` and the `setInterval` when using `useEffect`.

**Comment by Soare-Robert-Daniel** [comment]
@preda-bogdan, I added a lock in case of possible multiple calls. But I got no idea how to remove the setTimeout, I don't know a reliable function that tells me when the store is ready.

**Comment by HardeepAsrani** [comment]
@preda-bogdan We're making some changes and will let you know how it goes, thanks for the input. We decided to split the parts that were making useSelect calls into separate components to avoid making those calls at all unless the user has those selected and is editing them.

Hope it goes well. 😄

**Comment by Skystream96** [comment]
Hey @HardeepAsrani ,

I managed to test too and I can see the improvement now. Also, the visibility conditions seem to work fine including the Post Category that @irinelenache was mentioning before.

As far as this PR is concerned I think we are good to go.

@irinelenache would you agree?

Thank you guys for all the hard work and for making this fix possible!

**Comment by irinelenache** [comment]
Thank you @Skystream96 , this can be moved to **Ready to merge** now 🚀

**Comment by HardeepAsrani** [comment]
@Soare-Robert-Daniel Pro conditions aren't working anymore, they just keep loading without ever showing the field.

**Comment by HardeepAsrani** [comment]
@Soare-Robert-Daniel This happens when you don't have any Woo products set, so it should not show loading once the products have loaded even if none exist.

**Review by HardeepAsrani — APPROVED** [review]

**Pull request merged**
