### PR TITLE
Fix Tab block issue with Masonry and Slider

### LINKED ISSUE #832: Masonry doesn't work inside Tabs
If you put Masonry inside Tabs, it doesn't work.

### PR DESCRIPTION
**Pull request by Soare-Robert-Daniel**
Fix #832 

Add fixes for https://github.com/Codeinwp/otter-blocks/pull/800#issuecomment-1081631824

### CODE REVIEW

**Comment by HardeepAsrani** [comment]
While @irinelenache does a review, can you remove the console.log from the code?

**Review by arinaturcu — COMMENTED** [review]
@Soare-Robert-Daniel The part related to the tabs seems good to me :rocket:

**Comment by Soare-Robert-Daniel** [comment]
@irinelenache, you can re-check.

**Comment by irinelenache** [comment]
@Soare-Robert-Daniel Tested again and now everything works fine, thank you 🚀

**Review by HardeepAsrani — CHANGES_REQUESTED** [review]
@Soare-Robert-Daniel Masonry still doesn't work if you use it inside the WooCommerce Product Tabs feature of Neve Pro.

**Comment by Soare-Robert-Daniel** [comment]
@HardeepAsrani, Masonry is working for me in WooCommerce Product Tabs.

**Review by HardeepAsrani — APPROVED** [review]

**Comment by HardeepAsrani** [comment]
@Soare-Robert-Daniel Seems to working now, must have been cache from my side . Thanks

**Pull request merged**
