### PR TITLE
Development

### PR DESCRIPTION
**Pull request by HardeepAsrani**
- https://github.com/Codeinwp/otter-blocks/issues/1842 - [tested Rodica]
- https://github.com/Codeinwp/otter-blocks/issues/1665 - [In testing - Irinel]
- https://github.com/Codeinwp/otter-internals/issues/98 - [Tested - Irinel]
- https://github.com/Codeinwp/otter-blocks/issues/1843 - [Tested - Irinel]
- https://github.com/Codeinwp/otter-blocks/issues/1717 - [Tested - Irinel]
- https://github.com/Codeinwp/otter-internals/issues/91 - [Tested - Irinel]
- https://github.com/Codeinwp/otter-blocks/issues/1880
- https://github.com/Codeinwp/otter-blocks/issues/1882 - [Tested - Irinel]
- https://github.com/Codeinwp/otter-blocks/issues/1871 - [Tested - Irinel]
- https://github.com/Codeinwp/otter-blocks/issues/1876 - [Tested - Irinel]
- https://github.com/Codeinwp/themeisle/issues/1575 - [Tested - Irinel]

### CODE REVIEW

**Comment by HardeepAsrani** [comment]
@Codeinwp/qa-team Can we do a pre-release QA on this? We want to release this alongside with BF deals so it will be great to prioritize this if no other major release is being QA'd right now.

**Comment by irinelenache** [comment]
@HardeepAsrani 

- [ ] The live search style is broken when it's added in the Pop-up. The results are there but they are not visible https://vertis.d.pr/v/TpPjEA (I added this line `do_action( 'otter_load_live_search_deps' );` in functions.php)

**Comment by rodica-andronache** [comment]
@irinelenache regarding the Maps issue, it's happening to me too, after importing a starter site. Where the maps block has a "400pxpx" height

**Comment by Soare-Robert-Daniel** [comment]
> * [ ]  The live search style is broken when it's added in the Pop-up. The results are there but they are not visible https://vertis.d.pr/v/TpPjEA (I added this line `do_action( 'otter_load_live_search_deps' );` in functions.php)

> * [x]  If i have both Otter and Neve installed, the priority for the global notice will go to Neve, but should the Otter notice be visible after the Neve one was dismissed? Right now that's not happening.

This is the correct behavior. 

> * [x]  I had [this issue](https://vertis.d.pr/i/c8O0rn) when i added a default Maps block in the sidebar but i'm not able to reproduce it again, i'm posting it to make sure it's not related to something bigger

Added a smarted checking 🔧  Also, @irinelenache can you tell me what startersites do this? Is it possible that it might be some wrong values?

> * [x]  The AI block is available only if you have the administrator role. If you use another role, the block will ask for an API key and it won't work even if the key is valid or not https://vertis.d.pr/v/jLdi3r

Now AI Block will be available to use for non-admin users. But the key must be already set.

**Comment by Soare-Robert-Daniel** [comment]
@irinelenache you can find the fix here: https://github.com/Codeinwp/otter-blocks/pull/1928

**Comment by irinelenache** [comment]
@Soare-Robert-Daniel 
✔️ The AI block issue is fixed now

> Added a smarted checking 🔧 Also, @irinelenache can you tell me what startersites do this? Is it possible that it might be some wrong values?

^ It happened using any starter site, i just changed the settings in order to make the sidebar visible and added the block. The PR did not fix this issue, you can check on this instance:
```
 Admin area URL: https://finalizeburst.s2-tastewp.com/wp-admin 
 Username: irinel 
 Password: R3ceDl322ys 
```

**Comment by Soare-Robert-Daniel** [comment]
> ^ It happened using any starter site, i just changed the settings in order to make the sidebar visible and added the block. The PR did not fix this issue, you can check on this instance:

It seems that when loaded with customizer in the sidebar, the leaflet otter CSS is missing and the Leaflet might try to extract the height itself, thus creating the weird artifact like `style="height: 400pxpx` when we have to code that directly sets the height to the element. 

This will be a separate issue.

**Comment by irinelenache** [comment]
@Soare-Robert-Daniel @HardeepAsrani Thank you for checking & fixing the issues 🚀 

Everything's fine regarding the release ✅

**Pull request merged**
