### PR TITLE
Section Enhancements

### LINKED ISSUE #1239: Add Color & Overlay to Otter's section Columns
### Description:

At this point having both **Background color** and **Overlay**, it's possible only on the Section block.
It would help to also have this option for the Columns inside the section.
Screenshot 2022-10-03 at 17 57 34

___
For example in this Section from our site, the right side can't be reproduced using the current build (a solid bg + img overlay):
image

### PR DESCRIPTION
**Pull request by HardeepAsrani**
Closes #1239.

### Summary

- Adds Background Overlay to Section's Column.
- Change Section's Maximum Width and Height control to Unit from RangeControl
- Add Background Hover & Text Controls
- UI Changes
- Add Vertical Alignment option to Column
- Fix Shape Divider not working properly

### Screenshots 

----

### Test instructions

Make sure it works fine and is backward-compatible without breaking anything, as well as general well being of the Section block.

---- 

### Checklist before the final review

- [ ] Visual elements are not affected by independent changes.
- [ ] It is at least compatible with the [minimum WordPress version](https://wordpress.org/plugins/otter-blocks/).
- [ ] It loads additional script in frontend only if it is required.
- [ ] Does not impact the [Core Web Vitals](https://web.dev/vitals/).
- [ ] In case of deprecation, old blocks are safely migrated.
- [ ] It is usable in Widgets and FSE.

### CODE REVIEW

**Comment by HardeepAsrani** [comment]
@mghenciu You can take a look at the changes when you've time and let me know of your feedback.

**Comment by irinelenache** [comment]
@HardeepAsrani Tested and here is what i found so far:

- [ ] I created a section block with some random settings and i got this fatal error in frontend https://vertis.d.pr/i/lYq1EI
- [ ] The shape divider width and height don't work in frontend 
editor: https://vertis.d.pr/i/uQDNxL
frontend: https://vertis.d.pr/i/AOcuxM
- [ ] The text and link color are applied only in frontend https://vertis.d.pr/i/Dbr8W0
- [ ] Some other things like column settings and box shadow are not updating, i guess this is happening because of the first issue, i don't get the CSS updated notice in the editor anymore

You can check the issues here:
```
URL : https://sections.vertisite.cloud/
Username : litizuliko8895
Password : 09JZEKQTRmSw1HPoaNc8
```

**Comment by HardeepAsrani** [comment]
@irinelenache The first three issues should be fixed. Make sure you don't use a comma in width/height, as I see in your screenshot.

For the fourth, we don't force the color to text. Neve is already applying some color to text in the editor so that's why it appears black regardless. Nothing we can do here.

**Comment by HardeepAsrani** [comment]
@irinelenache When you test on Monday, I've also added Vertical Alignment to Column so make sure to check that. It should inherit Vert Alignment of Section if not set.

**Comment by irinelenache** [comment]
@HardeepAsrani Tested and the isssues are fixed, thank you 🚀 

Found something else, related to the vertical alignment added:

- [ ] The columns size is different in editor and frontend, based on how the vertical alignment is used

   section when no alignment is used, editor: https://vertis.d.pr/i/36HSGu
   section when no alignment is used, frontend: https://vertis.d.pr/i/6vKFRf

   section when center alignment is used, editor: https://vertis.d.pr/i/d5wEIJ
   section when center alignment is used, frontend: https://vertis.d.pr/i/sYNrEE

You can check it here:
```
 Admin area URL: https://sections-fix.s1-tastewp.com/wp-admin
 Username: irinel 
 Password: Es0xTpDF6tk 
```

**Comment by HardeepAsrani** [comment]
> For the Background & Background Overlay, in Figma there are separate Panels - as each of those settings are quite complex. So I suggest we keep it that way, using separate Panels.

@mghenciu I've kept them in same panel because we're using the new panel control so everything is inside the Popover. Having a separate component will just end up being the Panel having a single control.

**Comment by HardeepAsrani** [comment]
>  The columns size is different in editor and frontend, based on how the vertical alignment is used

That's not an issue with the new one and has been working like this so far. I suppose it's not the best but will take some looking into it. I'll do it separate from this PR. Thanks for the report.

**Comment by HardeepAsrani** [comment]
> I am not sure what this control should do. I tried applying it on the section, but without an effect:

Should work better now. It doesn't work in Editor with Neve because Neve adds its own color and we don't force the color on text, only if it inherits.

**Comment by HardeepAsrani** [comment]
I've added the responsive controls for max width too. Let me know if there's anything else.

**Comment by irinelenache** [comment]
@HardeepAsrani Checked again and found a single problem, regarding the responsive max width:
This is how it looks in editor: https://vertis.d.pr/i/74oNSS
This is how it looks in frontend: https://vertis.d.pr/i/b1X8B0

After this is fixed and @mghenciu approves it too, i think we can move it to **Ready to merge** 🚀

**Comment by irinelenache** [comment]
@HardeepAsrani The last issue is fixed, thank you 🚀 No other findings on my end ✅

**Comment by HardeepAsrani** [comment]
Thanks @irinelenache. Waiting for heads up from @mghenciu before merging it.

**Comment by mghenciu** [comment]
Looks good Hardeep, didn't found any issues.

Just a few questions:

- is it normal that when switching between devices (Desktop -> Tablet/Mobile and reverse), the selected Tab is always Layout, even if I was originally in the Style Tab?

https://user-images.githubusercontent.com/52494172/200197719-598f2607-8d27-47ff-b232-0784ebdb1fb1.mov


___
- after the merges, all the Labels will be with Caps? including ours
I am asking this to be consistent with the ones from Core (an example below)
Screenshot 2022-11-07 at 00 01 14

___
- This was happening to me with the Background Popup selector, on Chrome latest version:


https://user-images.githubusercontent.com/52494172/200198112-bb81bb0f-a0f4-466b-a5af-cd82fce1d613.mov


___
Is there any reason for using Layout Tab instead of **Settings**?
It may sound better, but for consistency reasons - probably we should keep Settings, as we do for all blocks.

**Comment by HardeepAsrani** [comment]
> is it normal that when switching between devices (Desktop -> Tablet/Mobile and reverse), the selected Tab is always Layout, even if I was originally in the Style Tab?

Yes, that's from Core. Can't do anything.

> Is there any reason for using Layout Tab instead of Settings?

It was there from beginning so didn't notice the label much. Thanks.

Will check the rest.

**Comment by HardeepAsrani** [comment]
Fixed the rest, I'll merge it now and we can fix if there are any other issues while it's out for the final release QA. Thank you all for finding the issues.

**Pull request merged**
