### PR TITLE
Add Float mode for Sticky Blocks

### LINKED ISSUE #1139: Add float mode to Sticky
### Description:

A feature to allow some block/section to float to top/bottom always, regardless if the item has been scrolled or not. And a detection to notify user when more than one item has the same settings.

### PR DESCRIPTION
**Pull request by Soare-Robert-Daniel**
Closes #1139.

### Summary

- Add controls

#### Controls

Make block active

There is already an active block on the page

There are multiple active blocks on the page

----

### Test instructions

1. Make some blocks sticky.
2. Activate `Always Active` in one of them.
3. The rest should have the option deactivated since only one can always be active.

If you encounter any problems, please post the test instance. Sticky is very sensitive about the setup.

---- 

### Checklist before the final review

- [ ] Visual elements are not affected by independent changes.
- [ ] It is at least compatible with the [minimum WordPress version](https://wordpress.org/plugins/otter-blocks/).
- [ ] It loads additional script in frontend only if it is required.
- [ ] Does not impact the [Core Web Vitals](https://web.dev/vitals/).
- [ ] In case of deprecation, old blocks are safely migrated.
- [ ] It is usable in Widgets and FSE.

### CODE REVIEW

**Comment by HardeepAsrani** [comment]
@Soare-Robert-Daniel Seems nice, you don't need to show the help text unless it's a child block then you can show the help text about it needs to be a parent block + disable the control. Same goes with multiple blocks being sticky.

**Comment by Soare-Robert-Daniel** [comment]
The sticky script has been refactored to a more singular approach. Instead of independent functions that run with their event and try to synchronize each time with an external object that acts as a mediator, a [pseudo-ECS-oriented](https://www.simplilearn.com/entity-component-system-introductory-guide-article) approach has been used. 

Now each sticky element is represented as a data class with `StickyData`. A `StickyRunner` will loop through the sticky elements two times. One time to update the data of each `StickyData` and a second time to align the HTML element based on the processed data.

Now the implementation of the sticky should be more straightforward.

**Comment by HardeepAsrani** [comment]
@Soare-Robert-Daniel Do we have the Indicator on the Backend for which element is Sticky like we do for Visibility Conditions?

**Comment by Soare-Robert-Daniel** [comment]
> @Soare-Robert-Daniel Do we have the Indicator on the Backend for which element is Sticky like we do for Visibility Conditions?

You can check the `className` for `o-sticky` and `o-sticky-float` (for floating blocks)

**Comment by HardeepAsrani** [comment]
@Soare-Robert-Daniel If I put a Section Block in Full Width with a Countdown, it doesn't stay full width. The width option can be empty by default.

We want to be able to create things like this: https://www.growthmarketingpro.com/wp-content/uploads/2018/12/hellobar.png

**Comment by Soare-Robert-Daniel** [comment]
I made the tweak. Now the default `width` is 100%.

If you set the section/group/column width to `Full width` and the Side Offset to 0, you will get that full viewport sticky element.

https://user-images.githubusercontent.com/17597852/187852639-33400837-0f01-4409-ac99-4fd00468005a.mp4

**Comment by HardeepAsrani** [comment]
@Soare-Robert-Daniel If it's ready then we can put it for QA. We should see how things look in the mobile in testing, and also that it is backward compatible.

**Comment by irinelenache** [comment]
@Soare-Robert-Daniel Tested the feature and here are my findings:

- [ ] Is it expected to be able to add values bigger than 100% in the **Width** control? https://vertis.d.pr/jnHiKP
- [ ] I tried to change the **Side to Stick** for a section but nothing changes for me in frontend https://vertis.d.pr/Finq12
- [ ] On mobile, the floating content will get under the header https://vertis.d.pr/XNZCf3

⚠️ Testing is not complete, I still have to do some testing on more browsers/devices. Also, sometimes the floating controls don't work until i do a hard refresh in the editor, it may be related to some caching problems

**Comment by Soare-Robert-Daniel** [comment]
> * [ ]  Is it expected to be able to add values bigger than 100% in the **Width** control? https://vertis.d.pr/jnHiKP

Yes. The sizing is not very consistent on the float mode. And 100%, is not the entire page or port view, is just the original width in which the element was placed initially. That's why is good to have the option to tweak the size as much as you want.

> * [ ]  On mobile, the floating content will get under the header https://vertis.d.pr/XNZCf3

As it should be. You need to set an offset to prevent that. We can not go over the menu, it will be a big problem since you will not be able to access it.

**Comment by Soare-Robert-Daniel** [comment]
> * [ ]  I tried to change the **Side to Stick** for a section but nothing changes for me in frontend https://vertis.d.pr/Finq12

Should work now. `Side to Stick` for blocks will `Full Align` were a special case. Now it should work if the `Width` is less than `100%`

Example:

`100%`

image


`50%`

image

**Comment by irinelenache** [comment]
@Soare-Robert-Daniel Did another round of testing, here is what i found:

- [ ] The **Enable on mobile** setting can't be deactivated https://vertis.d.pr/ALReOI
- [ ] When i'm making changes to the **Side offset**, the Screen offset value will reset to default https://vertis.d.pr/jU4tj2

I tested on more devices/browsers and the feature seems to work fine in frontend 🚀

**Pull request merged**
