### PR TITLE
Pro patterns

### PR DESCRIPTION
**Pull request by HardeepAsrani**
Closes #.

### Summary

This adds Pro patterns to Otter. We can test them first and then also add few of these to Otter free with some sort of promotional mechanism.

Can you help with the testing @JohnPixle @mghenciu?

### Screenshots 

----

### Test instructions

If you install just Otter free, you should see Upsell notices on all the Otter Patterns once you insert them. If one disable it once then it won't show again in the editor session.

If you dismiss them in 3 sessions, they won't appear again for a month. You can clear browser storage to make them appear again. Run this in the console:

`window.localStorage.clear();`

And if you install Otter Pro & activate the license, you should start seeing new Patterns from Otter Pro: https://demosites.io/otter/pro-patterns/

---- 

### Checklist before the final review

- [ ] Visual elements are not affected by independent changes.
- [ ] It is at least compatible with the [minimum WordPress version](https://wordpress.org/plugins/otter-blocks/).
- [ ] It loads additional script in frontend only if it is required.
- [ ] Does not impact the [Core Web Vitals](https://web.dev/vitals/).
- [ ] In case of deprecation, old blocks are safely migrated.
- [ ] It is usable in Widgets and FSE.
- [ ] Copy/Paste is working if the attributes are modified.

### CODE REVIEW

**Comment by mghenciu** [comment]
@HardeepAsrani , could you please provide the exact testing flow?
I've tried on this instance: https://kemon-yoga-loxi.instawp.xyz/ | gegufakile0139 | J83LSy7rWjmuni4NQfPO

using the Dev Build from above for Otter Free & Pro, but I am not sure where [this Pro Patters](https://demosites.io/otter/pro-patterns/) should appear.

**Comment by HardeepAsrani** [comment]
@mghenciu It's in the Pattern inserter along side the free patterns so that you can search by the name. Here's a list of all the patterns: https://github.com/Codeinwp/otter-blocks/blob/pro-patterns/plugins/otter-pro/inc/plugins/class-patterns.php#L40

**Comment by mghenciu** [comment]
@HardeepAsrani , I tried testing again on this instance, initially using the Dev Free and then added the Dev Pro build, **but without success.** For example I tried searching for the Slider and Contact form patterns, and couldn't find the patterns I've created in the results.
https://ternet-jam-befe.instawp.xyz/wp-admin | bugijuruve8372 | IQpYXwixeUnaNO27tP8g

___
I noticed there are cases when the Testing flow is missing/incomplete, for example in this case isn't clear if we have to install Otter Pro or Free, or both.  In the future, it would help to avoid cases like this, where the someone is spending time just trying to make the test run, but without success.

**Comment by HardeepAsrani** [comment]
@mghenciu I don't see any issue with your setup; it should work normally. I'll check on my side to see if something is failing here

**Comment by mghenciu** [comment]
Overall looks good, Hardeep. Nice job!

Just some things I noticed (nothing deal breaking):

 **Pricing with a Single Plan**
 The Overline Text is with Serif in Preview, even though in the Pattern itself - it's Sans Serif.
Same thing for the **three-pricing-columns-with-shadow**, where the Prices are Serif in preview. I think the issue here is the fact that those ar Spans, instead of `<P>`
 
Screenshot 2022-12-15 at 17 13 19

___
**Contact Form with a Full-width Map**
There's a 20px Top & Bottom margin. Ideally that margin shouldn't be present: 
Screenshot 2022-12-15 at 17 21 04


___
**Two Columns Subscribe Form**
The Privacy Text is Centered (in backend), while in the Original Pattern, it should be **Left aligned**:
Screenshot 2022-12-15 at 17 28 20

___

**Four Columns with Numbers and Text over Dark Background**
There looks to be a Classic block inside of this pattern:
Screenshot 2022-12-15 at 17 30 48

___
**Centered Testimonials with Stars**
Not sure if this is expected (space between stars), when using Neve:
Screenshot 2022-12-15 at 17 32 18

Same thing for the Author Box
Screenshot 2022-12-15 at 17 33 21


___ 
For this one (Grid Portfolio with Two Columns and a Description), **I removed the Spacers** between the Image and Names, because it was way too big with some themes:
image

___
**Paragraphs `(<p>)` bottom margin**
It looks like in Otter Section columns, `<p>` don't get the default margin-bottom, as they do in Core. Which may result in issues like this (text is too close to the button): 
Screenshot 2022-12-15 at 17 41 47

___
For the Product Review in Twenty Twenty-Two, should I do something special to make the text work (hardcore it to #fff)?
image

___
Testing Instance:
https://wildebeest-kula.instawp.xyz | fadicicita7958 | OCv96AZIYHJUoNg1RkWE

**Comment by HardeepAsrani** [comment]
- Using Cache in Dynamic Conditions

 > Pricing with a Single Plan

This happens because of how styles are being added to the editor. It's very small and I had to really zoom in to notice the difference so I think we can ignore this.

> Contact Form with a Full-width Map

Fixed.

> Two Columns Subscribe Form

It's happening due to editor styles, don't know why these are there in the first place but we can't do anything about it.

> Four Columns with Numbers and Text over Dark Background

Fixed.

> Centered Testimonials with Stars

I see this is only happening in Preview of the Pattern and we can't really do much there, also it's a Core block and not being caused by our side.

> Grid Portfolio with Two Columns and a Description

Updated.

> Paragraphs (<p>) bottom margin

It does work fine on my end.

> Product Review

I suppose we can have a hardcoded text color given the background is hardcoded.

> @HardeepAsrani We are still planning to add a "Pro label" to our "Pro" patterns in the inserter as discussed, right?

We will but this PR will be mostly for releasing the patterns first.

Also, I've updated all the Pro patterns to make sure they work with 5.9 to use older block options that were available in 5.9. 3 Patterns will only work in 6.0 or 6.1 but rest work fine as back as 5.9

**Comment by ineagu** [comment]
@HardeepAsrani Not sure who need to test here, would be great if we can test and ship it, along with some minimal at least pro labeling. While might seem minor or technically boring, I think it would be super helpful.

**Comment by HardeepAsrani** [comment]
Thanks for the tests and feedback, I've implemented the Templates Cloud mechanism here and we can merge it after this has been merged: https://github.com/Codeinwp/templates-cloud/pull/52/

**Comment by mghenciu** [comment]
Here's the suggested list with **Pro Patterns to be included in Free** (based on uniqueness and usefulness):
image

___
image
___
image

___
image

___
 
image

**Comment by HardeepAsrani** [comment]
Posting the video here as well for record keeping: https://www.loom.com/share/3f61d0fed3a945b3bad974fbfc7b265e

**Comment by irinelenache** [comment]
@HardeepAsrani Tested the enhancements and everything's fine on my end, good job 🚀

**Pull request merged**
