### PR TITLE
Form Layout Generation 🚀 

### PR DESCRIPTION
**Pull request by Soare-Robert-Daniel**
Closes #.

### Summary

Add a new block that lets you generate a Form block.

Available actions:

- Generate: generate the form based on the given prompt. Add the generated Form to a history list. (The history list allows you to navigate through generate Forms in the prompt editor)
- Replace: replace the AI Block/Prompt Editor with the generated form and end the process.
- Insert below: insert the generated form below the Ai Block/Prompt Editor.
- Regenerate: the prompt is sent again, with a more significant variation. The newly generated Form will replace the current one in the preview (meaning there is no change in the history - if you generate three forms, and in one of them you press `Regenerate`, you still have three forms. -- same behavior as in ChatGPT). ⚠️ Pretty unstable since the base prompt is not very good. 

ℹ️ Form Block now has a shortcut in the toolbar. When you press it, it will automatically create the AI Block. Do not confuse it with the fact it influences the Form; it is not an extension. It is something independent.

### Screenshots 

https://github.com/Codeinwp/otter-blocks/assets/17597852/343749ae-e039-4870-a026-5bf3d1b9223c

----

### Test instructions

:warning: You will need an Open AI API Key. You can use this one [Open AI Key](https://github.com/Codeinwp/otter-internals/issues/82#issuecomment-1630642026).

Test if everything is alright, like in the video.

⚠️ Sometimes, OpenAI will give an empty form. If you press `Generate` or `Regenerate`, the preview section will see something that asks for a Form variation; this is why it appears.

---- 

### Checklist before the final review

- [ ] Visual elements are not affected by independent changes.
- [x] It is at least compatible with the [minimum WordPress version](https://wordpress.org/plugins/otter-blocks/).
- [x] It loads additional script in frontend only if it is required.
- [x] Does not impact the [Core Web Vitals](https://web.dev/vitals/).
- [x] In case of deprecation, old blocks are safely migrated.
- [x] It is usable in Widgets and FSE.
- [x] Copy/Paste is working if the attributes are modified.
- [x] PR is following [the best practices]()

### CODE REVIEW

**Review by HardeepAsrani — APPROVED** [review]
LGTG, before the release we can also work out on adding some link to docs when we have those ready. Good work.

**Comment by rodica-andronache** [comment]
@Soare-Robert-Daniel everything's working well 👍 great work 🚀

**Comment by HardeepAsrani** [comment]
@Soare-Robert-Daniel Can you replace the URL with the staging one and test to confirm it works good? If yes then we can deploy that to production and put the final URL.

**Comment by HardeepAsrani** [comment]
@Soare-Robert-Daniel Can you fix the merge conflicts?

**Pull request merged**
