### PR TITLE
Development

### PR DESCRIPTION
**Pull request by HardeepAsrani**
- https://github.com/Codeinwp/otter-blocks/issues/1600
- https://github.com/Codeinwp/otter-blocks/issues/1676
- https://github.com/Codeinwp/otter-blocks/issues/1677
- https://github.com/Codeinwp/otter-blocks/issues/1486
- https://github.com/Codeinwp/otter-blocks/issues/1680
- https://github.com/Codeinwp/otter-blocks/issues/1667
- https://github.com/Codeinwp/otter-blocks/issues/1703
- https://github.com/Codeinwp/otter-blocks/issues/1702
- https://github.com/Codeinwp/otter-blocks/issues/1572
- https://github.com/Codeinwp/otter-blocks/issues/1540
- https://github.com/Codeinwp/otter-internals/issues/93
- https://github.com/Codeinwp/otter-blocks/issues/1712
- https://github.com/Codeinwp/otter-internals/issues/88

### CODE REVIEW

**Comment by rodica-andronache** [comment]
- [ ] Regarding [this](https://github.com/Codeinwp/otter-blocks/issues/1540) if you add any Otter block, enable _Visibility conditions_, click on add **Rule Group** , select **Post Author** as Condition and type anything. The block breaks https://vertis.d.pr/v/gvRemj

**Comment by rodica-andronache** [comment]
- [ ] Regarding [this](https://github.com/Codeinwp/otter-blocks/issues/1676), if you first use Otter free and create a form, with Email Only ( as that is the only option available ), and install Otter Pro, the option is updated to Database & Email for that form too. Not sure is correct or not. I thought that the Database & Email default value should apply just for new forms

**Comment by HardeepAsrani** [comment]
Regarding the form submission default one, I’d take @Codeinwp/design-team’s opinion. For me, Email & Submission becomes the new default. What do you both think about the flow?

**Comment by HardeepAsrani** [comment]
@rodica-andronache While we get a feedback from design team, did you find any other issues?

**Comment by rodica-andronache** [comment]
- [ ] For the Forms block, when you are using a _File_ field, and **Save to Media Library** is NOT enabled , the image from the Form Submissions is not working anymore https://vertis.d.pr/v/aXWTKP
- [ ] Noticed that the first field of Form Submissions changed. Right now, is Submission #123, compared to how it was before, when it showed the email. Is that correct? https://vertis.d.pr/i/X3FLiJ

**Comment by HardeepAsrani** [comment]
>  Noticed that the first field of Form Submissions changed. Right now, is Submission no.., compared to how it was before, when it showed the email. Is that correct? https://vertis.d.pr/i/X3FLiJ

Yea, it was part of https://github.com/Codeinwp/otter-internals/issues/88

**Comment by Soare-Robert-Daniel** [comment]
@rodica-andronache, the mentioned bugs have been fixed 🔧 .

**Comment by mghenciu** [comment]
> Regarding the form submission default one, I’d take https://github.com/orgs/Codeinwp/teams/design-team’s opinion. For me, Email & Submission becomes the new default. What do you both think about the flow?

Indeed, it's an action that users didn't required - **but it's a way of promoting Otter Form Submissions** and having a more easier way of viewing the entries directly inside WP. So I would say this should be fine, since we are adding more value and not downgrading or affecting the UX.

But generally speaking, this shouldn't reset/affect the other configurations made by the user. 

And since we are talking about this, what will happen with my submissions if I cancel my subscription or subscription expires or delete Otter Pro?
Will it revert to Email only? are the submissions still available?

**Comment by rodica-andronache** [comment]
@Soare-Robert-Daniel thanks! those issues are fixed.
I've also tested the oldest versions of PHP and WP supported, from https://github.com/Codeinwp/otter-blocks/blob/master/readme.txt and there is an error when creating a new post.

So, with PHP 5.6 and WP 5.9 when adding a new post this appears https://vertis.d.pr/i/9gZ4Bi
This is the error:

`TypeError: Cannot destructure property 'isOnboardingVisible' of '(0 , n.useSelect)(...)' as it is undefined.
    at render (https://py-sardine-tite.vertisite.cloud/wp-content/plugins/otter-blocks/build/blocks/blocks.js?ver=b71b47424bc244aa0011:16:583543)
    at Le (https://py-sardine-tite.vertisite.cloud/wp-includes/js/dist/vendor/react-dom.min.js?ver=17.0.1:100:3)
    at Pj (https://py-sardine-tite.vertisite.cloud/wp-includes/js/dist/vendor/react-dom.min.js?ver=17.0.1:231:183)
    at di (https://py-sardine-tite.vertisite.cloud/wp-includes/js/dist/vendor/react-dom.min.js?ver=17.0.1:168:305)
    at Nj (https://py-sardine-tite.vertisite.cloud/wp-includes/js/dist/vendor/react-dom.min.js?ver=17.0.1:168:236)
    at sc (https://py-sardine-tite.vertisite.cloud/wp-includes/js/dist/vendor/react-dom.min.js?ver=17.0.1:168:96)
    at gf (https://py-sardine-tite.vertisite.cloud/wp-includes/js/dist/vendor/react-dom.min.js?ver=17.0.1:162:109)
    at https://py-sardine-tite.vertisite.cloud/wp-includes/js/dist/vendor/react-dom.min.js?ver=17.0.1:73:230
    at unstable_runWithPriority (https://py-sardine-tite.vertisite.cloud/wp-includes/js/dist/vendor/react.min.js?ver=17.0.1:24:26)
    at Za (https://py-sardine-tite.vertisite.cloud/wp-includes/js/dist/vendor/react-dom.min.js?ver=17.0.1:73:8)`

I've checked, and this is happening just for this PR, everything's ok with the current version

**Comment by HardeepAsrani** [comment]
@mghenciu Yes, that's right, you will be back to the default behavior.

**Comment by HardeepAsrani** [comment]
@rodica-andronache Robert has fixed that, let us know if it works and if we're good to go. 😄

**Comment by Soare-Robert-Daniel** [comment]
@rodica-andronache, the issue is fixed 🔧 

@HardeepAsrani, the `core/preference` is available from 6.0. In 5.9 the button will show but it will not be functional.

**Comment by HardeepAsrani** [comment]
> @HardeepAsrani, the core/preference is available from 6.0. In 5.9 the button will show but it will not be functional.

It's fine for now, I think Core Preferences was available before that too, if I'm not wrong, but maybe under a different store name.

**Comment by rodica-andronache** [comment]
@HardeepAsrani all good now, thank you for your patience 🚀

**Comment by HardeepAsrani** [comment]
Awesome @rodica-andronache, thanks for the QA. Will start the release process then. 😄

**Pull request merged**
