### PR TITLE
Add PR checklist workflow

### LINKED ISSUE #1666: Add Neve-like checklist to Otter
### What problem does this address?

As discussed during the meeting, we can integrate the same workflow as we have in Neve: https://github.com/Codeinwp/neve/blob/master/.github/workflows/pr-checklist.yml

### What is your proposed solution?

_No response_

### PR DESCRIPTION
**Pull request by arinaturcu**
Closes #1666.

### Summary

- Adds the PR checklist workflow from Neve.
- All checks from the PR description body should be checked for the workflow to show as passed.
- It can be skipped  with the `pr-checklist-skip`.

### Test instructions

---- 

### Checklist before the final review

- [x] Visual elements are not affected by independent changes.
- [x] It is at least compatible with the [minimum WordPress version](https://wordpress.org/plugins/otter-blocks/).
- [x] It loads additional script in frontend only if it is required.
- [x] Does not impact the [Core Web Vitals](https://web.dev/vitals/).
- [x] In case of deprecation, old blocks are safely migrated.
- [x] It is usable in Widgets and FSE.
- [x] Copy/Paste is working if the attributes are modified.

### CODE REVIEW

**Review by preda-bogdan — APPROVED** [review]
The changes look good! Good Job! 🚀 
A small NIT (not blocking) I have is that a new checklist item can be added that refers to adding tests, this way the labels added can be used to measure how many tests are being added, and encourage writing more tests.

**Comment by arinaturcu** [comment]
Thanks! Would something like this sound good?
> - [ ] Include E2E or unit tests for the changes in this PR.

**Comment by HardeepAsrani** [comment]
@arinaturcu Yes, that will be great. Thank you for taking care of this. 🚀

**Comment by arinaturcu** [comment]
Ok, I added it now. Thank you for the feedback! 🚀

**Review by HardeepAsrani — APPROVED** [review]

**Pull request merged**
