### PR TITLE
Copy&Paste Animation + Adaptors update

### LINKED ISSUE #1446: Copy Animations with Copy-Paste style
### Description:

As mentioned [here](https://github.com/Codeinwp/otter-blocks/issues/1442) and as Discussed with Robert, **it would be helpful to have Animations included in the Copy Paste mechanism.**

**Use-case**: I have a page with 32 different Icons, and I want to add animations to all of them. I would be much easier to add on one Icon, and then Copy-Paste the style to others.

### PR DESCRIPTION
**Pull request by Soare-Robert-Daniel**
Closes #1446.

### Summary

- Update adaptors for the recent changes.
- Copy & Paste animations.

----

### Test instructions

Now the animation settings should also be copied.

ℹ️ As always, the copy-paste between different block types might not behave as expected.

---- 

### Checklist before the final review

- [ ] Visual elements are not affected by independent changes.
- [ ] It is at least compatible with the [minimum WordPress version](https://wordpress.org/plugins/otter-blocks/).
- [ ] It loads additional script in frontend only if it is required.
- [ ] Does not impact the [Core Web Vitals](https://web.dev/vitals/).
- [ ] In case of deprecation, old blocks are safely migrated.
- [ ] It is usable in Widgets and FSE.
- [ ] Copy/Paste is working if the attributes are modified.

### CODE REVIEW

**Comment by mghenciu** [comment]
Tested again Robert, and even if the issue I mentioned yesterday with the Copy-paste from an Image to a Column - is fixed, **I think the challenge with copying from different blocks, is still present.** 

Here's an example were I copied the Style from an Icon to a Core Heading (and it shouldn't be possible). Basically it adds the border radius of the Icon to the Core Heading - even if the core headings don't have border radius controls:
 

https://user-images.githubusercontent.com/52494172/213692435-84362226-1300-4a91-9a6b-799752df9466.mov




Maybe it would be better **to release the Copy Paste for Animations, and later look into this - if it's a more complex issue.**

**Comment by Soare-Robert-Daniel** [comment]
> Here's an example were I copied the Style from an Icon to a Core Heading (and it shouldn't be possible). Basically it adds the border radius of the Icon to the Core Heading - even if the core headings don't have border radius controls:

The great challenge is establishing more rules for the copy. It seams that Gutenberg add some hidden functionality that is not visible for the user but it awaken if some values are present. Normally, extra values should be ignored.

I think we can made some more explicit rules for hot blocks like heading and paragraph.

Another issue, if Gutenberg is adding his own copy style, how should we rename ours? With the past controls in toolbars we were kind of save since it was separated, but now we need to coexists.

**Comment by mghenciu** [comment]
I think at this stage, it's ok to leave it as it is, Robert.
**Assuming that users will use the Copy Paste only on the blocks of the same type.**

and **as Core already added/will add** [soon the Copy Paste feature](https://github.com/WordPress/gutenberg/issues/44418), we'll just need to wait a bit and see how we can integrate and adjust this - as having 2 copy/paste, won't make sense.

**Review by HardeepAsrani — APPROVED** [review]

**Comment by irinelenache** [comment]
@Soare-Robert-Daniel Found a single problem, i don't exactly know if this is the expected behaviour, let me know what you think:
- If i already have some blocks with animations and i want to copy and paste the style of a block with the animation deleted, i can't. Here is a video with the problem https://vertis.d.pr/v/Gq2zER

**Comment by Soare-Robert-Daniel** [comment]
As we discussed in the meeting, if we do not copy any animation from the block, we should not override the options of the block in which we paste. 

The current behavior will remain.

**Comment by irinelenache** [comment]
@Soare-Robert-Daniel Thanks for looking into this, i'll move this to **Ready to merge** then 👍

**Pull request merged**
