### PR TITLE
Development

### PR DESCRIPTION
**Pull request by HardeepAsrani**
- https://github.com/Codeinwp/otter-blocks/issues/998
- https://github.com/Codeinwp/otter-internals/issues/27
- https://github.com/Codeinwp/otter-blocks/issues/1152
- https://github.com/Codeinwp/otter-blocks/issues/818
- https://github.com/Codeinwp/otter-blocks/issues/1155
- https://github.com/Codeinwp/otter-blocks/issues/809
- https://github.com/Codeinwp/otter-blocks/issues/1121
- https://github.com/Codeinwp/otter-blocks/issues/1060
- https://github.com/Codeinwp/otter-blocks/issues/1153
- https://github.com/Codeinwp/otter-blocks/issues/1150
- https://github.com/Codeinwp/otter-blocks/issues/1174
- https://github.com/Codeinwp/otter-blocks/issues/1173
- https://github.com/Codeinwp/otter-blocks/issues/1074
- https://github.com/Codeinwp/otter-internals/issues/26
- https://github.com/Codeinwp/otter-blocks/issues/1179
- https://github.com/Codeinwp/otter-blocks/issues/1185
- https://github.com/Codeinwp/otter-blocks/issues/1139
- https://github.com/Codeinwp/otter-blocks/issues/1172
- Remove AggregateRating from Review Block Schema

---- 

### Checklist before the final review

- [ ] Visual elements are not affected by independent changes.
- [ ] It is at least compatible with the [minimum WordPress version](https://wordpress.org/plugins/otter-blocks/).
- [ ] It loads additional script in frontend only if it is required.
- [ ] Does not impact the [Core Web Vitals](https://web.dev/vitals/).
- [ ] In case of deprecation, old blocks are safely migrated.
- [ ] It is usable in Widgets and FSE.

### CODE REVIEW

**Comment by HardeepAsrani** [comment]
@irinelenache It's ready for the QA, hope we can filter out all the bugs!

**Comment by Soare-Robert-Daniel** [comment]
> * [ ]  When the **progress bar** has the percentage set as tooltip, some top margin will be added to the block https://vertis.d.pr/I7q4Nk

This is intended. We need some space to make sure that Tooltip does not collide with otter blocks.

**Comment by Soare-Robert-Daniel** [comment]
> * [ ]  When the button group has full width alignment, it looks different in [editor](https://vertis.d.pr/C8C4Hf) / [frontend](https://vertis.d.pr/tLefzb)

For this, WP has added some extra padding.

image

**Comment by Soare-Robert-Daniel** [comment]
> * [ ]  The **Open in new tab** toggle from the **Button group** gets deactivated when i'm editing the link https://vertis.d.pr/6oP8Ks

This is the default behaviour for that component. You can see it the core block: Buttons.

**Comment by Soare-Robert-Daniel** [comment]
@irinelenache You can re-test the Group Buttons block.

**Comment by irinelenache** [comment]
@Soare-Robert-Daniel @HardeepAsrani 

- [ ] If the buttons contain any icon, the button text will be left aligned in editor
editor: https://vertis.d.pr/soFaAO
frontend: https://vertis.d.pr/voIIPM

- [ ] If i add a product review in a section, it will still not be visible for the Review comparison block

Issues can be checked here:
```
 Admin area URL: https://release-otter.s2-tastewp.com/wp-admin 
 Username: irinel 
 Password: fam0axJd0Ps 
```

**Comment by HardeepAsrani** [comment]
>  If i add a product review in a section, it will still not be visible for the Review comparison block

That fix was merged just 10-15 mins back, so you probably didn't have that in the instance where you were testing. If you just update the plugin with the latest build, you should see it working.

I'll take a look at the first issue.

**Pull request merged**
