### PR TITLE
Welcome Modal

### PR DESCRIPTION
**Pull request by HardeepAsrani**
Closes https://github.com/Codeinwp/otter-internals/issues/27.

### Screenshots 

----

### Test instructions

---- 

### Checklist before the final review

- [ ] Visual elements are not affected by independent changes.
- [x] It is at least compatible with the [minimum WordPress version](https://wordpress.org/plugins/otter-blocks/).
- [x] It loads additional script in frontend only if it is required.
- [x] Does not impact the [Core Web Vitals](https://web.dev/vitals/).
- [x] In case of deprecation, old blocks are safely migrated.
- [x] It is usable in Widgets and FSE.

### CODE REVIEW

**Comment by HardeepAsrani** [comment]
@mghenciu Feel free to test it.

**Comment by mghenciu** [comment]
- [ ] Is it possible to extend the width of the Container to 340px? 
Ideally we are aiming to have **max 2 lines** of text for the Headings & **3 lines** for the body text.
With the current width, on this panel the text goes on 3 lines: 
Screenshot 2022-08-26 at 10 36 16

___

- [ ] when switching between panels, the Close Dialog is in focus each time. Is it possible to have this only for the first slide?  

https://user-images.githubusercontent.com/52494172/186851148-bef6b57b-1a5a-4c41-8c71-e275be91c927.mov


___

- [ ] **Last Slide height & scroll**
As mentioned above, we are aiming for the same Height on all panels, 2 lines max for the Headings & 3 lines max for the body text. Therefore I think having the scroll and a bigger height on the last slide, it's not very consistent UI wise:


https://user-images.githubusercontent.com/52494172/186852148-42948f99-367d-46ef-8a58-3b45a57e454a.mov

___

- [ ] Maybe we can make the Retake onboarding a button instead of a Toggle, something like this:
image

___

- [ ] Onboarding in the Dashboard
At the moment, when installing Otter, we only redirect the users to the Otter Dashboard.
Wouldn't it make sense to have a hint or something in the Dashboard about the Onboarding, something like this?
image

___
How do you feel about Showing the Modals, in the Editor,  one after another @HardeepAsrani?
Maybe we can use this idea with a small notification, and when users click on it they can see the Start Onboarding button:
image

https://www.figma.com/file/LRrhO1ovZnXFibXVsezR8a/Otter?node-id=1164%3A17463

**Comment by HardeepAsrani** [comment]
>  Is it possible to extend the width of the Container to 340px?

I've made the change, thank you!

>  when switching between panels, the Close Dialog is in focus each time. Is it possible to have this only for the first slide?

No, that's not in our control but users don't usually use keyboard for such things so it should be fine.

>  As mentioned above, we are aiming for the same Height on all panels, 2 lines max for the Headings & 3 lines max for the body text. Therefore I think having the scroll and a bigger height on the last slide, it's not very consistent UI wise:

I had a talk with Marius about it, and we've reduced the amount of text so it's better now.

>  Wouldn't it make sense to have a hint or something in the Dashboard about the Onboarding, something like this?

We actually had it in the Dashboard earlier but removed it as it makes more sense to show them the features when they are in the editor. We shouldn't over-do these things as users dislike being nudged again and again.

> How do you feel about Showing the Modals, in the Editor, one after another @HardeepAsrani?
Maybe we can use this idea with a small notification, and when users click on it they can see the Start Onboarding button:

I don't understand what you mean here. Can you explain?

>  Maybe we can make the Retake onboarding a button instead of a Toggle, something like this:

I'll make the change.

**Comment by HardeepAsrani** [comment]
I've made the change with width, text in the last slide & the button.

Also, as discussed with Marius, if you come to Otter from our upsells, like WP Maintainance or such, we won't show you the modal immediately (as not to bother you) but 2 days later.

We can maybe turn on the Custom CSS modal for WP Maintainance Mode too @selul? That way we can still get more users who don't want to migrate to new versions while the new version users, who will install Otter anyway, won't see the promotions. What do you think?

**Comment by selul** [comment]
@HardeepAsrani sounds good.

**Comment by mghenciu** [comment]
> I don't understand what you mean here. Can you explain?

The question it's about the Order in which we show the Onboarding Modal.
Right now, I think there are 2 possible scenarios: 
- a user **opened the Editor** before installing/activating Otter, so there will be only one Modal (the one from Otter).
- the user **didn't opened** the Editor before, so there are 2 modals in the queue (Otter & Gutenberg).

how do we show them? in this queue
One potential way of doing this, that I was suggesting, was trough the Notification bell:
image

**Comment by HardeepAsrani** [comment]
@mghenciu Here, I'm not sure the dot will always convey the meaning that there's a remaining action, especially for the first-time user, who might think it's just how the icon looks, as there's no similar indicator anywhere else.

Right now, we show the editor after you dismiss the Welcome Editor.

**Comment by irinelenache** [comment]
@HardeepAsrani Tested and found only some small things: 

- [ ] If the user already has Otter pro installed & activated, the [Otter pro upsell](https://vertis.d.pr/Nwbekw) will still be present in the modal (i'm not sure it's expected or not) 
- [ ] For me, the scrollbar is still visible on the last slide (using 14inch Macbook and Chrome) https://vertis.d.pr/6Mb5WF

Besides these, everything seems to work fine 🚀

**Comment by HardeepAsrani** [comment]
@irinelenache That text is actually for Otter Pro users, I think can make it better like changing "you get" to "you have" and so on.

**Comment by HardeepAsrani** [comment]
I also found that it breaks in 5.8 due to an unexpected issue. I'll fix that.

**Pull request merged**
