### PR TITLE
Animation Optimization

### LINKED ISSUE #1033: Animation optimization
### Description:
Few suggestions made by our users on how we can optimize animations:

- We can remove (or give an option) the -webkit prefixes that show animations on old browsers which can reduce the blueprint of the file by around 2/3 and make it from 66kb to something like 20kb. However, I see some stats that even browsers from 2 years back use -webkit prefixes so maybe some compromise here on adding an option to load them or dropping support.

- Loading animations in the front based on the usage where we only load the CSS from the animations which are loaded in the front. It's a bit more complex and we will need some mechanism to detect and extract CSS based on this but it can reduce 60/70kbs of page size when user is using only few animations the page.

Any thoughts? @selul

### PR DESCRIPTION
**Pull request by HardeepAsrani**
Closes #1033.

### Summary

This adds a new option to Dashboard (enabled by default), which toggles how we load animations in the front-end. If it's enabled, we only load CSS for the animations which are loaded on the page, not the entire file.

### Screenshots 

----

### Test instructions

You can disable/enable the option and ensure the animations file is only loaded when the option is disabled, and the animations continue to work either way properly.

For testing, you will have to use the Regenerate Styles option after you toggle. In code, we will force that option during the update migration.

---- 

### Checklist before the final review

- [x] Visual elements are not affected by independent changes.
- [x] It is at least compatible with the [minimum WordPress version](https://wordpress.org/plugins/otter-blocks/).
- [x] It loads additional script in frontend only if it is required.
- [x] Does not impact the [Core Web Vitals](https://web.dev/vitals/).
- [x] In case of deprecation, old blocks are safely migrated.
- [x] It is usable in Widgets and FSE.

### CODE REVIEW

**Comment by irinelenache** [comment]
@HardeepAsrani Made some tests and the mechanism seems to work fine (i'll have to test more scenarios though). I tried to see how it behaves on GTmetrix and i noticed that there is a difference for TTFB on a post that has a few animations (loading, counting and typing)
- without this PR: TTFB: 439ms
- with this PR: TTFB: 752ms

Let me know if this is expected or it can be somehow fixed.

⚠️ The testing is not final, i'll come back with another comment after i check everything

**Comment by HardeepAsrani** [comment]
@irinelenache That's a nice observation and I can see where that is coming from, and I'll fix that part.

But for the scope of this PR, can you test with just Loading Animations and see the GTMetrix?

**Comment by HardeepAsrani** [comment]
I also did few more things and removed all the default Otter styles from loading on the website when Otter wasn't being used, so please make sure block styles work properly when Dynamic Blocks are used or when blocks are added some other way. @irinelenache

**Comment by irinelenache** [comment]
@HardeepAsrani Tested more scenarios and everything seems to work fine and the performance results are improved 🚀 Also, the Otter styles are loaded only when needed 👍

**Comment by rinart73** [comment]
Any way to make this option available for people that use a separate CSS animation plugin? I decided to disable Otter because I'm using low-end hosting and I'm trying to minimize the amount of resources used. I'm not really using blocks that Otter adds at the moment.
Maybe I could hook up to some filter to override the setting and enable it? Or did you code the new functionality into the main plugin only?

**Comment by HardeepAsrani** [comment]
Hey @rinart73, it's not possible to do that because that plugin is really simple and Otter is the plugin which has most of the things in place to really make use of this features, like separating the CSS files on save and loading them.

**Comment by HardeepAsrani** [comment]
Hey @rinart73,

We see you've some nice insights about our product. I was wondering if you'd like to sometime hop on a call to discuss things. I'm curious to know how you use our product and how we can use your experience to improve.

Let me know if you'll be interested in that.

**Comment by rinart73** [comment]
@HardeepAsrani I'm fine with discussing things with text, not call. Feel free to contact me in Telegram: https://t.me/Rinart73

**Pull request merged**
