### PR TITLE
fix: sharing icons link to wrong post when used in neve custom layouts

### LINKED ISSUE #1270: Social Share icons point to the Custom Layout instead of the actual post
When used in the context of a CL template, the social share icons will actually share the Custom Layout template, and not the actual post.

To replicate this, just [share this post](https://demosites.io/otter/2022/10/11/cl-post-preview/) from the social share icons at the bottom.

Screenshot 2022-10-17 at 19 42 40

this is from the twitter share popup:

Screenshot 2022-10-17 at 19 42 04

### PR DESCRIPTION
**Pull request by arinaturcu**
Closes #1270.

### Summary

Find the post that needs to be shared from the current URL, rather than relying on `get_the_permalink()` to ensure the custom layout is not shared instead of the actual post.

### Test instructions

- Place a Sharing Icons block inside a Neve custom layout
- Add the custom layout to a post or page
- The buttons should share the link to the actual post/page and not to the custom layout
- Make sure it works with all types of permalink structure

Besides the custom layout context, they should also be checked in home pages, archive pages, widget areas. 

---- 

### Checklist before the final review

- [x] Visual elements are not affected by independent changes.
- [x] It is at least compatible with the [minimum WordPress version](https://wordpress.org/plugins/otter-blocks/).
- [x] It loads additional script in frontend only if it is required.
- [x] Does not impact the [Core Web Vitals](https://web.dev/vitals/).
- [x] In case of deprecation, old blocks are safely migrated.
- [x] It is usable in Widgets and FSE.
- [x] Copy/Paste is working if the attributes are modified.

### CODE REVIEW

**Review by HardeepAsrani — APPROVED** [review]

**Comment by irinelenache** [comment]
@arinaturcu Tried to test but couldn't make it work, for me it will still share the custom layout link.

You can check on this instance:
```
 Admin area URL: https://otter-cl.s2-tastewp.com/wp-admin 
 Username: irinel 
 Password: 3L-t3ZqB7to 
```

**Comment by arinaturcu** [comment]
Thanks @irinelenache! Seem that it works only with plain permalinks. I'm working on it and will let you know.

**Comment by arinaturcu** [comment]
@irinelenache Thanks! It should work now 🙈

**Comment by irinelenache** [comment]
@arinaturcu Now it works fine, thank you 🚀

**Comment by HardeepAsrani** [comment]
@arinaturcu This won't work on archive pages, for example, if you add it to Header of a website using FSE or Custom Layouts, on the homepage the link will be of the first post of the page rather than the homepage itself.

**Comment by arinaturcu** [comment]
@HardeepAsrani The tricky part is to get the name of the current post because the correct URL can be easly obtained.

I tried to get the post ID from the URL with `url_to_postid()`, but this works only for plain permalinks. And `get_queried_object_id()` will work in most cases, but will have the issues you mentioned (on archive pages and FSE). I didn't find anything else that could help.

What about removing the `&title=` part from the sharing URL?

**Comment by HardeepAsrani** [comment]
Still not right, I've this setup right now and I'm now getting same results in the Header as well as the Query Block.

Screenshot 2023-01-16 at 11 12 39 PM

**Comment by arinaturcu** [comment]
@HardeepAsrani I made some changes and used an attribute to check if the block is inside a query. Can you take another look and see if you find another situation when it won't work?

**Review by HardeepAsrani — APPROVED** [review]

**Comment by irinelenache** [comment]
@arinaturcu Tested more scenarios and everything seems to be fine on my end 🚀

**Pull request merged**
