### PR TITLE
Make Custom CSS work with FSE

### PR DESCRIPTION
**Pull request by HardeepAsrani**
### Summary

This fixes the issue with Custom CSS extension not working with FSE & Tablet/Mobile view in Post Editor.

----

### Test instructions

Make sure it works correctly both in back/front in both FSE/Post Editor. It won't work on Widgets/Customizer.

---- 

### Checklist before the final review

- [x] Visual elements are not affected by independent changes.
- [x] It is at least compatible with the [minimum WordPress version](https://wordpress.org/plugins/otter-blocks/).
- [x] It loads additional script in frontend only if it is required.
- [x] Does not impact the [Core Web Vitals](https://web.dev/vitals/).
- [x] In case of deprecation, old blocks are safely migrated.
- [ ] It is usable in Widgets and FSE.

### CODE REVIEW

**Comment by irinelenache** [comment]
@HardeepAsrani Tested and the issue is fixed for Mobile/Tablet view in single posts, but it still isn't working in the Site editor, both editor and frontend.

You can check on this instance:
```
 Admin area URL: https://neve-pods.s3-tastewp.com/wp-admin 
 Username: irinel 
 Password: nfydH_Jzjz4 
```

**Comment by HardeepAsrani** [comment]
I tried on your instance and it seems to work fine for me. Can you confirm?

Screenshot 2022-11-09 at 11 18 34 PM
Screenshot 2022-11-09 at 11 18 37 PM

**Comment by irinelenache** [comment]
@HardeepAsrani I checked again and i was trying to add custom css to blocks that were inside the **Post content** block, and nothing was applied https://vertis.d.pr/i/u9Z2aG. When i added the same blocks as top level blocks and added the CSS, they looked ok https://vertis.d.pr/i/bTKlxR. Let me know if this is the expected behaviour

Also, after i refresh the site editor, the CSS is not applied anymore, until i make a change to it. Here is a video to better outline the issue https://vertis.d.pr/v/wvJdKu

**Comment by HardeepAsrani** [comment]
@irinelenache

> I checked again and i was trying to add custom css to blocks that were inside the Post content block, and nothing was applied https://vertis.d.pr/i/u9Z2aG. When i added the same blocks as top level blocks and added the CSS, they looked ok https://vertis.d.pr/i/bTKlxR. Let me know if this is the expected behaviour

It's happening because some of those items require you to be more specific, like for Post Title, you need to target the link inside instead of just selector.

I'll fix the other one.

**Comment by irinelenache** [comment]
@HardeepAsrani Thanks for explaining, the second issue is fixed now so i'm moving this to **Ready to merge** 🚀

**Pull request merged**
