### PR TITLE
Revamped readme.txt

### PR DESCRIPTION
**Pull request by UVLabs**
- Renamed plugin Repo listing to include the keyword "page builder" as its a common trend amongst Gutenberg block plugins and I think we can benefit from this change

- Used some of the old text that was in the readme but basically rewrote the whole thing to add more details and include more Gutenberg block keywords.

Let me know if you have any questions or something more you'd like to include

Closes [#528](https://github.com/Codeinwp/otter-blocks/issues/528)

### CODE REVIEW

**Comment by HardeepAsrani** [comment]
@UVLabs Can you remove the part about Templates Library? We aren't pushing that much so better to not write about it much. Thanks!

**Comment by UVLabs** [comment]
@HardeepAsrani No problem

**Comment by UVLabs** [comment]
@HardeepAsrani I removed the dedicated pitch section for templates and added a section making mention of the global defaults, do you plan to add more otter blocks to the supported global defaults list? What about 3rd party and default wp blocks?

**Comment by HardeepAsrani** [comment]
@UVLabs We might add for more in Otter blocks. Seems good to me. Any feedback @mghenciu @Soare-Robert-Daniel @arinaturcu

**Review by HardeepAsrani — CHANGES_REQUESTED** [review]
The ones asked by Mihai.

**Comment by UVLabs** [comment]
@HardeepAsrani @mghenciu thank you, I've made the changes

**Comment by mghenciu** [comment]
Just to make sure, is the Flip Block mentioned/explained in the Readme?
I am reading a PDF of the previous version and can't find it in the **Blocks Available in Otter section**.

it's only mentioned in the Release Notes.

**Comment by UVLabs** [comment]
@mghenciu I have updated the readme and made mention of the flip block but I tried to not explain every single one because it gets repetitive

**Comment by mghenciu** [comment]
> @mghenciu I have updated the readme and made mention of the flip block but I tried to not explain every single one because it gets repetitive

Thanks for making the update, Uriahs. I agree with you, that we shouldn't repeat ourselves, and one example for this are the Pricing Table & Pricing Section, which go as one block in the Description.

Long term we should try to be as explanatory as possible, as we want our (new) customers to easily find and understand what Otter can do (and this goes for both Free & Pro features, blocks). + by having more keywords on the [Description page](https://wordpress.org/plugins/otter-blocks/), hopefully we'll have a SEO advantage.

**Comment by HardeepAsrani** [comment]
@UVLabs You've rebased the PR so we can't merge it directly as we want to merge it directly to master branch. I'll close this PR and copy/paste the file directly. :(

**Pull request closed without merging**
