### PR TITLE
Add Images to Icon List & SVG load

### PR DESCRIPTION
**Pull request by Soare-Robert-Daniel**
Close #675

### CODE REVIEW

**Comment by Soare-Robert-Daniel** [comment]
## Testing

This PR adds a new feature to Icon List Block: images as an alternative to icons.   
**We need to ensure that the block is not breaking when making the update. It is crucial that adding images has the same behavior as items and do not try to override each other.**

Main Steps:

1. Using the current Otter version, add an Icon List block.
2. Change to this PR, and check for breaking changes. There should be no error.
3. Select the Icon List, and activate the feature using the toggle [1] - This is also available for items.
4. Add an Image, create a new item to check.
5. After adding an item, try to change it from its inspector [2].

[1]
image

[2]
image

**Review by HardeepAsrani — CHANGES_REQUESTED** [review]
@Soare-Robert-Daniel It works fine for me, just a few things:

- Instead of a checkbox, the Icon Library should have a custom image checkbox.
- Icon color option shouldn't be visible if an image is selected.

Once that is done, you can ask Irinel to review.

**Comment by HardeepAsrani** [comment]
All yours @irinelenache to catch some bugs!

**Comment by irinelenache** [comment]
@Soare-Robert-Daniel @HardeepAsrani Tested this feature and found a few things:

- [ ] When i select the custom image option and no image is selected, the editor will look like this https://vertis.d.pr/PLKhjp

- [ ] The themeisle icons dropdown is broken https://vertis.d.pr/QjBHS0

- [ ] After selecting an image, the image picker doesn't disappear like for the other blocks https://vertis.d.pr/0VzpFo

- [ ] The Themeisle icons look small in editor/frontend, especially on mobile https://vertis.d.pr/qbNLzp

- [ ] A small edge case: when the icon dropdown is open, if i try to change the icon library to custom image, the icon search box will still be visible on screen https://vertis.d.pr/AiFxEh

**Comment by Soare-Robert-Daniel** [comment]
> * [ ]  After selecting an image, the image picker doesn't disappear like for the other blocks https://vertis.d.pr/0VzpFo

I think this is intentional. @HardeepAsrani did you planned another method for changing the image?

> * [ ]  The Themeisle icons look small in editor/frontend, especially on mobile https://vertis.d.pr/qbNLzp

I can not reproduce it. Is it a Mac problem?

**Comment by irinelenache** [comment]
@Soare-Robert-Daniel The marked issues are fixed, thank you 🚀 

> The Themeisle icons look small in editor/frontend, especially on mobile https://vertis.d.pr/qbNLzp
> I can not reproduce it. Is it a Mac problem?

^ About this issue, looked more into it and i saw it's happening on windows too. Based on how many lines the content has, the icon will be smaller. https://vertis.d.pr/1hcCDK -> Here are 4 icon list items that have the same icon

**Comment by Soare-Robert-Daniel** [comment]
> ^ About this issue, looked more into it and i saw it's happening on windows too. Based on how many lines the content has, the icon will be smaller. https://vertis.d.pr/1hcCDK -> Here are 4 icon list items that have the same icon

Can you give me a TesteWP instance with this?

**Comment by irinelenache** [comment]
@Soare-Robert-Daniel Sure:
```
 Admin area URL: https://costcord.tastewp.com/wp-admin 
 Username: irinel 
 Password: be7SF8oVEho 
```

**Comment by Soare-Robert-Daniel** [comment]
@irinelenache, the problem was not the number of the icons, but the length of the text. When the sentence overflow, the icon become smaller.

Thanks @irinelenache. A really interesting edge case.

**Comment by irinelenache** [comment]
@Soare-Robert-Daniel Tested again and now it works fine, thank you 👍

**Comment by HardeepAsrani** [comment]
> I think this is intentional. @HardeepAsrani did you planned another method for changing the image?

@Soare-Robert-Daniel Yea, I had to do it as the user couldn't ever replace the image if the parent element had already set one. It just always used the one from parent.

**Pull request merged**
