### PR TITLE
Fix: Google maps invalid key

### PR DESCRIPTION
**Pull request by arinaturcu**
When the saved API key is invalid, the placeholder should appear instead of the blank map.

If the user enters again an invalid key the issue is still there, but after a refresh, the placeholder should appear again.
So, the issue is partially solved.

### CODE REVIEW

**Comment by HardeepAsrani** [comment]
@arinaturcu It will be useful to add some help text on placeholder about the API key not being valid or not us not being able to validate it (in case the user has no internet).

**Comment by arinaturcu** [comment]
@HardeepAsrani I added the help text. Let me know if I should change something :robot:

**Comment by HardeepAsrani** [comment]
Seems good. Can you review @irinelenache?

When you have time, just remove the exclamation mark from the error notice. Seems like we're screaming. 😄

**Comment by irinelenache** [comment]
@arinaturcu Tested and the issue and behaviour is partially fixed, as mentioned in the first comment 👍

**Review by HardeepAsrani — DISMISSED** [review]
@arinaturcu It works fine the first time but once you change the value again on the same page, it comes back to the old behavior: https://www.loom.com/share/0431abe7fc694fc592be9726795129f1

Update: I realized right after writing it down that it was mentioned in the first comment so nevermind.

**Pull request merged**
