### PR TITLE
Add Actions when Countdown ends

### LINKED ISSUE #1138: Evergreen Countdown Feature
### Description:

A repeating countdown widget is a timer that displays the amount of time a particular user has to get the offer. The user can define how long the countdown will be there for after the user's first visit. This can be stored in local cache.

What I need more help is how we handle the end of the countdown for the evergreen countdown. Do we have a class to add to parent block that hides the entire section?

It will be a Pro feature.

@Codeinwp/design-team

### PR DESCRIPTION
**Pull request by Soare-Robert-Daniel**
Closes #1138.

### Summary

Actions
- Hide block
- Show block
- Disappear

### Screenshots 

----

### Test instructions

You need to test the two new mods (Evergreen and Interval) and the new triggers when Countdown ends.

Evergreen is a timer that starts the moment when you visit the page. Intervall will show the Countdown between the Start Date and End Data.

For easy testing of the triggers, you can set the time value to a past date or 0 (for Timer mode).

#### Query
```javascript
new QueryQA().select('blocks').where({ has: { blocks: ['countdown'] }}).run()
```

---- 

### Checklist before the final review

- [ ] Visual elements are not affected by independent changes.
- [ ] It is at least compatible with the [minimum WordPress version](https://wordpress.org/plugins/otter-blocks/).
- [ ] It loads additional script in frontend only if it is required.
- [ ] Does not impact the [Core Web Vitals](https://web.dev/vitals/).
- [ ] In case of deprecation, old blocks are safely migrated.
- [ ] It is usable in Widgets and FSE.

### CODE REVIEW

**Comment by Soare-Robert-Daniel** [comment]
@HardeepAsrani @Codeinwp/design-team, we have a few challenges with this:

- Hide/Show: at the moment, this act like a switch with the `visibility` property. I tried using `display: none`, but the layout shift was awful for the page.
- For redirect, this will happen after the js in loading and process. It is not a direct redirect (like when clicking on the page and redirecting without loading the page)
- For disappear: this is a bit tricky because the block should be hidden in case the time is already expired. If I set it to `display: none` and after checking, I make it visible, I will have a layout shift.

I am not sure if the layout shift is ok to happen. Did not encounter many websites with behavior.

**Comment by JohnPixle** [comment]
@Soare-Robert-Daniel thanks for sharing these insights. I am not quite sure what layout shift means in this case. Does it mean that when the page loads the countdown area will be blank for a while, and then the entire layout will "move" ? 

If possible do you think you could share a quick video of how the layout shift works in action? 

Thanks!

**Comment by Soare-Robert-Daniel** [comment]
> @Soare-Robert-Daniel thanks for sharing these insights. I am not quite sure what layout shift means in this case. Does it mean that when the page loads the countdown area will be blank for a while, and then the entire layout will "move" ?

Yes.

> If possible do you think you could share a quick video of how the layout shift works in action?

 I will post after I will finish the Timer mode. Show the time based on your first time on the site. **E.g.**:  If you enter for the first time, it will show X time from that our. Like the sites that show promotional offers for a limited time when you enter on their site.

**Comment by Soare-Robert-Daniel** [comment]
Now you set an interval for the countdown to decrease based on the user's first visit to the site.

The problem is that we need an expiration mechanism. Evergreen plugin uses cookies for storing the data; by default, they have an expiration date.

Should we also put an expiration date based on a formula or let the user set one?

https://user-images.githubusercontent.com/17597852/188868550-450b5559-0988-449b-a796-2836c93302e1.mp4

@JohnPixle, you can see at the end of the video the layout shift. The countdown occupied its space; after calculating the remaining time, which was 0, it disappeared, thus creating a shift in the layout.

**Comment by selul** [comment]
>  Evergreen plugin uses cookies
Why localStorage does not work here? 

> Should we also put an expiration date based on a formula or let the user set one?

The expiration date should be based on the user's first visit + countdown, no need to have another field for this.

**Comment by Soare-Robert-Daniel** [comment]
> The expiration date should be based on the user's first visit + countdown, no need to have another field for this.

By expiration, I mean how much time the countdown must stay hidden until it resets.

E.g.: A user enters for the first time and sees the countdown with 2 days promotion. After 2 days, the countdown will not longer appear. The dilemma, this should stay forever or after (let's say) a month, the user will again the countdown with the promotion.

**Comment by Soare-Robert-Daniel** [comment]
> Why localStorage does not work here?

It works, but the values do not expire automatically. Remains forever until it is deleted by the user via Clear Data. Cookies have an expiration mechanism built in.

**Comment by selul** [comment]
> It works, but the values do not expire automatically. Remains forever until it is deleted by the user via Clear Data. Cookies have an expiration mechanism built in.

But we don't need them to expire if we store the initial timestamp, which we can compare with the current date, and if expired we reset it. I think this answers the first question as well.

**Comment by selul** [comment]
@Soare-Robert-Daniel yes, I do, it can cause issues with caching, privacy, and many others.

**Comment by Soare-Robert-Daniel** [comment]
> @Soare-Robert-Daniel yes, I do, it can cause issues with caching, privacy, and many others.

Got it.

**Comment by Soare-Robert-Daniel** [comment]
@Codeinwp/design-team @HardeepAsrani, you can now test it out for feedback.

Please add a video or an instance for issues.

**Comment by mghenciu** [comment]
Nice work Robert, overall 🎸 💪 

I think this feature is quite complex, both from a UIX & Dev perspective. So maybe we can release it gradually, **by first adding the Countdown Time functionality, and what it happens when the countdown ends (Redirect, hide itself)**, and later build on those features with Hide other blocks, replace, etc.

___
Now related the the working prototype, here are a few ideas:

- maybe we can add some kind of basic CSS default transition, for when a Section appears/disappears. I know [this is a tricky one](https://stackoverflow.com/questions/3331353/transitions-on-the-css-display-property), but maybe we can look into it.
- from what I've tested, on expire and when choosing to hide/show a block, the timer will still be visible. Not sure if this makes total sense. I'll try to experiment with the options in Figma, and follow up.
- for the Timer, I think we can add a Toggle to Hide the Days & Hours, if those are equal to 0 (null). Meaning that if a user select only a few minutes and seconds -> the days could be hidden.
- I get the concern that Marius mentioned about cookies. However I would take into account also the case where a user opens the same page in Incognito, or on another Browser-same device. What would happen then?

**I'll share a Figma while in a while.**

**Comment by Soare-Robert-Daniel** [comment]
@mghenciu, made a new transition when an element appears. Is not perfect, the layout is still shiting abruptly, but the Lighthouse metrics are not affected.


https://user-images.githubusercontent.com/17597852/190113218-893f37b1-dfd8-4eb9-8f4a-8d999e8b203e.mp4

**Comment by mghenciu** [comment]
> @mghenciu, made a new transition when an element appears. Is not perfect, the layout is still shiting abruptly, but the Lighthouse metrics are not affected.

Looks like a progress Robert, but I would use a more minimal effect, no slide or stretch. Just a basic, subtle fade in or out.
We can leave this for later if it takes too much time.

___
I am back with the [Figma update](https://www.figma.com/file/LRrhO1ovZnXFibXVsezR8a/Otter?node-id=1716%3A24052). I tried to imagine how we want this features now, and how would the block look in future. This means that we can implement the features gradually, and later scale on that. Instead on spending too much time working on all at once.

For example for now we can go with **Static & Timer**, and for the Actions with Hide the Countdown, and Redirect - later add restart.
image

**Let me know your thoughts, and most importantly if the Logic behind the UI makes sense/it's intuitive.**
Some of those features may be available/enabled only when other are active, because those are dependent, for example the Restart will work only with the Timer Countdown Type.

**Hide the Countdown in Frontend** feature, will hide it in Frontend, but will allow to use the same Countdown logic on the page, so for example display a section after some time, the user opened the page.

cc @JohnPixle

**Comment by Soare-Robert-Daniel** [comment]
@mghenciu, a few questions:

- When adding the restart option, it wasn't supposed to have another field that specified a delay. Suppose we have a `Static`, should the countdown choose a random day? If it is a `Timer`, should restart right away or after a fixed time?
- `Hide the Countdown in Frontend` not sure about this. I think this is more suited for something like Visibility Conditions. Loading an entire block to the front just to be used like a trigger does not sound too appealing.


CC: @HardeepAsrani

**Comment by mghenciu** [comment]
- about the **Restart** @Soare-Robert-Daniel , that will be available **Only on the Timer Countdown**, for the Static & Interval it doesn't makes to have it, imo. Static will end when it reaches the end, and Interval will count only the time between that interval. Let me know if this makes sense.
And about what you proposed, with delay or setting a fixed time after it restarts, it can be also on page refresh - have you seen this patter somewhere else? or what would be the benefit of this

___

- the **Hide the Countdown in Frontend** should work, as you mentioned, as an invisible trigger. So let's say after a user enters a page, I want to show a **Promo section** with a Promo code, but only show this after 35 seconds from when the user opened the page. Would this be possible to do using the Visibility Conditions?

**Comment by Soare-Robert-Daniel** [comment]
>   And about what you proposed, with delay or setting a fixed time after it restarts, it can be also on page refresh - have you seen this patter somewhere else? or what would be the benefit of this

I don't see where this is used. Suppose, you are on the page, you see the countdown and how it ends, it shows a block. Then you refresh and the countdown restart, so you must wait again for it. Is this going to be used for showing things like subscribe messages than spam on pages like the ones from blog sites?

I will add the functionality for testing, so if it fits.

**Comment by JohnPixle** [comment]
@mghenciu The Figma UIs look good and we definitely need the descriptions behind the countdown type dropdown as you properly added. 

My only suggestion would be not to use the term `timer` though, and use `Evergreen` instead. It's a well-known term in the industry. `Timer` is a bit more generic and leaves room for mis-conceptions imo. 

> Looks like a progress Robert, but I would use a more minimal effect, no slide or stretch. Just a basic, subtle fade in or out.

Yes, absolutely. A simple fade in / out will work much better than any other fancy animation. We do not want to draw too much attention.

**Comment by Soare-Robert-Daniel** [comment]
@mghenciu, if all the display toggles are off, the block will be hidden in the front end. No need for an extra toggle.

A message will appear in the editor. It will let to visualize the date values, but it will not be displayed on the frontend.

image

**Comment by Soare-Robert-Daniel** [comment]
@mghenciu @JohnPixle 

You can test it here:

```
 Admin area URL: https://consisthat.s3-tastewp.com/wp-admin 
 Username: robertino 
 Password: MiJnTpmsirA 
```

**Comment by mghenciu** [comment]
Nice job, @Soare-Robert-Daniel 💪 

Some things I noticed while testing:

- [ ] I used an Evergreen that will disappear and Show a Section instead. **The challenge here is that the Invisible Section is still taking space in the DOM**. Not something groundbreaking, but still, I don't think this is expected:

https://user-images.githubusercontent.com/52494172/190640438-3a24979e-43c8-44d0-a39e-e1c6b999a8fc.mov

___

- [ ] **Duplicating a Countdown Block**
I discussed with @HardeepAsrani  a few days ago, that there is a know issue in the WP space, when duplicating a Block, it will somehow remain linked to the original one, and adjusting the Style settings will apply to the duplicate also. This happens all the time with the Countdown block. For example in this video, as seen, in Backend I have a countdown, I duplicate it, and when adjusting the bg-color on the Origin, it will apply it on both blocks:
  

https://user-images.githubusercontent.com/52494172/190643052-5d0eeeac-a363-4c23-adcf-3063990193b1.mov



___


- [ ] **Helper text saying something about the Restart**, even if the Selection action is **_No Action_**
Screenshot 2022-09-16 at 15 25 39

___



- [ ] Even in the current layout Robert, without the Sidebar restructuring, **I would move the End Action upper in the sidebar**. Somewhere  after the Time Settings panel or after the Display panel. This will help keep the same Information Architecture, meaning that we have Settings, and later Styles options.

**Comment by irinelenache** [comment]
@Soare-Robert-Daniel Tested the feature and here are my findings:

- [ ] If i use the evergreen feature, i can't make the countdown stop, because if i choose **No action** as [end action](https://vertis.d.pr/nRAAnL), the countdown will restart when it reaches 0. 
- [ ] If the countdown ended and the end behaviour should be to hide the countdown and show another block, everytime i refresh the page, the countdown will be visible for a second https://vertis.d.pr/rXtPSg
- [ ] I can't use both **show** and **hide** CSS classes. I think this is expected but maybe it can be a nice addition to be able to use both of them.

**Comment by Soare-Robert-Daniel** [comment]
> * [ ]  I can't use both **show** and **hide** CSS classes. I think this is expected but maybe it can be a nice addition to be able to use both of them.

I was thinking about this. It looks very practical. @HardeepAsrani @mghenciu @JohnPixle what do you think? Instead of showing that selector, we display both options.

**Comment by mghenciu** [comment]
> I was thinking about this. It looks very practical. @HardeepAsrani @mghenciu @JohnPixle what do you think? Instead of showing that selector, we display both options.


Thanks for the suggestion Irinel. As discussed on git, it could be something like this: 
image


I am a bit worried that this could trigger some edge cases, so please make sure to try to break this using some complex scenarios also, besides the straightforward ones :) 
to see if there are some flaws in the logic.

**Comment by Soare-Robert-Daniel** [comment]
> * [x]  If the countdown ended and the end behaviour should be to hide the countdown and show another block, everytime i refresh the page, the countdown will be visible for a second https://vertis.d.pr/rXtPSg

This is pretty tricky. For the moment, the countdown will be invisible but still occupy the space (to no cause a layout shift) until it will check if it has expired.

Small test.

```html
<!-- wp:cover {"minHeight":229,"minHeightUnit":"px","customGradient":"linear-gradient(135deg,rgb(6,147,227) 0%,rgb(175,40,40) 48%,rgb(155,81,224) 100%)","isDark":false,"className":"o-countdown-trigger-on-end-c02c556a o-cntdn-bhv-show"} -->
<div class="wp-block-cover is-light o-countdown-trigger-on-end-c02c556a o-cntdn-bhv-show" style="min-height:229px"><span aria-hidden="true" class="wp-block-cover__background has-background-dim-100 has-background-dim has-background-gradient" style="background:linear-gradient(135deg,rgb(6,147,227) 0%,rgb(175,40,40) 48%,rgb(155,81,224) 100%)"></span><div class="wp-block-cover__inner-container"><!-- wp:paragraph {"align":"center","placeholder":"Write title…","style":{"typography":{"fontSize":"4em"}},"textColor":"background"} -->
<p class="has-text-align-center has-background-color has-text-color" style="font-size:4em">Countdown Test</p>
<!-- /wp:paragraph --></div></div>
<!-- /wp:cover -->

<!-- wp:themeisle-blocks/countdown {"id":"wp-block-themeisle-blocks-countdown-c02c556a","behaviour":"restart","triggers":"showBlock","mode":"timer","timer":{"seconds":"10"}} -->
<div id="wp-block-themeisle-blocks-countdown-c02c556a" data-bhv="restart" data-mode="timer" data-timer="10000" data-trigger="showBlock" class="wp-block-themeisle-blocks-countdown"><div class="otter-countdown__container"><div class="otter-countdown__display"><div name="day" class="otter-countdown__display-area is-main-component"><div class="otter-countdown__value">0</div><div class="otter-countdown__label">Day</div></div><div name="hour" class="otter-countdown__display-area is-main-component"><div class="otter-countdown__value">0</div><div class="otter-countdown__label">Hour</div></div><div name="minute" class="otter-countdown__display-area is-main-component"><div class="otter-countdown__value">0</div><div class="otter-countdown__label">Minute</div></div><div name="second" class="otter-countdown__display-area is-main-component"><div class="otter-countdown__value">0</div><div class="otter-countdown__label">Second</div></div></div></div></div>
<!-- /wp:themeisle-blocks/countdown -->

<!-- wp:paragraph {"backgroundColor":"tertiary","className":"o-countdown-trigger-on-end-c02c556a o-cntdn-bhv-hide"} -->
<p class="o-countdown-trigger-on-end-c02c556a o-cntdn-bhv-hide has-tertiary-background-color has-background">Grab the promotion! 30%. You have only 30s to choose.</p>
<!-- /wp:paragraph -->

<!-- wp:paragraph {"backgroundColor":"vivid-red","className":"o-countdown-trigger-on-end-c02c556a o-cntdn-bhv-show"} -->
<p class="o-countdown-trigger-on-end-c02c556a o-cntdn-bhv-show has-vivid-red-background-color has-background">No more promotions for you.</p>
<!-- /wp:paragraph -->
```

**Comment by irinelenache** [comment]
@Soare-Robert-Daniel The mentioned issues are fixed, thank you 🚀 

- [ ] Using the **evergreen** type and **no action** as end action, the countdown will disappear if it reached 0 and i'm refreshing the page https://vertis.d.pr/SiWpdM

Besides this, everything seems to work fine for me

**Pull request merged**
