### PR TITLE
Development

### PR DESCRIPTION
**Pull request by HardeepAsrani**
- https://github.com/Codeinwp/otter-blocks/issues/1623
- https://github.com/Codeinwp/otter-blocks/issues/1290
- https://github.com/Codeinwp/otter-blocks/issues/1490
- https://github.com/Codeinwp/otter-blocks/issues/1931
- https://github.com/Codeinwp/otter-blocks/issues/1800
- https://github.com/Codeinwp/otter-blocks/issues/1930
- https://github.com/Codeinwp/otter-blocks/issues/1955
- https://github.com/Codeinwp/otter-blocks/issues/1933
- https://github.com/Codeinwp/otter-blocks/issues/1548
- https://github.com/Codeinwp/otter-blocks/issues/1046
- https://github.com/Codeinwp/otter-blocks/issues/1671
- https://github.com/Codeinwp/otter-internals/issues/99
- https://github.com/Codeinwp/otter-blocks/issues/1908
- https://github.com/Codeinwp/otter-internals/issues/90
- https://github.com/Codeinwp/otter-internals/issues/106
- https://github.com/Codeinwp/otter-blocks/issues/1884
- https://github.com/Codeinwp/otter-blocks/issues/1960

### CODE REVIEW

**Comment by irinelenache** [comment]
@HardeepAsrani Tested the release builds and here is what i found:

- [ ] For the Advanced heading, the top/bottom margin is not applied in the editor. [editor](https://vertis.d.pr/i/xKfp78) vs [frontend](https://vertis.d.pr/i/cdflAt)
- [ ] The custom speed and delay time for animations is not available for me https://vertis.d.pr/v/w4LxOB
- [ ] There is no way to add a bottom margin for the posts block pagination https://vertis.d.pr/i/yWpuKv , so this is how it will look in frontend https://vertis.d.pr/i/l2bdqP
- [ ] This is how the AI generated patterns look using 2024 theme (before inserting) https://vertis.d.pr/i/LIuz3I
- [ ] I got these warnings after installing Neve pro https://vertis.d.pr/i/JV7kKB

**Comment by HardeepAsrani** [comment]
Thank you @irinelenache, I've fixed the first three. The last one is bit tricky so we can leave it for now. For the 4th one, I'm not able to reproduce it so would it be possible for you to give step by step instructions on how we can reproduce it?

**Comment by irinelenache** [comment]
@HardeepAsrani The marked issues are fixed now, thank you 🚀 

>  This is how the AI generated patterns look using 2024 theme (before inserting) https://vertis.d.pr/i/LIuz3I

^ The issue happens because the container width in the editor is smaller using Twenty Twenty-Four, and some generated patterns with 4 columns look bad https://vertis.d.pr/i/FPtCbO https://vertis.d.pr/i/WJnLQQ (I'm using 14 inch macbook pro and Chrome)

**Comment by HardeepAsrani** [comment]
@irinelenache My bad. I meant the 4th one we can let go for now. I'm not able to reproduce the 5th one. How do I do that?

**Pull request merged**
