### PR TITLE
Review Block Enhancements

### LINKED ISSUE #816: Product Review - enhancements
This one will need to go through a slight redesign, there are several things that need to be adjusted for this block in order to be more friendly. I will redesign/simplify it soon along with other blocks, but the changes will be simple.

Additionally, some things that would be nice to have would be:
- The ability to choose a rating scale. For example, 5 stars or 10 stars. 10 stars appear very long in the variant with the column.

If not possible, we'll find another way to visually hack it. 
Screenshot 2022-03-18 at 10 39 53

Other issues spotted:
- Need to add wide width and full width options in the block toolbar.
- Need to add color controls so user can choose color of several elements (star ratings, etc)
- Need to fine-tune the vertical spacing of the bullets on the Pros and Cons

Screenshot 2022-03-18 at 10 53 53

### LINKED ISSUE #1074: Closing Otter upsell shouldn't redirect users to another page
### Description:

[As discussed on Slack.](https://vertistudio.slack.com/archives/C02JC68P404/p1658484220312939)

### How to reproduce:

1.
2.
3.

### Technical info
* WordPress version: 6.0.1
* Plugin version: 2.0.9

### PR DESCRIPTION
**Pull request by HardeepAsrani**
Closes #816.

### Summary

- Move structure setting from Style to Inspector
- Fix Features not appearing in two columns
- Fix Pros/Cons icon alignment
- Allow user to change rating scale from 1-10 to 1-5
- Add Alignment Option
- Add Image Width Control
- New Design & Structure
- Add Style Picker
- Add Padding Control
- Add Border & Box Shadow Controls

### Screenshots 

----

### Test instructions

---- 

### Checklist before the final review

- [ ] Visual elements are not affected by independent changes.
- [ ] It is at least compatible with the [minimum WordPress version](https://wordpress.org/plugins/otter-blocks/).
- [ ] It loads additional script in frontend only if it is required.
- [ ] Does not impact the [Core Web Vitals](https://web.dev/vitals/).
- [ ] In case of deprecation, old blocks are safely migrated.
- [ ] It is usable in Widgets and FSE.

### CODE REVIEW

**Comment by HardeepAsrani** [comment]
@Codeinwp/design-team This is ready. Let me know if your feedback.

**Comment by JohnPixle** [comment]
@HardeepAsrani Looking good, I am testing it and will get you my detailed feedback over the next hours! Thanks for the update!

**Comment by JohnPixle** [comment]
Hey @HardeepAsrani and team, here is [a loom video](https://www.loom.com/share/6105676333b74d05820b9cd84d6b71af) with my feedback on the product review block. Great work, if I were a user I would definitely be happy to see this level of flexibility. 🚀

I think it's worth fine-tuning this since it is the first block with the updated sidebar structure, and the first one to implement the default / boxed UI.  The Sidebar layouts looks very good btw.

### Feedback points as mentioned in the video

- [ ] Need a color control for Borders
- [ ] It would be great if users can customise the  `Pros`, `Cons` and `Buy Product` text?
- [ ] In the 2-column layout, there is an issue with double border 
- [ ] Product Price should be aligned with the rating
- [ ] Discounted price should be `body text color` with opacity instead of a fixed hex value of #a2a2a2
- [ ] The `xx out of xx` text parts should inherit the body text size instead of a fixed size of 13px
- [ ] Stars color do not respond to color control. Empty stars can be the `star color` with 50% opacity
- [ ] Pros and Cons label colors do not update based on the Text color control
- [ ] The border radius should apply on the entire box, not only the border.
- [ ] Shadow is displaying only at the frontend
- [ ] We need to address the gap between the image and the product description. Currently there is a fixed gap of 50px
- [ ] When users switch between the default / boxed styles, the Review box should adapt
- [ ] Need a way for the users to be able to reset all the customisations made on the block. I think the above might solve that (switching to default would apply the default appearance) 
- [ ] The reset icon of the shadow properties is not consistent with the other reset buttons. Needs further discussions.

@mghenciu Please feel free to take a look as well and share your thoughts and suggestions.

https://www.loom.com/share/6105676333b74d05820b9cd84d6b71af

[This is the tastewp page](https://superextra.s3-tastewp.com/6-2/) where I tested. 

```
 Admin area URL: https://superextra.s3-tastewp.com/wp-admin 
 Username: pixle 
 Password: J-4khQoWehs 
```

**Comment by irinelenache** [comment]
@HardeepAsrani https://github.com/Codeinwp/otter-blocks/issues/1187 is fixed, here are my findings regarding the enhancements: 

- [ ] The image width isn't changing in editor, in frontend it works fine https://vertis.d.pr/P0Pk3z
- [ ] If i change the rating scale to 1-5, the slider will still be 1-10, the rendered value in the block is correct but maybe we can change the slider range for a better UX https://vertis.d.pr/PIwy4t
- [ ] When i change the Style to boxed, the layout will automatically change from 1 column to 2 columns https://vertis.d.pr/ZX5vPs
- [ ] The stars color isn't working https://vertis.d.pr/WgoNKI
- [ ] The border radius is not correctly applied when the block has a background color https://vertis.d.pr/xVz8m1
- [ ] The box shadow isn't working in editor when i select palette colors https://vertis.d.pr/Fx3LSB

**Comment by JohnPixle** [comment]
@irinelenache thanks for the help here. 

Just to confirm that indeed the Shadow is problematic only when using a Palette color. Seems to be working with a custom color. The other issues are true, good catch 👍🏻 

However the image width appeared to be working fine on my end.

**Comment by mghenciu** [comment]
Nice job @HardeepAsrani , overall 🚀 

Super detailed review John, thanks a lot!
And Irinel, thank for the quick imput.

___
Few things I found:

- [ ] when using the H6 for the Main Heading, that will create **a lot of space between the headline and the Stars section**. I think it should remain consistent with how it looks on a H2 heading
Screenshot 2022-09-15 at 17 15 47
Screenshot 2022-09-15 at 17 16 00


____

- [ ] Same thing for the Pro/Cons headings, when adjusting those, with some there will be a bottom-margin, and for some there won't be any margin:

https://user-images.githubusercontent.com/52494172/190428613-87852db6-9694-4da5-8af1-97157a4b4b9c.mov

- [ ] What do you guys think if we add the **same functionally of ordering/moving the Product Features**, as we have for the Tabs block (attached)? 
image
Same thing for the **Pros & Cons**. In my opinion this should make reordering more easy.

So it should be consistent, either with a responsive bottom margin or no margin at all. 


___

For the **Border controls**, and in general for **Sliders**, can we move at this point from the slider with a null value which is in the middle by default, even if value is 0? Something [similar to this one](https://wordpress.github.io/gutenberg/?path=/story/components-experimental-bordercontrol--with-slider), which starts from 0.
Also I think the Control labels shouldn't be with Caps Lock if we want them Consistent, for example Padding is not with Uppercase:

Screenshot 2022-09-15 at 18 26 12

This one it's actually a bit confusing, as in Core Figma they use just capital letters and in the Components Library, they use Caps Lock.

___
About the **Responsive Controls** @HardeepAsrani , at this point something like this won't be possible? but also having a reset option, as discussed in the meeting 
image

___
About the **Reset feature**, could we add it in this Release @HardeepAsrani ? the one in the Toolbar, something like _Reset Block style to Global Defaults_

**Comment by HardeepAsrani** [comment]
> For the Border controls, and in general for Sliders, can we move at this point from the slider with a null value which is in the middle by default, even if value is 0? Something [similar to this one](https://wordpress.github.io/gutenberg/?path=/story/components-experimental-bordercontrol--with-slider), which starts from 0.

We can't move it it anywhere else we put a value, in which case Border style might not work properly.

> Also I think the Control labels shouldn't be with Caps Lock if we want them Consistent, for example Padding is not with Uppercase:

I'll check to make sure but it wasn't in ALL CAPS. I'm pretty sure about it. Might be something with some theme or plugin you're using, maybe?

>  when using the H6 for the Main Heading, that will create a lot of space between the headline and the Stars section. I think it should remain consistent with how it looks on a H2 heading

We can add a default margin/padding here but then it won't be inherting them from the theme which is what we wanted. Both have their own pros/cons, I'd personally prefer to limit the padding/margin from our side.

@mghenciu

**Comment by HardeepAsrani** [comment]
>  The reset icon of the shadow properties is not consistent with the other reset buttons. Needs further discussions.

Yes, it's not consistent so it takes less space and is an idea borrowed from Elementor. We can change that but those two might not look good together. 😄

**Comment by HardeepAsrani** [comment]
>  In the 2-column layout, there is an issue with double border

I tried to reproduce it but seems to be working fine on my end. Can you check again and let me know?

>  The xx out of xx text parts should inherit the body text size instead of a fixed size of 13px

That doesn't look good when I tried with default themes, that's an example:

Screenshot 2022-09-21 at 5 12 09 AM

>  Pros and Cons label colors do not update based on the Text color control

They seem to work fine for me. Can you check again and let me know?

>  Shadow is displaying only at the frontend

That's a known issue. We can skit it for this PR; it needs a more through solution throughout the plugin.

> When users switch between the default / boxed styles, the Review box should adapt

I tried to keep it consistent with how block styles in Core work. These are meant for the default styles of the block without any modification. It doesn't reset any set attributes, just applies CSS class.

>  Need a way for the users to be able to reset all the customisations made on the block. I think the above might solve that (switching to default would apply the default appearance)

It seems like a nice idea for a block extension that we can make that can just resort to default attributes and that was my first impression when I read that but such an extension will pose one issue and that is it can't see the difference between style from the content of the block. So it can't be made into an all-rounder extension but probably in future we can make this for our blocks at least.

**Comment by HardeepAsrani** [comment]
> The image width isn't changing in editor, in frontend it works fine https://vertis.d.pr/P0Pk3z

I can't reproduce it. Can you help me with that.

> If i change the rating scale to 1-5, the slider will still be 1-10, the rendered value in the block is correct but maybe we can change the slider range for a better UX https://vertis.d.pr/PIwy4t

It's just not possible.

> When i change the Style to boxed, the layout will automatically change from 1 column to 2 columns https://vertis.d.pr/ZX5vPs

I can't reproduce this. Can you help?

Can you QA it again? One major change here is that we have moved the rating scale option to Otter Dashboard and now it's site wide instead of being block-scoped. @irinelenache

**Comment by JohnPixle** [comment]
> The image width isn't changing in editor, in frontend it works fine https://vertis.d.pr/P0Pk3z

Just a note that I also could not replicate this at my end either. Image width seemed to be working fine.

**Comment by irinelenache** [comment]
@HardeepAsrani The marked issues are fixed now, thank you 🚀 

> The image width isn't changing in editor, in frontend it works fine https://vertis.d.pr/P0Pk3z

I checked again and i see it's happening with products from Craft Beer demosite. I tried with other png image and it's working fine, the problem is only at the images from the demo i think. You can check here:
```
https://review.s3-tastewp.com/2022/09/21/test-review-2/
Username: irinel  Password: JJCJUNuCc-4
```

Some other findings:

- [ ] The shadow is not correctly applied when the review has some border radius https://vertis.d.pr/5mIcCx
- [ ] When i have more reviews on the same post, the **Sync with Woocommerce** control gets multiplied https://vertis.d.pr/0OLsYw
- [ ] When i change the default value of the Border width, i think the style should change from Default to Boxed, because if you have some Border width set, the style control won't do anything https://vertis.d.pr/w4haxj

**Comment by HardeepAsrani** [comment]
> I checked again and i see it's happening with products from Craft Beer demosite. I tried with other png image and it's working fine, the problem is only at the images from the demo i think. You can check here:

Might be the issue with the image size.

>  When i change the default value of the Border width, i think the style should change from Default to Boxed, because if you have some Border width set, the style control won't do anything https://vertis.d.pr/w4haxj

That's how block styles work. They apply the default style and you can override them with your selected attributes.

**Pull request merged**
