### PR TITLE
Form UI Changes

### LINKED ISSUE #1330: Form block 2.0
### Description:

Re-iterate over the form block to make it more intuitive, potentially as a strong stand-alone solution, here are some comments : 

https://www.loom.com/share/3b41edc1204f47ebaad29f947e95aea7

@HardeepAsrani @JohnPixle @mghenciu

### PR DESCRIPTION
**Pull request by HardeepAsrani**
Closes #1330.

### Summary

As discussed in Otter meeting, this changes Form Block's UI to reduce the panels and use Tools component for Form Options panel.

### Screenshots 

Screenshot 2023-01-19 at 4 36 11 AM

----

### Test instructions

- Just make sure things work normally as before. Only UI changes, no functionality was touched.

---- 

### Checklist before the final review

- [ ] Visual elements are not affected by independent changes.
- [x] It is at least compatible with the [minimum WordPress version](https://wordpress.org/plugins/otter-blocks/).
- [x] It loads additional script in frontend only if it is required.
- [x] Does not impact the [Core Web Vitals](https://web.dev/vitals/).
- [x] In case of deprecation, old blocks are safely migrated.
- [x] It is usable in Widgets and FSE.
- [x] Copy/Paste is working if the attributes are modified.

### CODE REVIEW

**Comment by HardeepAsrani** [comment]
@JohnPixle @mghenciu Let me know what you both think!

**Comment by mghenciu** [comment]
**Is the spacing between Options, normal?**
Looks a bit too much compared to the default 13px bottom or 24px:
Screenshot 2023-01-20 at 15 57 37

___

We also can decrease a bit the size by shortening the Helper text:
_Send the form's data to another email. (Admin's email is default)._. -> **Enter the email address you'd like the email to be sent to.**

Also here, the placeholder should be: **_Default is site administrator_** 


_Customize the title of the email that you are gonna receive after a user submits the form._ -> **Enter the title of the email.** 



___

On another note, what do you think Hardeep if we use a Panel for the **Form Options**, as it was before, and inside have a panel with Enable advanced form options, like this: 
image


___
Also, **is it possible globally to add the 3 dots link on the entire element** (heading + dots), ar at least on the title also?
Since the new Global Defaults control was added, I tried to click on the title also, not just on the 3 dots :))

**Comment by HardeepAsrani** [comment]
@mghenciu I had few opinions about the Three Dotted Layout and its usage which I thought I can perhaps put out better in a video: https://www.loom.com/share/7c66cfc5d46e41b4affb29f831f582c3 - let me know what you think about these.

**Comment by mghenciu** [comment]
I like this idea, @HardeepAsrani , to have only one Form block in the Inserter:

_we can probably have more premade templates, like RSVP, Quote and such, so perhaps we should only show them when you add the block, and not outside else we will have a lot of variations appearing._

and the templates here: 
image


___


> 

> @mghenciu I had few opinions about the Three Dotted Layout and its usage which I thought I can perhaps put out better in a video: https://www.loom.com/share/7c66cfc5d46e41b4affb29f831f582c3 - let me know what you think about these.

Yeah, you are right - that it won't make sense to have an additional panel if it's empty by default.
In the suggestion I had, I was referring to the Form Options - where by default there will be at least 2 settings at any stage.

___
Another thing I noticed now, is that when all the Form Settings are enabled - a lot of things are in that panel, and it may be hard to have a visual separation between them. What do you think if we add a subtle bottom border between each setting added, something like [this](https://wordpress.github.io/gutenberg/?path=/story/components-experimental-divider--horizontal): 
Screenshot 2023-01-21 at 12 43 26

**Comment by irinelenache** [comment]
@HardeepAsrani Tested the UI changes and everything works fine for me 🚀

**Comment by AndreeaCristinaRadacina** [comment]
Hi there @HardeepAsrani 
Is there an issue with the Enable the reCaptcha option? I enabled it, but nothing appears:
image
image
Also, would that option refer to the hCaptcha too?

**Comment by HardeepAsrani** [comment]
@AndreeaCristinaRadacina If you have enabled and configured hCaptcha then you can just enable reCaptcha on form and in the front it should normally display the hCaptcha. Have you inserted hCaptcha keys in their dashboard?

**Comment by HardeepAsrani** [comment]
@AndreeaCristinaRadacina Yea we didn't want to add more stuff to Otter itself for hCaptcha, just allow an integration using their plugin instead.

**Pull request merged**
