### PR TITLE
Fix SVG crop in Neve

### LINKED ISSUE #1594: SVG logo cropping stopped working
This bug probably has come back. Cropping (or skip cropping) of SVG logo not possible with Neve 3.5.6 and WP 6.1.1.

_Originally posted by @lmisch in https://github.com/Codeinwp/neve/issues/3350#issuecomment-1482093975_
            

### Step-by-step reproduction instructions

- Install and activate the [SVG Support](https://wordpress.org/plugins/svg-support/) plugin.
- Try setting an SVG image as the logo.
- You'll see the missing skip cropping button and an error when trying to crop the image.

### Is the issue you are reporting a regression
Previously reported: https://github.com/Codeinwp/neve/issues/3350

### PR DESCRIPTION
**Pull request by Soare-Robert-Daniel**
Closes #1594 .

### Summary

Our filter will load the mime types & metadata only if no other filter adds them.

ℹ️ Tested with SVG Support, and we do not accidentally override the data generated 👍 

### Screenshots 

Before: Load SVG has no details about the size. When trying to edit, the window shows empty. When using in Customizer for Website Logo, the Skip crop button does not exist, and Select & Crop does not give any feedback.

https://user-images.githubusercontent.com/17597852/230579406-3eb65a07-e036-4a1b-81d0-baf3cc20d599.mp4

After: SVG has details about the size, the edit window is no longer empty, and you can see the dimensions in the right corner. On Customizer, all buttons are working. 

https://user-images.githubusercontent.com/17597852/230579658-4adfd890-d56a-4a07-b857-851113e5f7e9.mp4

----

### Test instructions

1. Load an SVG. You can get plenty from [here ](https://themeisle.com/illustrations/).
2. Check if it has details about the size when you select it in Media Libary (can be seen in the video)
3. When you use it in Customizer for Logo & Site Identity, the buttons are functional when you press them.

ℹ️ You can NOT crop SVG, so when you press the Select & Crop, it should give you an error (seen in the second video). 

---- 

### Checklist before the final review

- [x] Visual elements are not affected by independent changes.
- [x] It is at least compatible with the [minimum WordPress version](https://wordpress.org/plugins/otter-blocks/).
- [x] It loads additional script in frontend only if it is required.
- [x] Does not impact the [Core Web Vitals](https://web.dev/vitals/).
- [x] In case of deprecation, old blocks are safely migrated.
- [x] It is usable in Widgets and FSE.
- [x] Copy/Paste is working if the attributes are modified.

### CODE REVIEW

**Comment by Soare-Robert-Daniel** [comment]
After some investigation, the cause is this:

https://github.com/Codeinwp/neve/blob/d2ab7b9b90f0b90c9097e6dca2d3dc654f713cb2/assets/apps/components/src/Common/MediaLibrary.js#L87-L88

The variables are `undefined`, thus creating an error.

image

The SVG loaded is not a real/correct attachment. They exist in the media library but have no metadata attached. When you try to edit it, you get this:

image

What SVG Support has, and we don't, is the generation of attachment data. They have this file https://plugins.svn.wordpress.org/svg-support/trunk/functions/attachment.php where the magic is happening.

ℹ️ I think it will be a good idea to have the error handling in case of an attachment without metadata in Neve. It should display an error about the missing data and not freeze the modal.

CC @cristian-ungureanu, @HardeepAsrani

**Comment by HardeepAsrani** [comment]
@Soare-Robert-Daniel Good work investigating the issue. The thing here is that Otter might also be used with themes other than Neve, it might be good to add add some metadata to the image, as minimum as we can to get away with while also making sure if some SVG Support specific plugin is running, we bail out and let them do the work instead.

**Review by HardeepAsrani — APPROVED** [review]
Looks good to me.

**Comment by irinelenache** [comment]
@Soare-Robert-Daniel Great job, tested and the issue is fixed, didn't find any other problem 🚀

**Pull request merged**
