### PR TITLE
Add Default Value to Form Fields

### LINKED ISSUE #1908: Add option to add default values to form fields
### What problem does this address?

I started designing a form with a bunch of hidden fields only to realize that there is no option to set a default value for any of the form fields. 

I think this is a pretty basic feature that all form builders have, so we should consider adding it as well.

### What is your proposed solution?

Add a 'Default Value' input field to 'Field Settings' for some input fields (text, hidden, number ...).

### Will this feature require documentation? (Optional)

I dont know.

### PR DESCRIPTION
**Pull request by Soare-Robert-Daniel**
Closes #1908

### Summary

Add default value component to Form fields.

🔧 New UI for Radio, Select, Checkbox in the Options to support selecting the default option value.

### Screenshots 

https://github.com/Codeinwp/otter-blocks/assets/17597852/864b1620-7098-4402-985c-22627aae154d

----

### Test instructions

Check the default value for Text type input (email, text, number, etc.) and Choice type (Radio, Select, Checkbox).

---- 

### Checklist before the final review

- [x] Included E2E or unit tests for the changes in this PR.
- [x] Visual elements are not affected by independent changes.
- [x] It is at least compatible with the [minimum WordPress version](https://wordpress.org/plugins/otter-blocks/).
- [x] It loads additional script in frontend only if it is required.
- [x] Does not impact the [Core Web Vitals](https://web.dev/vitals/).
- [x] In case of deprecation, old blocks are safely migrated.
- [x] It is usable in Widgets and FSE.
- [x] Copy/Paste is working if the attributes are modified.
- [x] PR is following [the best practices]()

### CODE REVIEW

**Review by HardeepAsrani — CHANGES_REQUESTED** [review]
Code looks good but we should add some indicator in drag/drop to set the default, right now it says nothing and you just have to figure out, so a tooltip there or some sort of indicator to let the user know what those checkbox/radiobox do.

**Comment by Soare-Robert-Daniel** [comment]
Here is the tooltip.

Screenshot 2023-10-27 at 15 59 45

**Review by HardeepAsrani — CHANGES_REQUESTED** [review]
Hey, thanks for the changes. I saw few issues which I still find to be important:

- Here the Untitled label stays when you click and try to make the change, not working as a placeholder.
- It took me a while to realize where I'm supposed to type/edit the value. Maybe it will be better to have autofocus when you click on Add New.
- We can also replace the Untitled Tab with "Click to Edit" placeholder maybe.

Screenshot 2023-10-31 at 11 37 40 AM

**Comment by Soare-Robert-Daniel** [comment]
The text is now a placeholder.

image

Focus when adding a new option.

https://github.com/Codeinwp/otter-blocks/assets/17597852/0d77f363-4c20-4ab9-a42d-6bf4f1c51e59

**Review by HardeepAsrani — APPROVED** [review]

**Comment by irinelenache** [comment]
@Soare-Robert-Daniel Tested and everything's fine on my end 🚀

**Pull request merged**
