### PR TITLE
Animation enhancements

### LINKED ISSUE #1548: Custom Delay/Speed, Animation Offset & Hover controls for Blocks Animation
### What problem does this address?

> With the introduction of the block editor and the lack of ability to assign metadata to your markup makes adding block animations fairly difficult.
> 
> This plugin comes very close to solving this problem but after testing is missing some key features.
> 
> Custom Inputs
> 
> You don’t have the ability to add custom values for delay/speed. This is critical to chaining animations especially when content is ordered into grids/columns. If I have 3 columns each containing an image and I wish to fade in the image one after the other this is not possible using this plugin.
> This renders the animation useless for a large number of content layouts.
> 
> Animation offset
> 
> I’m surprised this is missing from the plugin but you can’t assign an offset to run the animation. Currently, the animations trigger as soon as the content enters the viewport. Although you can add a pre-defined animation delay this is not the same.
> 
> If an element is only just within the view port the delay count down will run. If you want to ensure the full element is in view before running the animation you’d need to be able to assign an offset.
> 
> Hopefully this plugin continues to be developed to better support these 2 common animation features. 

### What is your proposed solution?

Feedback for the plugin posted on WordPress.org: https://wordpress.org/support/topic/so-close-to-being-perfect-3/ - I think it's some good feedback and we can see how we can implement these features, especially the second one that seems not out of box with the library we use.

Also, we can have Hover animations as many users have asked for that over the years.

### PR DESCRIPTION
**Pull request by Soare-Robert-Daniel**
Closes #1548

### Summary

🚀 Now, users can use custom values for Speed and Delay
🔍 Now, animations can trigger on mouse hover.
⛔ Offset for triggering the animation after passing a certain point.

### Screenshots 

image

image

----

### Test instructions

1. Make a block and add an Otter animation via the Block Tools tab on the Sidebar/Inspector
2. Check if the custom values, offset and hover are working.

⚠️ Hover is *not* enabled for the Editor to preview.

⚠️ The reference point for offset is considered the top limit of the element. If you use an image as a test, do think that the middle of the image is the reference point when you set the value of the offset. If you want to trigger the animation when the image is fully visible, use the image width as the offset.

Also, make sure that CSS class names for the block that you are testing look clean, like this:

```
<!-- wp:paragraph {"className":"animated pulse o-anim-custom-speed o-anim-value-speed-3s o-anim-hover "} -->
<p class="animated pulse o-anim-custom-speed o-anim-value-speed-3s o-anim-hover">asdfasdfasdf</p>
<!-- /wp:paragraph -->
```

Check if we have malformed data like `o-anim-value-speed-3s30s`. ℹ️ If you are sure if it is ok or not, you can post here for confirmation.

If the custom values are not working, go to Console and run this code: `document.querySelector('#o-anim-custom-values').innerHTML`. The result should be included in SS or posted video with the issue.

You can copy the problematic block and paste it here (like the example above) for faster cooperation. They are independent of any settings, so I do not need an instance.

---- 

### Checklist before the final review

- [ ] Included E2E or unit tests for the changes in this PR.
- [x] Visual elements are not affected by independent changes.
- [x] It is at least compatible with the [minimum WordPress version](https://wordpress.org/plugins/otter-blocks/).
- [x] It loads additional script in frontend only if it is required.
- [x] Does not impact the [Core Web Vitals](https://web.dev/vitals/).
- [x] In case of deprecation, old blocks are safely migrated.
- [x] It is usable in Widgets and FSE.
- [x] Copy/Paste is working if the attributes are modified.
- [x] PR is following [the best practices]()

### CODE REVIEW

**Review by HardeepAsrani — COMMENTED** [review]
It looks good, the delay, speed and offset worked nicely but I was testing the experience and hover doesn't seem to do anything on Firefox (atleast).

Also, we can add some tests here to as the module is getting more complex and avoid making any future changes that breaks the behavior.

Thank you!

**Review by HardeepAsrani — APPROVED** [review]

**Comment by irinelenache** [comment]
@Soare-Robert-Daniel Tested and here are some things that i found:

- [ ] Sometimes animations are visible at the top of the page and they are not triggered when they are in display https://vertis.d.pr/v/vPXxPW (I think it's related to the animation used - **Back in down**)
Block: https://pastebin.com/a3LxYGkx
- [ ] If i use the **Play on hover** feature, the block is already there before hovering, i don't exactly get how this can be properly used https://vertis.d.pr/v/xGQ6tn
- [ ] There is also a problem with the **Slide in down** animation. It's visible before being on display and blocks if i stop scrolling https://vertis.d.pr/v/yiKSts 
Block: https://pastebin.com/ESLEU8cF

**Comment by Soare-Robert-Daniel** [comment]
> * [x]  Sometimes animations are visible at the top of the page and they are not triggered when they are in display https://vertis.d.pr/v/vPXxPW (I think it's related to the animation used - **Back in down**)
>   Block: https://pastebin.com/a3LxYGkx

> * [x]  There is also a problem with the **Slide in down** animation. It's visible before being on display and blocks if i stop scrolling https://vertis.d.pr/v/yiKSts
>   Block: https://pastebin.com/ESLEU8cF

Now it should be 🔧 . It seems that one piece of CSS was no longer loading and caused some problems with the animation that was starting from the top. It seemed like a regression from WP.

> * [ ]  If i use the **Play on hover** feature, the block is already there before hovering, i don't exactly get how this can be properly used https://vertis.d.pr/v/xGQ6tn

Play on Hover is more for in-place animation, like the ones that add a jiggle or something similar. The usage will be decided by the user whether he likes it or not, or how creative he is.

**Comment by irinelenache** [comment]
@Soare-Robert-Daniel Thank you for the fixes 🚀 Here's another issue:

- [ ] There is still a problem when i'm adding an animation to an image, i don't exactly get why it happens https://vertis.d.pr/v/ifZhB4

You can check it here:
```
 Admin area URL: https://childlikeprocess.s1-tastewp.com/a02e5-the-law-firm/
 Username: irinel 
 Password: z-q95DWldNg 
```

**Comment by Soare-Robert-Daniel** [comment]
> * [ ]  There is still a problem when i'm adding an animation to an image, i don't exactly get why it happens https://vertis.d.pr/v/ifZhB4

It's a very weird issue. As an idea, we do only the triggering of the animation. The third-party lib does the running. In some cases, some animation might not work in all the cases as expected.

You can compare the current version with the one from this PR. If the issue is persistent in both versions, we will make another issue to not stall the features in this PR.

**Comment by irinelenache** [comment]
@Soare-Robert-Daniel I tested again and i see that the issue is not persistent, so i think it's safe to move this to **Ready to merge** and investigate it later if it occurs again 👍

**Pull request merged**
