### PR TITLE
Add AI Content

### PR DESCRIPTION
**Pull request by Soare-Robert-Daniel**
Closes #.

### Summary

Add content generation feature in AI Block.

Now Core Paragraph and Heading are enhanced using AI Toolbar, which provides useful premade prompts for text generation. This feature is also available when you multi-select multiple paragraphs and headings.

ℹ️ AI Block generates the content inside itself and provides features like history. AI Toolbar inserts the content **directly** into the page.

Additional:
- Added section to change the OpenAI Key in Dashboard > Integration
- Solved the pesky behavior of not getting the request when they are retrieved from an external server
- Now, the generation request goes through a proxy where we measure the usage. 

#### AI Block Generation

image
image

#### AI Toolbar

image

https://github.com/Codeinwp/otter-blocks/assets/17597852/0822fd07-54ad-4af5-900a-e2e5480b0973

----

### Test instructions

⚠️ You will need an Open AI API Key. 

- Test the new feature of the AI Block: Content generation. Make sure that From generation works the same.
- Test the AI Toolbar for Heading and Paragraph. Check for glitches.

---- 

### Checklist before the final review

- [ ] Included E2E or unit tests for the changes in this PR.
- [x] Visual elements are not affected by independent changes.
- [x] It is at least compatible with the [minimum WordPress version](https://wordpress.org/plugins/otter-blocks/).
- [x] It loads additional script in frontend only if it is required.
- [x] Does not impact the [Core Web Vitals](https://web.dev/vitals/).
- [x] In case of deprecation, old blocks are safely migrated.
- [x] It is usable in Widgets and FSE.
- [x] Copy/Paste is working if the attributes are modified.
- [x] PR is following [the best practices]()

### CODE REVIEW

**Review by HardeepAsrani — CHANGES_REQUESTED** [review]
Overall, it looks good. The only thing missing is about the workflow. When you click on something on the toolbar, like "Make it longer" it shouldn't just replace all your content instantly but popup the AI Block and show it inside there so the user can first see the response and then decide on the next action.

Also, we have an extra button for `Make it more descriptive/Make it longer`

**Review by HardeepAsrani — APPROVED** [review]
Things are working fine. There might be some changes to tracking but I need to confirm with the team but until that we can get this tested so we can move ahead.

**Comment by AndreeaCristinaRadacina** [comment]
Hi there,

Do we have any plans with the Settings accordion? Right now is clickable, but empty:
image

**Comment by AndreeaCristinaRadacina** [comment]
I tried using my API key, but I get this error, no matter if the account is new (no usage) or old.
image

Do you know why this might happen?

**Comment by irinelenache** [comment]
@Soare-Robert-Daniel Nice work 🚀 Tested and here are some issues that i found:

- [ ] After the text is generated, when i use the **Replace** button, the text is added after instead of replacing the initial text https://vertis.d.pr/v/zLULsY
- [ ] When i use the **Regenerate** feature on some AI generated text, i'm getting a very different response https://vertis.d.pr/v/j93nt0
- [ ] The AI block has a fixed height and a longer prompt doesn't fit inside it https://vertis.d.pr/v/jJU4YU

**Comment by irinelenache** [comment]
@Soare-Robert-Daniel The marked issues are fixed, thank you 👍 

Besides the issue that @AndreeaCristinaRadacina mentioned, everything's fine on my end.

Let me know if we will fix that also or i can move this to **Ready to merge** 👀

**Comment by HardeepAsrani** [comment]
@Soare-Robert-Daniel We can remove that Settings panel if that stays empty.

**Comment by Soare-Robert-Daniel** [comment]
The Settings have been removed—no need to test.

The endpoint for prompt fetch has been reverted to production one, which we need to update.

**Comment by HardeepAsrani** [comment]
@Soare-Robert-Daniel, Can you please fix the merge conflicts here? Thank you!

**Comment by AndreeaCristinaRadacina** [comment]
@HardeepAsrani hi there,

I have an issue that persists and I don't know the cause. I use the production builds for Otter and Otter Pro and generated a couple of API keys. Still, this is what happens when I enter a prompt:
image

Do you have any idea about this?

**Comment by Soare-Robert-Daniel** [comment]
@AndreeaCristinaRadacina @Codeinwp/qa-team, the new prompt is now available in the prod server; you can use the new Layout Generation.

**Comment by AndreeaCristinaRadacina** [comment]
I noticed that whenever I click on one of the options from the Toolbar, the prompt also appears. For example, if I click on "Make it shorter", it will generate a new block that also contains the prompt area. Is it intended?

**Comment by Soare-Robert-Daniel** [comment]
> I noticed that whenever I click on one of the options from the Toolbar, the prompt also appears. For example, if I click on "Make it shorter", it will generate a new block that also contains the prompt area. Is it intended?

Yes, for now.

**Comment by AndreeaCristinaRadacina** [comment]
One more thing:
When I selected a heading, the AI options inside the toolbar still contained the option "Generate heading", but when I clicked on it, it only changed the HTML tag without any rephrasing or something:
image

**Comment by Soare-Robert-Daniel** [comment]
> One more thing: When I selected a heading, the AI options inside the toolbar still contained the option "Generate heading", but when I clicked on it, it only changed the HTML tag without any rephrasing or something

No problem with this. Styling is not an issue. Regarding the result, there is no guarantee about it -- this is the AI Magic.

**Comment by mghenciu** [comment]
> No problem with this. Styling is not an issue. Regarding the result, there is no guarantee about it -- this is the AI Magic.

@Soare-Robert-Daniel , I think based on the Figma files - the suggested/generated content should be (in this case Headline), should be a bit smaller; even if it has a H1 tag: 
image

Also, I assume the AI Magic in this case - means that the AI didn't provided a variation since the text was too short, right?

**Pull request merged**
