### PR TITLE
Update animate.css to the latest version [#556]

### LINKED ISSUE #556: Update animate.css to latest version
We should update to the latest version of animate.css and use all the latest animations: https://animate.style/

### PR DESCRIPTION
**Pull request by arinaturcu**
Updates to the latest version of animate.css. 
`animate.min.css` is replaced with `animate.compact.css`.

Closes #556.

### CODE REVIEW

**Comment by HardeepAsrani** [comment]
@irinelenache Can you please test? Thank you!

**Comment by irinelenache** [comment]
@HardeepAsrani @arinaturcu Can i have a zip build for this PR?

**Comment by arinaturcu** [comment]
@irinelenache  Sure, [here](https://we.tl/t-xcSq5oJ4Fu) is the zip file :seal:

**Comment by irinelenache** [comment]
@arinaturcu Tested and the feature seems to work fine, found only one edge case

- [ ] When the page is scrolled from bottom to top, the blocks with **Back entrance** animations are not loaded anymore. I made a video to better outline the issue https://vertis.d.pr/tN9u5l

Can be checked here:
```
https://maddeningrail.tastewp.com/2022/02/15/test-animations-again/
Username: irinel  
Password: 27VTnOSH22o
```

**Review by HardeepAsrani — CHANGES_REQUESTED** [review]
Please fix the issues pointed out by Irinel's QA. Thanks!

**Comment by arinaturcu** [comment]
@irinelenache Thank you for the review! :rocket: 
The issue should be fixed now.

Here are the build files:

[blocks-animation.zip](https://github.com/Codeinwp/otter-blocks/files/8110045/blocks-animation.zip)
[blocks-css.zip](https://github.com/Codeinwp/otter-blocks/files/8110046/blocks-css.zip)
[blocks-export-import.zip](https://github.com/Codeinwp/otter-blocks/files/8110047/blocks-export-import.zip)
[otter-blocks.zip](https://github.com/Codeinwp/otter-blocks/files/8110048/otter-blocks.zip)

**Comment by irinelenache** [comment]
@arinaturcu Tested and the reported issue is fixed, thank you 🚀 

Found something else:

- [ ] With this PR, Otter settings in dashboard are not loaded anymore, and some errors are thrown in console https://vertis.d.pr/QEnAY2

**Comment by irinelenache** [comment]
@arinaturcu Checked with the last build and now it's working fine, thank you 👍

**Pull request merged**
