### PR TITLE
Allow saving in FSE for Form Options

### LINKED ISSUE #1802: Otter Contact Form not Saving Changes in Neve FSE Templates/Template Parts
### Description

When you edit any template of template part in Neve FSE by going to WP Dashboard > Appearance > Editor and place the Otter Form Block, select the Contact Form, make changes to the Save Location or Success or Error Message, save the changes, and refresh the page, the changes are not saved.

When we try to make the change again, it doesn't react and the save button is not allowed to be clicked assuming that no change happened.

### Step-by-step reproduction instructions

1. Install Neve FSE theme and Otter Blocks Plugin.
2. Go to WP Dashboard > Appearance > Editor > Template > Page > Edit the template.
3. Place Otter Form Block and select contact.
4. Make changes to the Save Location setting or Success/Error Message and hit Save.
5. Refresh the page and your save will vanish.
6. Try making changes again in Form Settings and try clicking the Save button and it will not get clicked.

### Screenshots, screen recording, code snippet or Help Scout ticket

Screen Recording: https://share.getcloudapp.com/nOuL48qm

Help Scout Ticket: https://secure.helpscout.net/conversation/2323424663/380740?folderId=212385

### Environment info

_No response_

### Is the issue you are reporting a regression

No

### PR DESCRIPTION
**Pull request by Soare-Robert-Daniel**
Closes #1802

#### [UPDATED]

A straightforward solution to this problem is to insert a dummy block and then delete it immediately. This will mark the block as dirty, thus enabling the Post/Page saving. The functionality is wrapped in a `debounce` function, which prevents multiple events from triggering simultaneously. 

ℹ️ This works reliably in Post/Pages/FSE/Widgets/Customizer 🔥 

#### [OLD SOLUTION]
Usually, the Save button is enabled when you make a change to the content of the post/page. The problem arises when some functionality is not tied to the content but is triggered by the `Save` button.

Form Options live in the WP Options. When a user changes something in the Form the Mail, the values must be saved in WP Options to take effect. They are not tied to the block attributes, thus making them invisible for the Editor to detect changes.

After some heavy investigation regarding the saving mechanism in the Gutenberg editor, a simple trick to enable the saving is to make a request using the function `dispatch( 'core' ).editEntityRecord`.

In this PR, we implement a function that makes this request by adding an unregistered meta value to the entity. Since it is unregistered, the value is not saved anymore, but making the request marks the post/page as `dirty`, thus enabling the `Save` button.

⚠️ This is not working with Widgets on the widget page.

### Screenshots 

https://github.com/Codeinwp/otter-blocks/assets/17597852/7d0bf192-3b90-4353-b646-37c307949560

----

### Test instructions

1. Use an FSE theme.
2. Add a form inside of the templates/pages.
3. Save the form as it is, then change some values in the Form Options.
4. `Save` button should be available.

⚠️ The `Save` will be available after 3 seconds without modification. As long as you type or change something in the Form options within 3 seconds, it will not trigger.

⚠️ You should notice `Form options have been saved`, which confirms the save request.

---- 

### Checklist before the final review

- [ ] Included E2E or unit tests for the changes in this PR.
- [x] Visual elements are not affected by independent changes.
- [x] It is at least compatible with the [minimum WordPress version](https://wordpress.org/plugins/otter-blocks/).
- [x] It loads additional script in frontend only if it is required.
- [x] Does not impact the [Core Web Vitals](https://web.dev/vitals/).
- [x] In case of deprecation, old blocks are safely migrated.
- [x] It is usable in Widgets and FSE.
- [x] Copy/Paste is working if the attributes are modified.
- [x] PR is following [the best practices]()

### CODE REVIEW

**Comment by HardeepAsrani** [comment]
All good here or any changes required @Soare-Robert-Daniel?

**Comment by Soare-Robert-Daniel** [comment]
@HardeepAsrani I am now investigating how to allow saving on the Widgets page.

**Review by HardeepAsrani — APPROVED** [review]
You can fix the merge conflicts and put it up for QA, thank you @Soare-Robert-Daniel

**Comment by rodica-andronache** [comment]
@Soare-Robert-Daniel I can't make it work, not sure if I'm missing anything. The values I save, disappear after a page refresh. https://vertis.d.pr/v/y6Bgy7

**Comment by Soare-Robert-Daniel** [comment]
@HardeepAsrani, the FSE saving is now given by `select( 'core/editor' )?.isSavingNonPostEntityChanges()`. We should also check the saving for Custom CSS since it uses the same mechanism as Form. We might have a regression.

**Comment by HardeepAsrani** [comment]
@Soare-Robert-Daniel Were you able to fix the issue Rodica has with this?

**Comment by Soare-Robert-Daniel** [comment]
> @Soare-Robert-Daniel Were you able to fix the issue Rodica has with this?

Yes.

**Comment by rodica-andronache** [comment]
@Soare-Robert-Daniel now everything's working well 👍

**Pull request merged**
