### PR TITLE
Development

### PR DESCRIPTION
**Pull request by HardeepAsrani**
- Increase Section's Max Width
- Fix vertical alignment not working in Section block
- Improve CSS Animation module
- Fix CSS Animation conflicting with third-party plugins
- Disable CSS Editor for Site Editor
- Fix errors occurring with WordPress 5.9
- Fix child tabs block not working properly

### CODE REVIEW

**Comment by HardeepAsrani** [comment]
@irinelenache Can you test this for last to make sure it works well with WordPress 5.9 so we can release?

**Comment by irinelenache** [comment]
@HardeepAsrani Tested and found a small problem only:

- [ ] Slider settings don't work in editor and i get some errors in console https://vertis.d.pr/lqLyjP (in frontend it seems to work fine)

**Comment by irinelenache** [comment]
@HardeepAsrani 
You can check it on this instance:
```
 Admin area URL: https://costcork.tastewp.com/wp-admin 
 Username: irinel 
 Password: or6AGaxYjXk 
```

Tested with 13 inch Macbook pro 2017, macOS Big Sur Version 11.5.2 and Google Chrome Version 96.0.4664.110 (Official Build)

**Comment by HardeepAsrani** [comment]
@irinelenache Thanks. Can you make sure the Slider works fire now?

**Comment by irinelenache** [comment]
@HardeepAsrani The Slider issue i mentioned is fixed now 👍 

Found something else, still related to the Slider. When i have one created with settings for **Slides per page, Gap, Peek and Height**, if i check the post in frontend and open the editor by clicking **Edit post**, an error occurs after trying to change some settings. I created a video for you to check the behaviour https://vertis.d.pr/iFJ5nV , also here is the testing instance:
```
 Admin area URL: https://meatychess.tastewp.com/wp-admin 
 Username: irinel 
 Password: iQMz705gfl4 
```

**Comment by HardeepAsrani** [comment]
@irinelenache That's not important, so will skip for now. Thanks!

**Pull request merged**
