### PR TITLE
Add box control for margin and padding on icon block

### LINKED ISSUE #1429: Add unlinked margin options for the Icon Block
### Description:

At this point for the Otter Icon block, the margins are linked - meaning that is one value for all sides.
This makes it hard to achieve a proper vertical spacing without using a spacer (see example below), because the margin on the left looks like a visual mistake:
Screenshot 2023-01-06 at 14 05 15
Screenshot 2023-01-06 at 14 13 46

**It would help to be able to modify them on each side, separately.**
### How to reproduce:

1. Add an Icon Block and text below
2. Align everything Left
3. Try to set the margin of the Icon to 16px

### Reference:

[icon-block.json.zip](https://github.com/Codeinwp/otter-blocks/files/10360066/icon-block.json.zip)

### Technical info
* WordPress version: x.x.x
* Plugin version: x.x.x

### PR DESCRIPTION
**Pull request by arinaturcu**
Closes #1429 .

### Summary

- Adds BoxControl for margin and padding in Icon Block.
- Changes the global defaults sync `SyncControlDropdown`.
- Updates the Icon size control from the Global Defaults to be the same as in the block inspector.

Screenshot 2023-02-05 at 22 41 35

### Test instructions

- It should be checked with existing/old blocks that have a `string` value for the padding and margin.
- All the other controls should work as before.

---- 

### Checklist before the final review

- [x] Visual elements are not affected by independent changes.
- [x] It is at least compatible with the [minimum WordPress version](https://wordpress.org/plugins/otter-blocks/).
- [x] It loads additional script in frontend only if it is required.
- [x] Does not impact the [Core Web Vitals](https://web.dev/vitals/).
- [x] In case of deprecation, old blocks are safely migrated.
- [x] It is usable in Widgets and FSE.
- [x] Copy/Paste is working if the attributes are modified.

### CODE REVIEW

**Review by HardeepAsrani — CHANGES_REQUESTED** [review]
I think the changes are good. Can you replace the individual Sync Controls in Dimensions and Colors and replace them to use `SyncControlDropdown` like rest of the blocks?

**Review by HardeepAsrani — APPROVED** [review]

**Comment by irinelenache** [comment]
@arinaturcu Tested and here is what i found:

- [ ] The existing icon blocks changed from [this](https://vertis.d.pr/i/F7Q46P) to [this](https://vertis.d.pr/i/XLjsDL)
- [ ] Adding icons next to each other with the same dimension settings will make them look different https://vertis.d.pr/i/kq2VcP I remember we had an issue regarding this but i cannot find it, maybe @mghenciu can share his input on this

**Comment by mghenciu** [comment]
> maybe @mghenciu can share his input on this

yeah, we had this challenge before. The outcome should be that if icons have the same size set -> the shape remains the same, no matter what Icon is used (either Font Awesome or Themeisle Icons). Maybe an idea is to have the Icon objects inside a wrapper that always has equal height and width. We use this principle in Figma, and this way each Icon has the same size, no matter the format.
 
[For example like in this case](https://demosites.io/web-agency-pro-gb/contact-us/), the shapes are circles and should remain perfect circles:
image

**Comment by arinaturcu** [comment]
@HardeepAsrani I made some changes to fix the issues Irinel found:
- Added a class to the blocks that use the new control for the padding to keep the old one's appearance unchanged.

> - [x] Adding icons next to each other with the same dimension settings will make them look different

- To fix this I used the font awesome class `fa-fw` and `aspect-ratio: 1` to make all icons have the same width and to keep the shape.

Let me know if these changes are ok.

**Review by HardeepAsrani — CHANGES_REQUESTED** [review]
With the dev branch, I just had a simple Icon without any settings and upon upgrading to this branch, it broke:

```
Content generated by `save` function:

<div id="wp-block-themeisle-blocks-font-awesome-icons-dfd9ac52" class="wp-block-themeisle-blocks-font-awesome-icons"><span class="wp-block-themeisle-blocks-font-awesome-icons-container nan-padding"><i class="fab fa-themeisle fa-fw"></i></span></div>

Content retrieved from post body:

<div id="wp-block-themeisle-blocks-font-awesome-icons-dfd9ac52" class="wp-block-themeisle-blocks-font-awesome-icons"><span class="wp-block-themeisle-blocks-font-awesome-icons-container"><i class="fab fa-themeisle"></i></span></div>
```

**Comment by arinaturcu** [comment]
Thanks @HardeepAsrani! It should be fixed now.

**Comment by irinelenache** [comment]
@arinaturcu Everything's fine for the old icons, but the new added icons don't look the same when i use the same dimensions settings and both icon types (font awesome and themeisle icons) https://vertis.d.pr/i/Fje4qI

You can check the issue here:
```
 Admin area URL: https://ottericons.s3-tastewp.com/2023/02/15/otter-icons/
 Username: irinel 
 Password: QernbICeMPk 
```

**Review by HardeepAsrani — APPROVED** [review]

**Pull request merged**
