### PR TITLE
Progress Bar enhancement

### LINKED ISSUE #818: Progress bar - enhancements
Some suggestions for the progress bar block

### 1. Add typographic size controls
Currently there is no way to customise the size of the fonts for title and percentage.
Screenshot 2022-02-18 at 18 07 53

### 2. Tooltip bg color
If “tooltip” mode is enabled, we need to provide bg color picker. OR by default it should inherit the progress color.
Screenshot 2022-02-18 at 18 09 27

### PR DESCRIPTION
**Pull request by Soare-Robert-Daniel**
Closes #818.

### Summary

- Add font-size for Title and Value on Outer style
- Tooltip will inherit the progress bar as the background color

### Screenshots 

----

### Test instructions

---- 

### Checklist before the final review

- [ ] Visual elements are not affected by independent changes.
- [ ] It is at least compatible with the [minimum WordPress version](https://wordpress.org/plugins/otter-blocks/).
- [ ] It loads additional script in frontend only if it is required.
- [ ] Does not impact the [Core Web Vitals](https://web.dev/vitals/).
- [ ] In case of deprecation, old blocks are safely migrated.
- [ ] It is usable in Widgets and FSE.

### CODE REVIEW

**Comment by Soare-Robert-Daniel** [comment]
@mghenciu can you check if the current changes fit your needs?

**Comment by JohnPixle** [comment]
@Soare-Robert-Daniel none of the [Production](https://verti-artifacts.s3.amazonaws.com/otter-blocks-feat-progress-enhancement-aba69289/otter-blocks.zip) ~ [Development](https://verti-artifacts.s3.amazonaws.com/otter-blocks-feat-progress-enhancement-aba69289/otter-blocks-dev.zip) links work for me :/ I dont see the new UI. Can you attach the zip?

**Comment by Soare-Robert-Daniel** [comment]
[otter-blocks-dev (36).zip](https://github.com/Codeinwp/otter-blocks/files/9415760/otter-blocks-dev.36.zip)

@JohnPixle what browser do you use?

**Comment by JohnPixle** [comment]
Using Chrome. But it worked with your file, thanks.

Both of these seem to work, nice work 👍🏻

**Comment by mghenciu** [comment]
@Soare-Robert-Daniel , one thing I noticed:

- [ ] in Backend, the margin from the Outer Label looks way bigger compared to what is in Front-end. Not a huge issue, but it's confusing ar first, as it's not what you see it what you get:

https://user-images.githubusercontent.com/52494172/186688721-9c107a8f-c163-4469-8ce0-39ddc447da56.mov

Other than that, the enhancements look be be added.

**Comment by irinelenache** [comment]
@Soare-Robert-Daniel Tested and here is what i found:

- [ ] Updating to this PR will make some existing progress bars change from [this](https://vertis.d.pr/f2S2Kb) to [this](https://vertis.d.pr/FiFRfO) 

Besides this, the new control works fine 👍

**Comment by irinelenache** [comment]
@Soare-Robert-Daniel Checked again and now everything is fine 🚀

**Comment by HardeepAsrani** [comment]
Before merging this, let me know if you all think anything else needs to be added for this block at this point in time? @mghenciu @JohnPixle

**Comment by mghenciu** [comment]
> Before merging this, let me know if you all think anything else needs to be added for this block at this point in time? @mghenciu @JohnPixle

For this stage, the block looks good 🚀 
No other changes are required.

**Pull request merged**
